### ISSUE TITLE
nxos_ssh hostname not working on merge operation

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#1005]
Rollback also looks like it is probably broken.

**Comment by ktbyers** [comment]
See related PR https://github.com/napalm-automation/napalm/pull/999

**Comment by ktbyers** [comment]
FYI @lazhao123

**Comment by lazhao123** [comment]
Hello Kirk,

I have a question. How do I remove a setup from configuration. Say, I want
to remove static route under vrf management.

vrf management
  no ip route 0.0.0.0 0.0.0.0 192.168.1.1
  ip route 0.0.0.0 0.0.0.0  192.168.2.1

What would I put in the json file?
My proposal:
"vrf": [
  {
  "name": "management",
  "action": "no",
  "ip": "0.0.0.0",
  "mask": "0.0.0.0",
  "gw": "192.168.1.1"
  }
  {
  "name": "management",
  "ip": "0.0.0.0",
  "mask": "0.0.0.0",
  "gw": "192.168.2.1"
  }
]

How my Jinja2 template handle this json file? I can't find any info
regarding update configuration other than initial deployment. Do you have
any reference link that you can share?

Thank you
-Lawrence

**Comment by ktbyers** [comment]
@lazhao123 Should open that as a separate issue or ping people in Slack.

Regards, Kirk
