### ISSUE TITLE
remove vlan related question

### ISSUE THREAD

**Issue by lazhao123** [napalm-automation/napalm#1008]
Currently what I do is to add configuration, what if I need to remove a configuration like removing a vlan. What is the right approach?

**Comment by carlniger** [comment]
If possible you could use config replace instead of a merge operation. if that isn't possible for you, you'd need to handle it in whatever way makes sense for your environment... not exactly an easy problem to solve though! :)

**Comment by ktbyers** [comment]
Yes, I would echo @carlniger and say the declarative way to do it would be to use full configuration replace and that configuration would contain the vlans that should exist on the switch.
