### ISSUE TITLE
Cisco IOS configure replace issue with nonegotiate under an interface

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#1009]
Cisco IOS/IOS-XE will fail when using `configure replace` if going between the following two states:

```
interface GigabitEthernet0/1/3
 switchport mode access
 switchport nonegotiate
```

And tried to change it to this state:

```
interface GigabitEthernet0/1/3
 switchport mode trunk
 switchport nonegotiate
```

**Comment by ktbyers** [comment]
Additional details:
----------

```
cisco3#show archive config differences flash:candidate_config.txt 

!Contextual Config Diffs:
interface GigabitEthernet0/1/3
 +switchport mode trunk
interface GigabitEthernet0/1/3
 -switchport mode access


cisco3#show run int gigabitEthernet 0/1/3
Building configuration...

Current configuration : 86 bytes
!
interface GigabitEthernet0/1/3
 switchport mode access
 switchport nonegotiate
end
```

```
cisco3#configure replace flash:candidate_config.txt force revert trigger error 


Command rejected: An interface must be configured to the "Access" or "Trunk" modes to be configured to "NoNegotiate."
Failed to apply command  no switchport mode access
Aborting Rollback.

Rollback failed.Reverting back to the original configuration: flash:cisco3-cfg-Jun-28-20-02-46.327-17 ...


Total number of passes: 0
Rollback Done

The original configuration has been successfully restored.

```

**Comment by ktbyers** [comment]
cisco3#show version
Cisco IOS XE Software, Version 16.08.01
Cisco IOS Software [Fuji], ISR Software (ARMV8EB_LINUX_IOSD-UNIVERSALK9_IAS-M), Version 16.8.1, RELEASE SOFTWARE (fc3)

**Comment by TheRealBecks** [comment]
Just to be sure: If you enter the following commands, the configuration change will be committed?
`conf t
interface GigabitEthernet0/1/3
switchport mode trunk`

**Comment by ktbyers** [comment]
@TheRealBecks Yes, it works fine if you configure it manually via `conf t`.

**Comment by TheRealBecks** [comment]
In that case I would say: Happy bug finding day! :) As 'configure replace' isn't working, but the manual method is, you should escalate that to Cisco directly.

So this 'bug' here can be closed as it's no bug in the napalm repository?

**Comment by ktbyers** [comment]
Going to close as there are no actions to take on the napalm side. Hoping Cisco will fix this as it looks like an IOS bug.
