### ISSUE TITLE
IOS-XR putting hashes in the diff output

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#1015]
Reported in Slack

When i `replace` a config, if the config is fresh (the configuration does not exists) there is no issue. However if i do a `replace` when there is configuration and i `replace` new for old - the `hash` symbols appear, for example…

```
Replace Loopback Interfaces

Diff:
#  interface Loopback100
#   description ***MERGE LOOPBACK 100****
#   description ***REPLACE LOOPBACK 100****
#   ipv4 address 1.1.1.100 255.255.255.255
#   ipv4 address 3.3.3.100 255.255.255.255
#  !
```

I am using `6.5.2` - but i have seen this on images on XR since `5.x.x`

**Comment by max-cz** [comment]
I tested it on 5.2.2, but I was not able to replicate the problem.
Can you provide more information about it?

**Comment by aroramanish2009** [comment]
Hi @max-cz 
I am seeing the same issue, using the replace config option. In my case, I am seeing Diff populated with changes which are not real as nothing is being changed or committed to the device. I only see this issue with following in the configuration:
1. ACL 
2. Interface Names 
3. Prefix-set 
4. route-policy 

`#  !
#  ipv4 access-list SNMP-ACL
#   10 permit ipv4 host 10.x.x.x any
#   20 permit ipv4 host 10.x.x.x any
#   30 permit ipv4 host 10.x.x.x any
#  !
+  interface MgmtEth0/RP0/CPU0/0
+  !
+  interface TenGigE0/0/0/0/0
+  !
+  interface TenGigE0/0/0/0/1
+  !
+  interface TenGigE0/0/0/1/0
`
Please let me know if you need more information.

**Comment by ktbyers** [comment]
@aroramanish2009 Which version of NAPALM are you using?

I thought I might have fixed this earlier (would need to double check though as it was a while ago).

**Comment by aroramanish2009** [comment]
Hi @ktbyers 
The version I am running might be old, I can certainly try to upgrade and retest it. 

napalm-ansible         0.10.0

I will update the thread if upgrading resolves the issue. 
Thank you

**Comment by aroramanish2009** [comment]
Update: 
Upgraded to "napalm-ansible         1.0.0" using PIP
Same issue observed with diff, it tries commits ACL/Prefix-Set and RPL again even though nothing changes.

**Comment by ktbyers** [comment]
It is more a question of which version of NAPALM (napalm-ansible is largely a wrapper for the NAPALM library):

`pip list | grep napalm`

**Comment by aroramanish2009** [comment]
I was running napalm version 2.4.0, upgraded it to 3.0.0 but now I started to run into some netmiko error. Let me try to troubleshoot it. 
```
  File "/usr/local/ansible/2.7.0/lib/python2.7/site-packages/netmiko/cisco_base_connection.py", line 143
    msg = f"Login failed: {self.host}"
                                     ^
SyntaxError: invalid syntax
```

```
napalm                 3.0.0
napalm-ansible         1.0.0
```

**Comment by aroramanish2009** [comment]
```
napalm                 2.5.0
napalm-ansible         1.0.0
netmiko                2.4.2
```
Login issue is resolved with above combination but the diff file issue persists in version 2.5.0. Unable to resolve invalid syntax issue with version 3.0.0, interesting thing is that gather facts works with 3.0.0 and I see a successful login in router logs.

**Comment by ktbyers** [comment]
Python 2.7 is no longer supported.

You need to test with Netmiko 3.1.0 and NAPALM 3.0.0 ( the latest released version). Realistically we are not going to fix any issue on the old version (i.e. we would need to be working on the current code-base).

Thanks, Kirk

**Comment by aroramanish2009** [comment]
Let me try to test it out with Python 3 and get back to you.

**Comment by ktbyers** [comment]
@aroramanish2009 Sounds good.

**Comment by jbotello7381** [comment]
I thought to add my comments here since this is something I'm been actively working with Cisco.  

The issue mentioned by @aroramanish2009 is been fixed by Cisco.

`ncs5500-parser-2.0.0.1-r653.CSCvr17274
`

In the lab, I'm using 6.5.3 with the fix applied

I'm currently asking Cisco to see if they can fix how they generate the config diff when performing configuration replace, which is what we use in our automation workflow.  

This summarizes my current request to Cisco

```
From cisco documentation there are two ways to display the diff

show configuration change diff (show diff candidate vs. running if commit replace is executed)

and

show commit changes diff (show diff candidate vs. running)

If i remove the route-policy and then show the diff, i get the following

RP/0/RP0/CPU0:er06.lab01(config)#router bgp 65000
RP/0/RP0/CPU0:er06.lab01(config-bgp)# neighbor 62.115.186.50
RP/0/RP0/CPU0:er06.lab01(config-bgp-nbr)#address-family ipv4 unicast
RP/0/RP0/CPU0:er06.lab01(config-bgp-nbr-af)#no route-policy DROP in
RP/0/RP0/CPU0:er06.lab01(config-bgp-nbr-af)#no route-policy DROP out
RP/0/RP0/CPU0:er06.lab01(config-bgp-nbr-af)#
RP/0/RP0/CPU0:er06.lab01(config-bgp-nbr-af)#exit
RP/0/RP0/CPU0:er06.lab01(config-bgp-nbr)#exit
RP/0/RP0/CPU0:er06.lab01(config-bgp)#show commit changes diff
Thu Feb  6 08:30:21.109 UTC
Building configuration...
!! IOS XR Configuration version = 6.5.3
   router bgp 65000
    neighbor 62.115.186.50
     address-family ipv4 unicast
-     route-policy DROP in
-     route-policy DROP out
     !
    !
   !
end


If i do a full config replace, where the candidate config only different is the removal of the route-policies, i get the following

RP/0/RP0/CPU0:er06.lab01(config)#show configuration changes diff
Thu Feb  6 08:29:22.226 UTC
Building configuration...
!! IOS XR Configuration version = 6.5.3
-  router bgp 65000
-   neighbor 62.115.186.50
-    address-family ipv4 unicast
-     route-policy DROP in
-     route-policy DROP out
-    !
-   !
-  !
end
 
When effectively, the change only removes the route-policy DROP in and out (Not the entire neighbor/bgp config as can be assumed here), the output is confusing for our engineers and making them nervous when reviewing the changes.
```

The use of # for line configuration changes is also confusing, and hopefully, Cisco make changes on how they generate and output the configuration diffs

**Comment by aroramanish2009** [comment]
@jbotello7381 
This was really helpful, I applied the Service Pack 2 with the IOS-XR fix and it fixed the issue I was seeing with ACL/RPL etc. 
Thank you very much.

**Comment by ktbyers** [comment]
I am going to close this issue as I don't believe there is any work to be done on the napalm side. Just let us know if that is not correct.
