### ISSUE TITLE
IOS-XE Official Support?

### ISSUE THREAD

**Issue by masters3d** [napalm-automation/napalm#1036]
### Description of Issue/Question

Is there any plans to officially support IOS-XE?  My understanding is that IOS-XE has different command mapping than IOS-XR. 
https://www.routexp.com/2017/05/cisco-ios-and-cisco-ios-xr-command.html

**Comment by itdependsnetworks** [comment]
It is, and documented as such here https://napalm.readthedocs.io/en/latest/support/index.html

**Comment by masters3d** [comment]
I see XR but I am not finding XE.

**Comment by ktbyers** [comment]
Just use the Cisco IOS driver. IOS-XE should behave very similarly to Cisco IOS.
