### ISSUE TITLE
"Error [1005]: CLI command 1 of 2 'enable' failed:" when accessing Arista switch with enable secret configured

### ISSUE THREAD

**Issue by dpizzle** [napalm-automation/napalm#1039]
### Description of Issue/Question

I'm trying to access an Arista 7150S switch running `4.20.11.1M`. It works when no enable password is set, but I get the below error when the enable password is set. The user credentials remain the same.

I've seen this issue posted before, but no solution.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq

- [x] Yes
- [ ] No

### napalm version

```
# pip list --format freeze | grep napalm
napalm==2.4.0
```

### Network operating system version

```
Arista DCS-7150S-64-CL-R
Hardware version:    01.05

Software image version: 4.20.11.1M-2GB
Architecture:           i386
Internal build version: 4.20.11.1M-2GB-11019656.420111M
Internal build ID:      f3706e44-a6fb-451c-a7b1-dca5609c78a4
```

### Error Traceback

```
>>> import napalm
>>> driver = napalm.get_network_driver("eos")
>>> device = driver(hostname="arista_01", username="test_user", password="test_pass", optional_args = {"transport": "http"})
>>> device.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/napalm/eos/eos.py", line 142, in open
    self.device.run_commands(["show clock"], encoding="text")
  File "/usr/lib/python3.6/site-packages/pyeapi/client.py", line 730, in run_commands
    response = self._connection.execute(commands, encoding, **kwargs)
  File "/usr/lib/python3.6/site-packages/pyeapi/eapilib.py", line 499, in execute
    response = self.send(request)
  File "/usr/lib/python3.6/site-packages/pyeapi/eapilib.py", line 418, in send
    raise CommandError(code, msg, command_error=err, output=out)
pyeapi.eapilib.CommandError: Error [1005]: CLI command 1 of 2 'enable' failed: permission to run command denied
```

**Comment by mirceaulinic** [comment]
Hey @dpizzle - it looks like there's an optional arg `enable_password`, incidentally, for EOS only: https://napalm.readthedocs.io/en/latest/support/index.html#list-of-supported-optional-arguments. Can you check that and confirm it works as expected?

**Comment by dpizzle** [comment]
Hi @mirceaulinic - I now have a different error.

```
>>> import napalm
>>> driver = napalm.get_network_driver("eos")
>>> device = driver(hostname="arista_01", username="test_user", password="test_pass", optional_args = {"transport": "http", "enable_password": "test_enable"})
>>> device.open()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/napalm/eos/eos.py", line 142, in open
    self.device.run_commands(["show clock"], encoding="text")
  File "/usr/lib/python3.6/site-packages/pyeapi/client.py", line 730, in run_commands
    response = self._connection.execute(commands, encoding, **kwargs)
  File "/usr/lib/python3.6/site-packages/pyeapi/eapilib.py", line 499, in execute
    response = self.send(request)
  File "/usr/lib/python3.6/site-packages/pyeapi/eapilib.py", line 418, in send
    raise CommandError(code, msg, command_error=err, output=out)
pyeapi.eapilib.CommandError: Error [1005]: CLI command 1 of 2 'enable'(input='test_enable') failed: permission to run command denied
```

Separately, If I remove the enable password from the switch and leave the user credentials as they are, I am able to connect and collect facts. Does the enable password need to be passed when connecting irrespective of user privileges?

**Comment by ktbyers** [comment]
@dpizzle I think the fundamental issue is you need high enough privileges for the commands to execute (regardless of whether you have enable secret or not).

In both of the above cases you are getting:

```
failed: permission to run command denied
```

That makes me think you have AAA authorization configured or that the enable secret is not taking you to privilege 15.


Here is me connecting to EOS with a priv 15 user and no enable secret:

```
In [1]: import napalm

In [2]: driver = napalm.get_network_driver("eos")

In [3]: device = driver(hostname="arista1.domain.com", username="admin", password="foo")

In [4]: device.open()                                                                                                                                                    

In [5]: device.get_facts()
Out[5]: 
{'hostname': 'arista1',
 'fqdn': 'arista1',
 'vendor': 'Arista',
 'model': 'vEOS',
 'serial_number': '',
 'os_version': '4.20.10M-10040268.42010M',
 'uptime': 12927182,
 'interface_list': ['Ethernet1',
  'Ethernet2',
  'Ethernet3',
  'Ethernet4',
  'Ethernet5',
  'Ethernet6',
  'Ethernet7',
  'Management1',
  'Vlan1']}
```

**Comment by ktbyers** [comment]
A bit more details...pyeapi the underlying library that NAPALM uses for Arista by default makes an `enable` call when executing run_commands (which napalm does).

That is the call you are failing on with both of the above outputs that you posted.

**Comment by dpizzle** [comment]
Hi @ktbyers, when trying to pass the enable password, I still get the below error -

```
pyeapi.eapilib.CommandError: Error [1005]: CLI command 1 of 2 'enable'(input='test_enable') failed: permission to run command denied
```

I also find it confusing that when using the same user credentials without providing an enable password, works when the device doesn't have an enable password set, but fails when I set an enable password. The user credentials have the same privileges in both tests. Would setting an enable password on the switch change something? (_Maybe having a dumb moment_)

**Comment by ktbyers** [comment]
What is the privilege of the user?

And do you have AAA-authorization configured?

Kirk

**Comment by dpizzle** [comment]
Current privilege level is 1. Only aaa authorization config is -

```
aaa authorization exec default local group radius
```

**Comment by sindhujit1** [comment]
I faced the same issue using threads in python. Seems like using too many threads( I used 200) running parallely may be a cause this issue.

**Comment by ktbyers** [comment]
I think this issue is now stale...I am going to close. If there is follow-up work to be done here, just re-open it.
