### ISSUE TITLE
Is there a reason the documentation builds stopped?

### ISSUE THREAD

**Issue by jdillard** [napalm-automation/napalm#1040]
### Description of Issue/Question

It looks like the Read The Docs builds stopped 8 months ago: https://readthedocs.org/projects/napalm/builds/

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [ ] No

**Comment by mirceaulinic** [comment]
I think the documentation should only be generated on new version being released, which is when we've released 2.4.0: https://pypi.org/project/napalm/#history.

**Comment by mirceaulinic** [comment]
I think you are right @jdillard. I've added a webhook which should normally ensure to rebuild the docs on PR merge. You can find the develop version at https://napalm.readthedocs.io/en/develop/.

**Comment by ktbyers** [comment]
Thanks @mirceaulinic !
