### ISSUE TITLE
lock prevent to load new candidate config

### ISSUE THREAD

**Issue by blahu** [napalm-automation/napalm#1041]
### Description of Issue/Question

It's a question rather than an fault description.
We are writing a script that checks if running-config matches the file provided by configuration automation.
To do that we are uploading a new configuration (load_replace_candidate()) and executing compare_config().
Unfortunately sometimes there is already an open session on the box in pending state.
When load_replace_candidate() is executed it runs _lock() function that in case of a pending state will raise an exception SessionLockedException("Session is already in use").

We would like to argue that _lock() should be involved from within commit_config() - this is where it makes more sense to have such check?

Alternatively one could pass a lock/no_lock flag to both or either of the functions

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [ ] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==2.4.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)
I can't do verbatim
```
Arista EOS 4.21.7M
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```

```

**Comment by ktbyers** [comment]
We have a `lock_disable` argument in Juniper. I think it would be fine to add this to EOS (if someone wants to implement the PR on it):

https://github.com/napalm-automation/napalm/blob/develop/napalm/junos/junos.py#L94

**Comment by blahu** [comment]
https://github.com/napalm-automation/napalm/pull/1042

**Comment by mirceaulinic** [comment]
Implemented via #1042.
