### ISSUE TITLE
Documentation typo: duplicated paragraph

### ISSUE THREAD

**Issue by singlaive** [napalm-automation/napalm#1050]
Check this page on the doc site: https://napalm.readthedocs.io/en/latest/tutorials/ansible-napalm.html, as pasted below.

You should easily find the duplication of "if your ansible config is like this..", " do git clone"

Install
To install, clone napalm-ansible into your ansible module path. This will depend on your own setup and contents of your ansible.cfg file which tells ansible where to look for modules. For more in-depth explanation, see the Ansible Docs.

**If your ansible.cfg looks like:**

[defaults]
library = ~/workspace/napalm-ansible
Then you can do the following:

**cd ~/workspace**

git clone
**If your ansible.cfg looks like:**

[defaults]
library = ~/workspace/napalm-ansible
Then you can do the following:

cd ~/workspace

git clone https://github.com/napalm-automation/napalm-ansible.git

**Comment by mirceaulinic** [comment]
@singlaive feel free to open a PR to address this, and we shall review.
