### ISSUE TITLE
get_environment() error on ios device.

### ISSUE THREAD

**Issue by hasri20** [napalm-automation/napalm#1057]
i got some issue when running get_environment() on ios on linux device.

### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==2.4.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
R3#show version 
Cisco IOS Software, Linux Software (I86BI_LINUX-ADVENTERPRISEK9-M), Version 15.4(2)T4, DEVELOPMENT TEST SOFTWARE
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
File "~/.local/lib/python3.6/site-packages/napalm/ios/ios.py", line 1860, in get_environment
    total_mem = int(proc_total_mem) + int(io_total_mem)
UnboundLocalError: local variable 'io_total_mem' referenced before assignment
```

**Comment by netwninja** [comment]
I ran the below NAPALM script and not seeing the issue 

```
R1#show version | in IOS
Cisco IOS Software, IOSv Software (VIOS-ADVENTERPRISEK9-M), Version 15.6(1)T, RELEASE SOFTWARE (fc1)
ROM: Bootstrap program is IOSv
Cisco IOSv (revision 1.0) with  with 984441K/62464K bytes of memory.
R1#


root@napalm:~# cat ios1.py 
import json
from napalm.base import get_network_driver
driver = get_network_driver('ios')
dev = driver(hostname='r1', username='ansible', password='ansible123')
dev.open()
dev_info = dev.get_bgp_neighbors()
dev.close()
print(json.dumps(dev_info, sort_keys=True, indent=4))

root@napalm:~# python ios1.py 
{
    "cpu": {
        "0": {
            "%usage": 26.0
        }
    }, 
    "fans": {
        "invalid": {
            "status": true
        }
    }, 
    "memory": {
        "available_ram": 923999904, 
        "used_ram": 115113364
    }, 
    "power": {
        "invalid": {
            "capacity": -1.0, 
            "output": -1.0, 
            "status": true
        }
    }, 
    "temperature": {
        "invalid": {
            "is_alert": false, 
            "is_critical": false, 
            "temperature": -1.0
        }
    }
}

root@napalm:~# pip freeze | grep napalm
You are using pip version 8.1.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
napalm==2.4.0
napalm-base==1.0.0
napalm-eos==0.6.1
napalm-ios==0.8.1
root@napalm:~# 

```

**Comment by netwninja** [comment]
```
root@napalm:~# python ios1.py 
{
    "cpu": {
        "0": {
            "%usage": 15.0
        }
    }, 
    "fans": {
        "invalid": {
            "status": true
        }
    }, 
    "memory": {
        "available_ram": 923999904, 
        "used_ram": 115113844
    }, 
    "power": {
        "invalid": {
            "capacity": -1.0, 
            "output": -1.0, 
            "status": true
        }
    }, 
    "temperature": {
        "invalid": {
            "is_alert": false, 
            "is_critical": false, 
            "temperature": -1.0
        }
    }
}
root@napalm:~# cat ios1.py 
import json
from napalm import get_network_driver
driver = get_network_driver('ios')
dev = driver(hostname='r1', username='ansible', password='ansible123')
dev.open()
#dev_info = dev.get_bgp_neighbors()
dev_info = dev.get_environment()
dev.close()
print(json.dumps(dev_info, sort_keys=True, indent=4))

root@napalm:~# 

```

**Comment by mirceaulinic** [comment]
Can you try with napalm 2.5.0? This should normally be fixed, unless there's a different issue.

**Comment by TheRealBecks** [comment]
@netwninja Please test with the current version, thanks!

**Comment by zeddD1abl0** [comment]
I know this is an ANCIENT issue, but I'm encountering this issue currently on, what I can assume, is the latest version of NAPALM:

`
>>> dev_info = dev.get_environment()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/netbox-3.3.10/venv/lib64/python3.9/site-packages/napalm/ios/ios.py", line 2381, in get_environment
    if temp_value > system_temp_alert:
UnboundLocalError: local variable 'temp_value' referenced before assignment
`

I am happy to help troubleshoot if someone has something they'd like me to do.

**Comment by bewing** [comment]
This is most likely a new issue, in that whatever device you are running isn't matching the `re.compile("(.*) Temperature Value") ` 

Can you open a new issue, and include the output of `show env temperature status` from the device in question?
