### ISSUE TITLE
get_bgp_config errors out on EOS

### ISSUE THREAD

**Issue by AmbicaY** [napalm-automation/napalm#1113]
get_bgp_config errors out on some Arista devices.

Error:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 178, in call
            out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
          File "/usr/local/lib/python2.7/dist-packages/napalm/eos/eos.py", line 850, in get_bgp_config
            local_as = int(bgp_conf_line.replace("router bgp", "").strip())
        ValueError: invalid literal for int() with base 10: '65101.65101'

Looking at the code, the command "show running-config | section router bgp" gives the output as:
router bgp 65101.65101
.......

The code is trying to capture 11111.11111 as an integer and thats where its failing.

**Comment by TheRealBecks** [comment]
There are two possible ways to represent a BGP AS number:
> arista-test(config)#router bgp ?
  64512                Configure BGP AS 64512
  <1-4294967295>       AS Number
  <1-65535>.<0-65535>  AS Number in asdot notation

See [Cisco documentation](https://www.cisco.com/c/en/us/products/collateral/ios-nx-os-software/border-gateway-protocol-bgp/white_paper_c11_516829.html) for more information. The ASN can be represented as integer or when using the dotted notation as string. @mirceaulinic So what's the best approach here? Using a string so it will be compatible with both notations?

**Comment by mirceaulinic** [comment]
Only now seeing this, sorry... we have a helper in the napalm base: https://github.com/napalm-automation/napalm/blob/8deb8b6447098d16139c4fe77a67061838121fd6/napalm/base/helpers.py#L367

When used in the context @AmbicaY mentioned, for example, it'd give:

```python
>>> import napalm.base.helpers
>>> napalm.base.helpers.as_number('65101.65101')
4266524237
```

That should be an easy fix, let me PR that quickly.

**Comment by mirceaulinic** [comment]
Would any of you try #1191 and confirm it works well? My changes also touched a couple other methods besides `get_bgp_config`: `get_route_to` and `get_bgp_neighbors` - so I'd appreciate if you could test those too.
