### ISSUE TITLE
Documentation build on readthedocs.org is failing due to Black and PY27

### ISSUE THREAD

**Issue by TheRealBecks** [napalm-automation/napalm#1122]
When searching for 'NAPALM python' the first result on google.com is https://napalm.readthedocs.io/en/latest/
That documentation refers to NAPALM version 1 and when looking at https://readthedocs.org/projects/napalm/ I can see that the build process breaks. Two people are registered as maintainers: @mirceaulinic @dbarrosop 
Is there any chance to get the build process working again?

**Comment by ktbyers** [comment]
The `latest` here: https://napalm.readthedocs.io/en/latest/ looks to be NAPALM2. Why do you say it is NAPALM version1?

@TheRealBecks

**Comment by ktbyers** [comment]
Docs build is failing due to trying to use Python2.7 with Black.

**Comment by TheRealBecks** [comment]
The HTML title says it's "NAPALM 1" and now I found out where that (wrong) information comes from: https://github.com/napalm-automation/napalm/blob/develop/docs/conf.py#L67

**Comment by ktbyers** [comment]
This should be fixed:

https://readthedocs.org/projects/napalm/builds/

**Comment by TheRealBecks** [comment]
Yes, it works, thanks a lot!
If someone needs the current documentation, it can be found here: https://napalm.readthedocs.io/en/develop/
And here we get the documentations for master, stable and develop: https://readthedocs.org/projects/napalm/
...master and stable will be automatically updated with the next NAPALM release.
