### ISSUE TITLE
Adding Custom Method

### ISSUE THREAD

**Issue by bong-asis** [napalm-automation/napalm#1136]
### Description of Issue/Question

This is more of a support question rather than an issue.
I'm trying to follow the documentation below but not having any luck.

https://napalm.readthedocs.io/en/latest/tutorials/extend_driver.html

So basically i wanted to create a custom method for ios.py driver. See the code below. The intention is to parse a string from a specific command. However the changes doesn't seem to take effect, help?

### Method

    def get_string(self, command, string, index, separator=' '):
        result = self._send_command(command)
        result = result.splitlines()
        result = next(x for x in result if string in x)
        result = result.split(separator)
        result = result[index]
        return result

### napalm version

```
2.5
```

**Comment by bong-asis** [comment]
i just edited the ios.py under the napalm/ios/ folder and added the custom method, it worked but i guess that's not the recommended way of doing it.

### Input/Output
driver = get_network_driver('ios')
ios = driver('10.255.100.10', 'admin', 'cisco')
ios.open()
ios.get_string('show ip route', 'last resort', -4)
Out[7]: '10.255.1.1'
ios.get_string('show ip cef', 'attached', -1)
Out[8]: 'GigabitEthernet0/1.100'

**Comment by itdependsnetworks** [comment]
You show a code snippet, but it’s more about folder structure and system path. I suspect your custom driver is not found for one of those reasons

**Comment by bong-asis** [comment]
So i did exactly this.

1. created a new folder under napalm called custom_napalm (napalm/custom_napalm)
2. under napalm/custom_napalm folder, i have two files, __init__.py and ios.py. however that doesn't seem to be helping as i still could not call the new method. please help?

### contents of the ios.py
'''
from napalm.ios.ios import IOSDriver
class CustomIOSDriver(IOSDriver):
    """Custom NAPALM Cisco IOS Handler."""
    def get_my_custom_method(self):
        pass
    def get_string(self, command, string, index, separator=' '):
        result = self._send_command(command)
        result = result.splitlines()
        result = next(x for x in result if string in x)
        result = result.split(separator)
        result = result[index]
        return result
'''

**Comment by itdependsnetworks** [comment]
From anywhere the /tmp directory can you import that module in the python interpreter shell? If you cannot, adjust your system path, which is a question best suited for google, as there are multiple options and not specific to this project. 

If you can show that from the /tmp directory you enter the python interpreter and can import get_string, I’ll take a deeper look.

**Comment by bong-asis** [comment]
All good here. So instead of creating the folder inside venv/lib/site-packages/napalm i created the folder outside of napalm, that is venv/lib/site-packages/custom-napalm and then put the ios.py file in it, without the init.py as stated in the tutorial. I am now able to call the method for the ios object, which is cool. Thanks for your help!

**Comment by mirceaulinic** [comment]
@bong-asis I'm going to close this issue, as it sounds like you found the solution. Feel free to comment here if you have further questions, and I shall reopen.
