### ISSUE TITLE
IOS-driver: Allow usage of user-exec functions without the need of priv exec mode/enable secret

### ISSUE THREAD

**Issue by remingu** [napalm-automation/napalm#1139]
### Description of Issue/Question

By default driver('ios').open() will fail if the user does not provide an enable secret or has already privilege-level 15. 
It is not unusual that users are limited to lower privilege levels (8 for example).
Many getter functions inside napalm do not necessarily require priv exec level 15 and can be already performed in user-exec mode(priv1).

This is caused by the invocation of self._netmiko_device.enable() inside 
| napalm:base:networkdriver:_netmiko_open()
This will trigger netmikos enable(). This is perfectly fine when called from netmiko specifically whenever needed.
Without access to priv exec (priv 15) the ios-driver will fail completely.
It would work just fine without priv exec mode(15) for many purposes, but this behavior makes it unusable in that certain kind of deployments.

Also enable mode is  device-specific, therefore it should be probably invoked from inside the according driver and not generically from the basedriver, 

I created pull request #1138 . Please have a look.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==2.5.0
napalm-gaia==0.0.8
```

### Network operating system version
Cisco IOS generic behavior- applies to 12.2/12.4, 15, 16
refer CISCO IOS User Security Configuration Guides 
```

```

### Steps to Reproduce the Issue

```
#!/usr/bin/env python3

from napalm import get_network_driver

driver = get_network_driver('ios')
device = driver('192.168.10.165', 'cisco', 'test12')
device.open()
device.close()
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "/home/remingu/code/napalm/test.py", line 10, in <module>
    device.open()
  File "/home/remingu/code/napalm/napalm/ios/ios.py", line 169, in open
    device_type, netmiko_optional_args=self.netmiko_optional_args
  File "/home/remingu/code/napalm/napalm/base/base.py", line 102, in _netmiko_open
    self._netmiko_device.enable()
  File "/home/remingu/code/venv/lib64/python3.7/site-packages/netmiko/cisco_base_connection.py", line 22, in enable
    cmd=cmd, pattern=pattern, re_flags=re_flags
  File "/home/remingu/code/venv/lib64/python3.7/site-packages/netmiko/base_connection.py", line 1470, in enable
    raise ValueError(msg)
ValueError: Failed to enter enable mode. Please ensure you pass the 'secret' argument to ConnectHandler.

```

**Comment by ktbyers** [comment]
I think we should default to  the current behavior (which is try to go into enable mode). This is generally needed for the config-operations and some set of the getters (at least those that require the running-config).

Also changing this behavior is a pretty significant breakage of backwards compatibility which I don't think is worth doing.

I propose we add an optional argument that causes the `enable()` call to not be executed. In other words, we default to the current behavior and allow an optional argument ("enable_mode=False") where this default behavior would be changed (and where NAPALM would not automatically enter enable mode for the NAPALM-Netmiko drivers).

This optional argument should be supported for both IOS and NXOS-SSH (i.e. the NAPALM platforms that use Netmiko in a standard way...IOS-XR is a bit of its own beast).

Does that sound reasonable?

**Comment by remingu** [comment]
Hi, 

My PR does not break api.  So users wouldn't feel a difference as long as they don't rely on specific functions, for these functions a permission error is raised if the necessary privilege level is not available. I thought that might result in a more predictable behavior instead of sending commands and receiving a "invalid input error" message or empty values as it explicitely tells the user what is problem is.
However, I can drop my pull request and instead create a supposal for implementing it that way. Shouldnt take long and both approaches will do the trick, So absolutely reasonable, yes.

regards,
Daniel

**Comment by ktbyers** [comment]
Let's let @mirceaulinic chime in on this.

I have a pretty strong preference for using the optional_args pattern instead of the solution in the PR. 

I am worried about the added complexity in the code and breaking things in a backwards incompatible way (yes, it is possible we don't break things, but we would need to test very thoroughly to make sure we don't).

I also generally think that NAPALM should default to privilege level 15 i.e. that an automation tool with a large configuration component should default to that privilege.

**Comment by remingu** [comment]
i don't think it's overcomplex, seemed to be the nicest solution without breaking things after reading through the source.
permissionErrors might be possibly a point they came with python 3.3, Could be a possible gap for some older systems running python 3.2, But it can be easlily replaced by another error type like RuntimeError or something
Anyways it's about having an option to disable the mandatory need. Personally I don't care if this come with my code or somebody elses. Just thought it might be a nice idea to have something ready when coming along with wishes. Let's see.
  
regards

**Comment by mirceaulinic** [comment]
:wave: 

Yes, I think I'm with Kirk on this one - let's look into an implementation with an optional_args as I believe it'd be much simpler and more straight forward long term speaking. Remember that NAPALM is ultimately an uniform API for both gathering data and loading configuration - or, having a different behaviour per feature (i.e., you can do this, but can't do that with a specific username), seems like it defeats the purpose of the library. Of course, if the user _really_ wants that, they can do so by requesting this explicitly through an optional argument.

**Comment by remingu** [comment]
Hi, 

honestely i'm seeing good reasons for privilege aware apis, especially in large scale environments where different parties want to have a certain level of device access.
However, i can live fine with the optional args variant.
What about the changes for ping(),traceroute() and get_ntp_servers(). (We could discuss that separetely if wanted)  it would allow usage from user exec.

**Comment by mirceaulinic** [comment]
> What about the changes for ping(),traceroute() and get_ntp_servers(). (We could discuss that separetely if wanted) it would allow usage from user exec.

I think we want to ensure the API behaves uniformly for _any_ feature, `traceroute`, `ping`, etc. included. :-)

**Comment by remingu** [comment]
well,  i will close issue and fork the cisco drivers instead.
