### ISSUE TITLE
possible typo in iosdriver?

### ISSUE THREAD

**Issue by remingu** [napalm-automation/napalm#1143]
### Description of Issue/Question

Hi,

while i'm playing with my driver fork ... it's probably nothing, but it doesn't make much sense to me. See the if ttl block.

regards

ios.py:L3196 [traceroute()]

```
        if ttl:
           if isinstance(ttl, int) and 0 <= timeout <= 255:
               command += " ttl 0 {}".format(str(ttl))
        if timeout:
            # Timeout should be an integer between 1 and 3600
            if isinstance(timeout, int) and 1 <= timeout <= 3600:
                command += " timeout {}".format(str(timeout))
```

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
current develop branch(c35d503)
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
n/a
```

### Steps to Reproduce the Issue
n/a
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
n/a
```

**Comment by mirceaulinic** [comment]
Yes, I think that looks a bit :fish: - at least the `command += " ttl 0 {}".format(str(ttl))` which should probably be `command += " ttl {}".format(ttl)` instead. Feel free to open a PR for that @remingu.
