### ISSUE TITLE
LLDP interface showing with quotes

### ISSUE THREAD

**Issue by inetman28** [napalm-automation/napalm#1153]
### Environment
* Python version:  3.6.8
* NetBox version:  2.7.8
* Napalm version: 2.3.3 and 2.5.0

### Steps to Reproduce
1. Use driver EOS and method get_lldp_neighbors_detail

### Expected Behavior
Napalm return me correct key value pair without quotes

### Observed Behavior
As you can see remote_port key have value with quotation marks (see below):

```
         "Ethernet49/1": [
            {
                "parent_interface": "Ethernet49/1",
                "remote_port": "\"Ethernet49/1\"",  
                "remote_port_description": "SOMETHING DESCRIPTION",
                "remote_system_name": "DC1-SW4",
                "remote_system_description": "Arista Networks EOS version 4.22.3M running on an Arista Networks DCS-7060SX2-48YC6",
                "remote_chassis_id": "98:5D:82:62:BD:ВВ",
                "remote_system_capab": [
                    "bridge",
                    "router"
                ],
                "remote_system_enable_capab": [
                    "bridge",
                    "router"
                ]
            }
        ],

```

**Comment by mirceaulinic** [comment]
I don't know if I should laugh or cry (or both). Thanks for reporting @inetman28.

**Comment by TheRealBecks** [comment]
@inetman28 That's not a NAPALM bug, because when you issue "show lldp neighbors detail | json" an an Arista switch you will see that the doubled quotation marks come from there. Here's my example output:
`"interfaceId": "\"Gi0/8\"",`
On Cisco NX-OS 7 the output is as follows:
`"port_id": "Gi0/4"`
So it looks like a wrong output on EOS? Maybe you should file a bug report to Arista?

**Comment by inetman28** [comment]
I create support request to support@arista.com (via email).

**Comment by mirceaulinic** [comment]
I agree, and encourage you to open a case with Arista, however I believe we should correct this on the NAPALM side as well (for regression, moving forward). CC @TheRealBecks @inetman28

**Comment by mirceaulinic** [comment]
Could any of you test #1175 and confirm it works as expected?

**Comment by TheRealBecks** [comment]
@mirceaulinic That fixes the problem, thanks!

**Comment by asergeant01** [comment]
I have it that this will be addressed by Arista.....

> LLDP thing is fixed under Bug 480042 so it should start making it to releases in the next few weeks
> One caveat though is that to preserve existing behaviour (to stop changes from potentially breaking existing automation deployments) we are adding "interfaceId_v2": "Ethernet1 rather then changing interfaceId
