### ISSUE TITLE
NAPALM library not imported when using PyInstaller

### ISSUE THREAD

**Issue by vithubati** [napalm-automation/napalm#1159]
### Description of Issue/Question

I am working on Napalm library integration. everything was working perfectly fine. but when I tried to use Pyinstaller to bundle my application, it doesn't import Napalm dependencies. I get below error in Napalm library
`(‘Cannot import “junos”. Is the library installed?’,)`

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version

```
napalm==2.5.0
```

### Error Traceback

```
(‘Cannot import “junos”. Is the library installed?’,
```
please let me know if I am missing something here

**Comment by ktbyers** [comment]
Doesn't look like a napalm issue. 

At a minimum it looks like you are failing to install some needed dependencies.

**Comment by vithubati** [comment]
no, I am not. it's working properly locally. only when I tried to bundle the application using PyInstaller, the Napalm dependencies are not being picked up. I was thinking if I have something to do with something else I am missing.

**Comment by ktbyers** [comment]
You will probably have to dig around/research on pyinstaller more. It is not something I have any familiarity with.
