### ISSUE TITLE
Eos get_bgp_neighbors is failing on devices due to type mismatch

### ISSUE THREAD

**Issue by sdanelli** [napalm-automation/napalm#1168]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [] Yes
- [x] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==2.5.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
            "version": "4.22.2F-DPE",
```

### Steps to Reproduce the Issue

run get_bgp_neighbors with more than one neighbor on a device with that version. 

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
020-04-13T15:45:18Z
return executor()
2020-04-13T15:45:18Z
File "/usr/local/lib/python3.6/site-packages/olympus_nqa/Device.py", line 144, in _run
2020-04-13T15:45:18Z
return getattr(self.device, method)(*args, **kwargs)
2020-04-13T15:45:18Z
File "/usr/local/lib/python3.6/site-packages/napalm/eos/eos.py", line 504, in get_bgp_neighbors
2020-04-13T15:45:18Z
"uptime": int(time.time() - peer_data["upDownTime"]),
2020-04-13T15:45:18Z
TypeError: unsupported operand type(s) for -: 'float' and 'str'

```

Looks like the code problem is here:
https://github.com/napalm-automation/napalm/blob/develop/napalm/eos/eos.py#L501

I grabbed the output of `show ip bgp summary vrf all` from a non working device and the field is a string (`upDownTime`):
```
       "peers": {
                        "100.98.0.120": {
                            "description": "bad-host",
                            "msgSent": 56860,
                            "inMsgQueue": 0,
                            "prefixReceived": 6,
                            "upDownTime": "1586651008.000000",
                            "version": 4,
                            "prefixAccepted": 6,
                            "msgReceived": 56920,
                            "peerState": "Established",
                            "outMsgQueue": 0,
                            "underMaintenance": false,
                            "asn": "64814"
                        },

```

However on a device that works the field is a float:

```
        "peers": {
                        "100.64.0.8": {
                            "description": "good-host",
                            "msgSent": 2092805,
                            "inMsgQueue": 0,
                            "prefixReceived": 2440,
                            "upDownTime": 1580852047.450348,
                            "version": 4,
                            "msgReceived": 2240470,
                            "prefixAccepted": 2440,
                            "peerState": "Established",
                            "outMsgQueue": 0,
                            "underMaintenance": false,
                            "asn": 64801
```

the working version is:

```
            "version": "4.21.7.1M-DPE",
```

**Comment by mirceaulinic** [comment]
Thanks for reporting @sdanelli, this should be an easy fix. I'd also recommend you to report this to Arista to correct this in the next EOS releases.
