### ISSUE TITLE
nxos.compare_config() returns an error

### ISSUE THREAD

**Issue by vsakpal** [napalm-automation/napalm#1182]
Hello, 
I am experimenting with Napalm and Python, currently looking into the nxos.compare_config() function. However, I get an error which I am pasting in the section below. I do see a candidate_config file created in the archive directory I configured on the device. 

Python version: 3.8
NXOS:nxos.7.0.3.I7.6

Code:
driver = get_network_driver('nxos_ssh')
optional_args = {'use_keys': True, 'allow_agent': True, 'global_delay_factor': 2}
nxos = driver('ip_address', 'username, 'password', optional_args=optional_args)
nxos.open()

nxos.load_replace_candidate(filename="switch.conf")
diff = nxos.compare_config()
print(diff)

Error:

Traceback (most recent call last):
  File "/Users/<username>/PycharmProjects/untitled/netmikonapalmconfigreplace.py", line 14, in <module>
    diff = nxos.compare_config()
  File "/Users/<username>/PycharmProjects/untitled/venv/lib/python3.8/site-packages/napalm/nxos/nxos.py", line 209, in compare_config
    diff = self._get_diff()
  File "/Users/<username>/PycharmProjects/untitled/venv/lib/python3.8/site-packages/napalm/nxos/nxos.py", line 191, in _get_diff
    diff_out.split("Generating Rollback Patch")[1]
IndexError: list index out of range

Any insight would be appreciated.

Thank you!

**Comment by ktbyers** [comment]
Is your file you are uploading ("switch.conf") is this an NX-OS checkpoint file?

**Comment by vsakpal** [comment]
Nope, @ktbyers I simply created a text file with all the configuration from the switch and altered it so I could use it as a comparison with the running-config.

**Comment by vsakpal** [comment]
My idea was also to use this as a means of confirming if the intended config on the device has deviated from what the generated config (via internal tool). 

So I am treating `switch.conf` as a generated config file and comparing that to the actual config on the device to check for any deviation. Is that not possible?

**Comment by Thildemar** [comment]
Best I can tell napalm uses the "show diff rollback-patch" api function for NXOS: https://www.cisco.com/c/m/en_us/techdoc/dc/reference/cli/n5k/commands/show-diff-rollback-patch-file.html

NXOS only allows rollback/diff commands with a checkpoint file instead of a "raw" config.  The checkpoint file is basically a config with the implicit commands also noted with "!#" .  I was able to get this working by adding the checkpoint syntax to my candidate config.  If you look on your device for a "sot_file"  that will be the running config checkpoint napalm creates to compare to.  You can use that as a template for your candidate.  See gotchas here: https://napalm.readthedocs.io/en/latest/support/nxos.html

If anyone knows of a cleaner way to achieve "standard" config diff files with NXOS or has a way to improve the implementation I would be happy to hear it.

**Comment by vsakpal** [comment]
@Thildemar Thank you for your help. I appreciate it :)  I was able to make some progress with your suggestion. The thing I found was the candidate_config file which is uploaded to the device must have the exact name `candidate_config.txt` - took me a while to realize this. 

Secondly, I found that the nxos.compare_config() returns the diff however it would be good to see if we have '+' or '-' indicated. For eg, see the output I pasted below:

**_Output:_**
/Users//PycharmProjects/untitled/netmikonapalmconfigreplace.py
no interface loopback500
no interface loopback400
no interface loopback300

Committing changes

**_Code:_**
nxos.load_replace_candidate(filename='/Users/vsakpal/PycharmProjects/untitled/candidate_config.txt')

#Compare the file differences:
diff = nxos.compare_config()
print(diff)

#Check for diffs
if len(diff) >0:
    print("Committing changes")
    nxos.commit_config()
else:
    print("Configs are identical")

**Comment by Thildemar** [comment]
The + or - diff is something other platforms do, not part of NXOS (Napalm uses the native function to create the diff).  NXOS will output the commands it sees as required to change from current to candidate config, which also means you may see a lot of "no" statements at the top of the diff followed by the replacements lower in the file.

Rollback is created as step 1 in the commit_config() using the built in checkpoints function: https://github.com/napalm-automation/napalm/blob/7b704b59303a64b87cb30bc2dc83aa65780c1a4b/napalm/nxos/nxos.py#L215

**Comment by ktbyers** [comment]
I don't think there are any actions to take here. This thread is basically just discussing the behavior of NX-OS and configuration operations namely:

1. You must use a checkpoint file for full config replace.
2. The diff for a replace operation returns what NX-OS returns
3. The timing of when rollback happens.
