### ISSUE TITLE
IOS: get_interfaces_counters broken with Managment Interface

### ISSUE THREAD

**Issue by ExaneServerTeam** [napalm-automation/napalm#1200]
### Description of Issue/Question
Driver: ios
On call device.get_interfaces_counters() a KeyError is raised on Managment0 beeing missing

This is due to the Managment interface mgmt0 not beeing translated to canonical.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [w] Yes
- [] No

### napalm version
Git Current Develop

### Network operating system version

```
Cisco IOS Software, s6t64 Software (s6t64-ADVENTERPRISEK9-M), Version 15.5(1)SY4, RELEASE SOFTWARE (fc4)
Cisco C6807-XL ( Intel(R) Core(TM) i3-3227U CPU @ 2.50GHz ) processor (revision ) with 2879443K/524288K bytes of memory
```

### Steps to Reproduce the Issue
call to device.get_interfaces_counters()

### Error Traceback
```
Traceback (most recent call last):
  File "list-vlan2.py", line 19, in <module>
    print(yaml.dump(device.get_interfaces_counters()))
  File "/srv/home/adm-brin-f/Devel/pythonspace/test-napalm/.venv/lib/python3.6/site-packages/napalm/ios/ios.py", line 2133, in get_interfaces_counters
    counters[interface]["rx_discards"] = int(match.group("IQD"))
KeyError: 'Management0'
```

**Comment by mirceaulinic** [comment]
Hey @ExaneNetworkTeam - if you submit a PR by mid next week, I'll make sure to release it with 3.0.1. :-) 
Out of curiosity: are you seeing this bug with 2.5.0?

**Comment by ExaneServerTeam** [comment]
@mirceaulinic Pull request available

I can confirm that the bug is not triggered with 2.5.0.

**Comment by mirceaulinic** [comment]
> @mirceaulinic <https://github.com/mirceaulinic> Pull request available
>
> I can confirm that the bug is not triggered with 2.5.0.
>
Okay, great. Thanks for the clarification and PR!
