### ISSUE TITLE
NAPALM 3.0 fails on Python 2.7 due to f-string error

### ISSUE THREAD

**Issue by rrgual** [napalm-automation/napalm#1223]
Hi, Please help me how to deal with this I already install the  NAPALM and Netmiko updates however I cant run  also I already issue this command but still didnt work pip install --upgrade pip enum34

PS: Im using GNS3

Please see the image below for your reference

![NAPALM](https://user-images.githubusercontent.com/65682535/82494670-85899f80-9b1c-11ea-9361-d0ddb0f3b60b.jpg)

**Comment by ktbyers** [comment]
NAPALM is now Python3.6 or greater only.

Python 2.7 doesn't work with the newer version of Napalm (or Netmiko).
