### ISSUE TITLE
Adding OSPF to the GET commands

### ISSUE THREAD

**Issue by alphatwins** [napalm-automation/napalm#1224]
Hi there, i saw this post in the napalm-base from 2017 regarding OSPF being added to the Get, just like get bgp etc. [Link to old post](https://github.com/napalm-automation/napalm-base/issues/216)

Would be awesome to have something like "get_OSPF_neighbors" etc

**Comment by mirceaulinic** [comment]
Hi @alphatwins. I agree it would be awesome, please feel free to open a PR and we shall be happy to review.
Note, we have agreed to only accept new methods when implemented on at least 3 or more NAPALM core platforms.

Cheers!

**Comment by mirceaulinic** [comment]
Feel free to submit a PR directly whenever, as described above. If you have any questions, you're welcome to ask here.
