### ISSUE TITLE
Commit Config issue, not finding the config file

### ISSUE THREAD

**Issue by raikone14** [napalm-automation/napalm#1236]
Hey guys I am trying to test the commit of napalm, but it is not able to finding the cfg file, I also tried to change to "txt", but the same error occurred Here my code:

```
import napalm
import json


driver = napalm.get_network_driver("ios")


device = driver(
    hostname="10.0.0.254",
    username="cisco",
    password="cisco",
    optional_args={"secret" : "cisco"}

)

device.open()

device.load_merge_candidate(filename="config.cfg")
device.commit_config()
device.close() 
```
**### and this is the error,both files are in the same folder:**

> user@user-pc:~/Documents/python_files$ /usr/bin/python3 /home/user/Documents/python_files/network/config_compare.py Traceback (most recent call last): File "/home/user/Documents/python_files/network/config_compare.py", line 18, in device.load_merge_candidate(filename="config.cfg") File "/home/user/.local/lib/python3.8/site-packages/napalm/ios/ios.py", line 315, in load_merge_candidate return_status, msg = self._load_candidate_wrapper( File "/home/user/.local/lib/python3.8/site-packages/napalm/ios/ios.py", line 282, in _load_candidate_wrapper (return_status, msg) = self._scp_file( File "/home/user/.local/lib/python3.8/site-packages/napalm/ios/ios.py", line 620, in _scp_file return self._xfer_file( File "/home/user/.local/lib/python3.8/site-packages/napalm/ios/ios.py", line 670, in _xfer_file with TransferClass(**kwargs) as transfer: File "/home/user/.local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 278, in FileTransfer return FileTransferClass(*args, **kwargs) File "/home/user/.local/lib/python3.8/site-packages/netmiko/scp_handler.py", line 80, in init self.source_md5 = self.file_md5(source_file) File "/home/user/.local/lib/python3.8/site-packages/netmiko/scp_handler.py", line 257, in file_md5 with open(file_name, "rb") as f: FileNotFoundError: [Errno 2] No such file or directory: 'config.c

**Comment by ktbyers** [comment]
Which directory is "config.cfg" located in (full-path)?

**Comment by raikone14** [comment]
> Which directory is "config.cfg" located in (full-path)?

hey tks, but both are in the same folder my code and my config file, should I use the full path in is case ?

**Comment by ktbyers** [comment]
Your program is here:

/home/user/Documents/python_files/network/config_compare.py


Your current working directory is:

user@user-pc:~/Documents/python_files$

So which one of those two directories is config.cfg located in?

**Comment by raikone14** [comment]
> Your program is here:
> 
> /home/user/Documents/python_files/network/config_compare.py
> 
> Your current working directory is:
> 
> user@user-pc:~/Documents/python_files$
> 
> So which one of those two directories is config.cfg located in?

Hey, tks again for your reply,
This are the path of my files,at least when I do a copy path in visual studio:
/home/users/Documents/python_files/network/config_compare.py
/home/users/Documents/python_files/network/config.cfg
