### ISSUE TITLE
No data to return in get_environment

### ISSUE THREAD

**Issue by luqasz** [napalm-automation/napalm#1238]
### Description of Issue/Question

This is more of a dev question. In cases where I can not return any valid data for `get_environment` or any other, what napalm driver shoudl do ?
* raise exception
* return empty dict 

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq

- [x] Yes

### napalm version
```
napalm==2.5.0
```

### Network operating system version
Affects all devices

### Steps to Reproduce the Issue
Difficult to reproduce. Once MikroTik doesn't report any `/system resource print`, it will stay like that.

**Comment by mirceaulinic** [comment]
I'd say the following general rule of thumb:

- Error when there's something the users should do for the correct functionality (e.g., enable specific option or protocol), and document that as a caveat. See for example https://github.com/napalm-automation/napalm/blob/develop/napalm/ios/ios.py#L1911-L1912.
- Return empty when there's nothing you can do (i.e., the device doesn't return this information, and there's no other way to gather it) - but log a warning to inform the user.

Sounds good?

**Comment by luqasz** [comment]
Thx for clarification.
