### ISSUE TITLE
Parameters docstring read wrong by Sphinx in get_route_to method

### ISSUE THREAD

**Issue by hellt** [napalm-automation/napalm#1243]
### Description of Issue/Question

The parameters for get_route_to method are a bit messed up (longer mixed with protocol) - https://napalm.readthedocs.io/en/latest/base.html#napalm.base.base.NetworkDriver.get_route_to

Although the docstring at the commit when the docs were built seems to be correct...

**Comment by mirceaulinic** [comment]
Thanks for reporting. Yes, that seems to always be the case where we have ``(optional)``, should probably just move it after the column, i.e., `param source: (optional)` instead of `param source (optional):`.

**Comment by mirceaulinic** [comment]
Fixed by #1319.
