### ISSUE TITLE
error ios.commit_config()

### ISSUE THREAD

**Issue by ndricimdanaj** [napalm-automation/napalm#1258]
error ios.commit_config()
please help, any idea how to resolve 

from napalm import get_network_driver

driver = get_network_driver('ios')

optional_args = {'secret': 'cisco'} #cisco is the enable password
ios = driver('10.1.1.40', 'admin', 'cisco', optional_args=optional_args)
ios.open()

ios.load_replace_candidate(filename='config.txt')

diff = ios.compare_config()
#print(diff)
if len(diff):
    print(diff)
    print('Commit changes...')
    ios.commit_config()
![error 3 napalm](https://user-images.githubusercontent.com/40867730/88043313-928f3300-cb4d-11ea-9543-06c0d3c7ed2a.png)

    print('Done')
else:
    print('No changes required')
    ios.discard_config()

answer = input('Rollback config?')
if answer == 'yes':
    ios.rollback()

ios.close()

**Comment by mirceaulinic** [comment]
> please help, any idea how to resolve

Read the error message.

See also https://napalm.readthedocs.io/en/latest/support/ios.html#archive.
