### ISSUE TITLE
napalm_merge_cadidate_issue

### ISSUE THREAD

**Issue by narayanankl** [napalm-automation/napalm#1274]
Dear Team,

I have been keep trying to test loading acl with the help of napalm, but it keeps showing below the error.

Traceback (most recent call last):
File "napalmconfig1.py", line 19, in
iosvl2.load_merge_candidate(filename='acl.cfg')
File "/usr/local/lib/python3.8/dist-packages/napalm/ios/ios.py", line 315, in load_merge_candidate
return_status, msg = self._load_candidate_wrapper(
File "/usr/local/lib/python3.8/dist-packages/napalm/ios/ios.py", line 282, in _load_candidate_wrapper
(return_status, msg) = self._scp_file(
File "/usr/local/lib/python3.8/dist-packages/napalm/ios/ios.py", line 620, in _scp_file
return self._xfer_file(
File "/usr/local/lib/python3.8/dist-packages/napalm/ios/ios.py", line 673, in _xfer_file
if transfer.check_file_exists() and transfer.compare_md5():
File "/usr/local/lib/python3.8/dist-packages/netmiko/scp_handler.py", line 215, in check_file_exists
raise ValueError("Unexpected output from check_file_exists")
ValueError: Unexpected output from check_file_exists

**Comment by ktbyers** [comment]
@narayanankl Which version of NAPALM and Netmiko are you using? Please make sure you are using the latest released version.

Do you have `archive` configured and `secure copy` enabled on the device?

https://napalm.readthedocs.io/en/latest/support/ios.html#archive

Also are you at privilege level 15 (i.e. does the user you login with have privilege 15 permissions)?

**Comment by narayanankl** [comment]
@ktbyers , thanks for your response, yes, I have enabled archive and scp, but still the same error, also I can confirm the user is alligned with privilege level 15.

**Comment by narayanankl** [comment]
@ktbyers , hello is there any way to sort out this? I really stuck to proceed further :(, you r help would be much appreciated :)

**Comment by ktbyers** [comment]
@narayanankl What does `dir` on this failing device show?

**Comment by narayanankl** [comment]
@ktbyers , please find the dir output

SW1#dir
Directory of flash0:/

    1  drw-           0  Jan 30 2013 00:00:00 +00:00  boot
  264  drw-           0  Oct 14 2013 00:00:00 +00:00  config
  267  -rw-   107590528  Mar 22 2017 00:00:00 +00:00  vios_l2-adventerprisek9-m
  268  -rw-      524288  May 22 2020 11:51:56 +00:00  nvram
  269  -rw-         325   Oct 4 2020 19:15:54 +00:00  e1000_bia.txt
  270  -rw-        5608  Aug 27 2020 08:33:34 +00:00  -Aug-27-08-33-32.832-0
  271  -rw-        5636  Aug 27 2020 08:38:06 +00:00  -Aug-27-08-38-07.561-1
  272  -rw-        5643  Aug 27 2020 11:00:40 +00:00  archive-Aug-27-11-00-40.210-0
  273  -rw-        5339  Sep 23 2020 20:02:54 +00:00  archive-Sep-23-20-02-55.395-0
  274  -rw-        5517   Oct 2 2020 16:58:08 +00:00  archive-Oct--2-16-58-09.202-0
  275  -rw-        5104   Oct 2 2020 19:10:02 +00:00  archive-Oct--2-19-10-03.434-0
  276  -rw-        5083   Oct 4 2020 19:15:52 +00:00  archive-Oct--4-19-15-52.058-0

2142715904 bytes total (2029932544 bytes free)

**Comment by narayanankl** [comment]
@ktbyers , I have removed enable secret and provided normal enable password in as optional arguments. now it's picking up configuration from file using napalm.
Many thanks @ktbyers for your continues support.
