### ISSUE TITLE
License is missing 

### ISSUE THREAD

**Issue by resparis** [napalm-automation/napalm#1282]
Hi, Im trying to add it my company repository but I am getting the following error

[96mRejectReasons[0m (1)
[96mType:[0m      UNKNOWN_LICENSE_FOUND
          [96mLicense:[0m   UNKNOWN

Can you add one?

**Comment by ktbyers** [comment]
It is already there:

https://github.com/napalm-automation/napalm/blob/develop/LICENSE


Kirk

**Comment by resparis** [comment]
Do you think you can add it to pypi.org ? 

still getting the same error to imort it

**Comment by ktbyers** [comment]
Okay, I will update setup.py meta data.

Which tool are you using that is checking/verifying the license (for my information/learning)?

**Comment by ktbyers** [comment]
Also when you say you get an error on `importing it`--can you show me?

**Comment by resparis** [comment]
We are usign jfrog articatory.. 
Still having the same problem.

[96mMessage:[0m                     Artifact scanning found issues.  Upload aborted, see reject reasons.
[96mProgress:[0m                    [92m4[0m / [92m5[0m
[96mCreate Timestamp:[0m            2020-08-28 13:47:10 -0300 -03
[96mUpdate Timestamp:[0m            2020-08-28 13:51:59 -0300 -03
[96mArtifact:[0m                    PYPI - napalm==3.1.0
  [96mRejectReasons[0m (1)
    [96mRejectReason:[0m      fe83e95e-e75e-40ab-a7bb-8e2987702e80
      [96mType:[0m      UNKNOWN_LICENSE_FOUND
      [96mLicense:[0m   UNKNOWN

Not sure if I need to wait any refresh

**Comment by ktbyers** [comment]
Yes, you will have to wait until we deploy a new release to pypi. We are planning on doing that in the not too distant future (though that usually means on the order of x-days where x is less than ~7).

Note, NAPALM is licensed as Apache2 (which is clearly indicated in the repository using the standard filename for this).

**Comment by resparis** [comment]
oh cool. Thanks A lot for your help.
 
Just to let you know. I worked in a really big US company. WE have 5k branches. I did a multithread script to use netmiko to scp.
I have 2 linux servers, so I created 5 intances of the same script, each one of them with its own individual environment, using 50 threads each. So at the same time I was pushing the files to 500 devices. I knock them out in 4 days (push was done Out of the business hours).

**Comment by ktbyers** [comment]
@resparis Awesome :-)

Which vendor-platforms was that on (or most common platform anyways)? No worries if you can't respond.


Regards, Kirk

**Comment by resparis** [comment]
I can. For the line of business I am, we have an standard. 4431 for routers with 2 or 3 3650 switches.
something interesting was when I tried 150 theads at the same time, I got a lot of errors. My guess was hte ssh socket, but I did not have the time to do tshoot, that is the reason I split in "instances".

**Comment by ktbyers** [comment]
@resparis NAPALM 3.2.0 has been pushed to pypi with the updated License meta data. Can you test that your tooling passes now?
