### ISSUE TITLE
JunOS: Add Support for Logical Interfaces Counters

### ISSUE THREAD

**Issue by jtopjian** [napalm-automation/napalm#1293]
### Description of Issue/Question

I noticed that when calling `get_interfaces_counters` for JunOS, only the physical interface counters are returned and not the logical interfaces. Since logical interfaces are returned in a call to `get_interfaces`, I was wondering if it makes sense to also include logical interfaces when calling `get_interfaces_counters`. 

I did some testing and it's definitely possible to do, however at least in my environment, only the `rx_octets` and `tx_octets` have values. Still, they're values nonetheless and it would be nice to access them.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [ ] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==3.2.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
JunOS 17.3
```

**Comment by mirceaulinic** [comment]
Hi @jtopjian. I think it would make sense; historically, `get_interfaces` didn't return logical interfaces either, so I think it would be best to have them aligned. For anything else besides `rx_octets` and `tx_octets` you can default the other fields to -1.
