### ISSUE TITLE
nxos_ssh get_interfaces_counters prints data to stdout

### ISSUE THREAD

**Issue by jonathanghent** [napalm-automation/napalm#1303]
### Description of Issue/Question
The nxos_ssh get_interfaces_counters method prints all_stats_d before returning.  Other than that, it is working great.

https://github.com/napalm-automation/napalm/blob/7f107a9b9b74659cc43254e624992f6eebd1887e/napalm/nxos_ssh/nxos_ssh.py#L1723

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==3.2.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Any NXOS
```

### Steps to Reproduce the Issue
driver = napalm.get_network_driver('nxos_ssh')
device = driver(hostname,username,password)
device.get_interfaces_counters()

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
None
```

**Comment by mirceaulinic** [comment]
For this sort of issues, you can open a PR straight away @jonathanghent.

**Comment by jonathanghent** [comment]
See #1303
