### ISSUE TITLE
IOS-XR get_route_to empty outgoing interface

### ISSUE THREAD

**Issue by Tristou27** [napalm-automation/napalm#1310]
### Description of Issue/Question

In the IOSXRDriver, the method get_route_to does not check for the outgoingInterface, set by default to an empty string.
On IOS XR, there is a value in the XML output named InterfaceName, located under RoutePath/InterfaceName
```
<RoutePath>
    <Entry>
        <Address>0.0.0.0</Address>
        <InformationSource>0.0.0.0</InformationSource>
        <InterfaceName>GigabitEthernet0/1/1/2</InterfaceName>
(...)
    </Entry>
</RoutePath>
```

Would it be possible to complete this information ? I can open a PR to speed up the addition.

Rgds
Tristou27

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
(virtenv) {20-10-23 15:28}nietb4:~/Core-Tests-Automation ttr% pip freeze | grep napalm
napalm==3.2.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

All

### Steps to Reproduce the Issue
1 / Open a connection to a XR device
2 / Ask for a route in RIB (no matter the route)
3 / In the return dictionary, outgoing Interface is always empty.

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Original call was: <?xml version="1.0" encoding="UTF-8"?><Request MajorVersion="1" MinorVersion="0"><Get><Operational><RIB><VRFTable><VRF><Naming><VRFName>default</VRFName></Naming><AFTable><AF><Naming><AFName>IPv4</AFName></Naming><SAFTable><SAF><Naming><SAFName>Unicast</SAFName></Naming><IP_RIBRouteTable><IP_RIBRoute><Naming><RouteTableName>default</RouteTableName></Naming><RouteTable><Route><Naming><Address>172.18.0.35</Address></Naming></Route></RouteTable></IP_RIBRoute></IP_RIBRouteTable></SAF></SAFTable></AF></AFTable></VRF></VRFTable></RIB></Operational></Get></Request>
{'172.18.0.34/31': [{'current_active': True, 'last_active': False, 'age': 866539, 'next_hop': '0.0.0.0', 'protocol': 'connected', 'outgoing_interface': '', 'preference': 4, 'selected_next_hop': False, 'inactive_reason': '', 'routing_table': 'default', 'protocol_attributes': {}}]}
```

**Comment by mirceaulinic** [comment]
Hey @Tristou27 - yes, I think it would make sense to do that. It seems like there's an `InterfaceName` field under the `RoutePath` level, so if you'd be willing to PR that, it'd be very welcome! Cheers.

**Comment by Tristou27** [comment]
Hello @mirceaulinic 

Yes OK I'll try to push a PR in the coming days.

Rgds
Tristan

**Comment by Tristou27** [comment]
Done with #1421.

**Comment by Tristou27** [comment]
Merged.
