### ISSUE TITLE
Cisco IOS driver (placeholder)

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#133]
Just keeping track of some issues on new Cisco IOS driver:

1. Need support for inline config merge, config replace (i.e. not from an external file, but from inline in-code).
5. Unit testing is really slow.
8. Should automate the testing at the ansible level.
14. Update unittests to test that invalid commands in a replace config operation get rejected.
15. There is no diff for a merge operation.
19. Requirements.txt needs updated to required netmiko version.
20. What is required to make SCP and TACACS+ work.

~~Don't have any 'write mem' operation.   Fixed~~
~~IOS test I have hard-coded the 'flash:'       Fixed~~
~~Need to test non-standard SSH port.           Fixed using optional_args~~
~~Need to change order of configuration diff (so + and - sign so up appropriate way). Will need to update the unit test to reflect this also.                         Fixed~~
~~Should null out the merge_config file on discard operations.    Fixed~~
~~Should really check 'file prompt quiet' initial state and restore to original state (as opposed to just blindly toggling).        Did not do~~
~~Need to test using Ansible.~~
~~Timeout not wired in.   Did not do~~
~~Is there a better way to implement the rollback function that more directly ties into the configuration archive.     Did not do~~
~~Do you need 'archive' configured for any of this to work. Need to test on a new device. DBarroso stated silently failed without this.   Yes, archive is required~~
~~Netmiko version will need to be the current version (need to push new Netmiko version to pypi).~~
~~DBarroso stated silently failed without version xx.y on CSR1000v~~
~~Test on Py3 (can't do because ncclient and consequently pyez have no py3 support)~~
~~Need to document 'ip scp server enable'~~

**Comment by ppieprzycki** [comment]
Hi, 
There seems to be problem on some Cisco switches because they have different names for flash (and this is not consistent). 

I've just checked:
Device flash exist:
Cisco Catalyst 2960,3650, 3560 

Cisco 6500:
we have devices
sup-bootflash (where keeps iOS image)
bootflash (keeps crashes)

Cisco 4948/4900M
cat4000_flash (keeps only plan.dat 516k)
bootflash (here stores iOS image) 


Do you see any possibility to implement before copying function that will check flash device name according to the device version ?

**Comment by ktbyers** [comment]
@ppieprzycki 

New code (see pull request #134) should allow you specify the destination filesystem. I have the code here on this branch if you want to test (https://github.com/ktbyers/napalm/tree/cisco_ios_scp). 

You can see this unit test code for some details on how to call/use it (https://github.com/ktbyers/napalm/blob/cisco_ios_scp/test/unit/TestIOSDriver.py)

**Comment by ktbyers** [comment]
Timestamps on slow file operations:

>>>Replace config
check1: 2016-01-27 09:20:23.867486
check2: 2016-01-27 09:20:50.893301
check3: 2016-01-27 09:21:10.421605
check4: 2016-01-27 09:21:10.669322
check5: 2016-01-27 09:21:34.693989 (this is just before the method return)

**Comment by dbarrosop** [comment]
NAPALM 0.51 has been released with all your improvements. Should be close this task?

**Comment by ktbyers** [comment]
No please keep this one open. This was how I was keeping track of various issues that I encountered.

**Comment by dbarrosop** [comment]
Should we close this? How do you feel about it in general?

**Comment by ktbyers** [comment]
Let me review it and move any open items to the cisco ios NAPALM repository.



Kirk

On Thu, Apr 21, 2016 at 3:10 AM, David Barroso <notifications@github.com>
wrote:

> Should we close this? How do you feel about it in general?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/napalm-automation/napalm/issues/133#issuecomment-212842729>
>



-- 
Kirk Byers
CCIE #6243 emeritus
ktbyers@twb-tech.com
*http://pynet.twb-tech.com <http://pynet.twb-tech.com/blog>*
(415) 264-6270
Simplify your network management through automation
