### ISSUE TITLE
Feature request. Getters as generators

### ISSUE THREAD

**Issue by luqasz** [napalm-automation/napalm#1339]
Hi

I am maintaining `napalm-ros` (routeros / MikroTik driver) for `napalm`. My proposition is to use `yield` instead of returning whole dict / list etc. This only applies to getters which can return more than one result e.g. `get_users`. This will reduce memory usage since some drivers may already use generators under the hood.

What do you think ?

**Comment by mirceaulinic** [comment]
I see where you're coming from, and I do agree this would be better in some particular scenarios, for example, when calling NAPALM from a script. I'm afraid this would break functionality with various framework integrations. Of course, this would also require for all the drivers to be updated, so it'd be an API change. I'm not closing this though, let's see what other people think.

**Comment by luqasz** [comment]
Yes it will break backwards compatibility. However it will:
* reduce memory usage
* simplify things as generators will yield always same type 
* require new function calls

**Comment by mirceaulinic** [comment]
I believe this isn't something we'll support in the core NAPALM.

**Comment by luqasz** [comment]
> I believe this isn't something we'll support in the core NAPALM.

Which part ?

**Comment by mirceaulinic** [comment]
> Which part ?

`Getters as generators`
