### ISSUE TITLE
get_lldp_neighbors_detail with specified interface return type

### ISSUE THREAD

**Issue by luqasz** [napalm-automation/napalm#1340]
Hi

What type should `get_lldp_neighbors_detail()` return when `interface` is passed ? I couldn't find any information in `base.py` or tests. Should it return a dict with interface as key and all  its neighbors OR list with all neighbors ?

**Comment by mirceaulinic** [comment]
Hi @luqasz. It should return a dictionary with the interface as key. Let me know if you have any questions.
