### ISSUE TITLE
IOS-XR NETCONF driver returns empty running-config, candidate-config, and startup-config

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#1348]
Cisco IOS-XR version:

```
Cisco IOS XR Software, Version 6.5.3
Copyright (c) 2013-2019 by Cisco Systems, Inc.
```

Relevant test code:

```python
#!/usr/bin/env python

from getpass import getpass
from pprint import pprint as pp
from napalm import get_network_driver

device = {
    "hostname": "iosxr3.lasthop.io",
    "username": "pyclass",
    "password": getpass(),
}

driver = get_network_driver("iosxr_netconf")
device = driver(**device)
device.open()

print()
print(">>>Test get_config()")
output = device.get_config()
pp(output)
```

```
$ python iosxr_get_conf.py 
Password: 

>>>Test get_config()
{'candidate': '', 'running': '', 'startup': ''}
```

**Comment by ktbyers** [comment]
CC: @neelimapp

**Comment by neelimapp** [comment]
Could you please try with optional_args, setting config_encoding to xml?

**Comment by ktbyers** [comment]
Okay, yuck on the 6.7.1 support...

that is really going to limit support of this (as we are going to have to state support of 6.7.1 as I view `get_config` in CLI format as pretty fundamental to the entire driver).

And now I can't test it as my test device is 6.5.3. I will have to figure out a way to get a newer virtual device.

XML encoding works fine.

**Comment by neelimapp** [comment]
Yes, we have added the current limitations of this driver in the documentation. 
https://github.com/napalm-automation/napalm/pull/1314#issuecomment-719737760

**Comment by ktbyers** [comment]
Yeah, we will probably need to roll that to 6.7.1 in the documentation as CLI format for config is pretty fundamental to reasonable operation for the driver.

**Comment by neelimapp** [comment]
Okay.
CC: @111pontes

**Comment by ktbyers** [comment]
Closing as this is the expected behavior for this OS version.
