### ISSUE TITLE
Cisco IOS: can 'configure replace' be made to support automatic rollback for invalid config

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#135]
Original comment from @dbarrosop:

>
You mention that "'configure replace' will accept the config with a typo command, but will just reject the relevant command". IMHO I think it would be better to detect that there was some issue and rollback automatically. That's what FortiOS does and it's one of the premises of napalm, that all intended changes are applied or none. What do you think?
>

**Comment by ktbyers** [comment]
Notes, on behavior:

Working:
<pre>
#configure replace flash:rollback_config.txt force
Total number of passes: 1
Rollback Done

</pre>

Failed (invalid configuration command in the config):
<pre>
#configure replace flash:candidate_config.txt force 
The rollback configlet from the last pass is listed below:
********
!List of Rollback Commands:
adfjasdfadfa
end
********


Rollback aborted after 5 passes
The following commands are failed to apply to the IOS image.
********
adfjasdfadfa
********


</pre>

**Comment by ktbyers** [comment]
Behavior when doing automatic rollback at IOS level.

<pre>
#configure replace flash:candidate_config.txt force revert trigger error 
Failed to apply command adfjasdfadfa
Aborting Rollback.

Rollback failed.Reverting back to the original configuration: flash:pynet-rtr1-cfgJan--6-12-49-44.412-PST-0 ...

Total number of passes: 1
Rollback Done

The original configuration has been successfully restored.

pynet-rtr1#show run | inc logging
logging buffered 10000
no logging console
</pre>

So it did rollback the change to the original config.

**Comment by ktbyers** [comment]
Here is what 'revert trigger error' looks like when it works:

<pre>
#configure replace flash:rollback_config.txt force revert trigger error 
Total number of passes: 1
Rollback Done

</pre>

**Comment by dbarrosop** [comment]
So revert trigger error seems the way to go, right?

**Comment by ktbyers** [comment]
@dbarrosop Yes it looks like it would probably work:

Key issues:
1. Does IOS give you many false positives.
2. Related to item 1, the 'crypto pki certificate chain TP-self-signed-' frequently generates an error. I believe this is due to the 'quit' line at the end which consists of '  \tquit\n' (i.e. two spaces and then a tab) so when you copy this manually the tab gets converted to a space.
3. Do you need 'archive' configured-enabled for this to work (will need to test).

**Comment by dbarrosop** [comment]
Just one comment, any prerequisites to make this work is just a matter to document them. So don't bother that much if the archive feature has to be enabled, if there is a reason for that people should do it. Dealing with IOS is already complex enough to not use that feature if it's available : )

**Comment by ktbyers** [comment]
Okay, I added support for this.

https://github.com/ktbyers/napalm/commit/e5208220204a2ef41a320d16577320e5bd50bdd0

I added an optional_arg named 'auto_rollback_on_error' that defaults to True. This will allow people to choose to ignore errors if necessary.

This is needed as Cisco IOS can have issues with the self-signed certificate and 'revert trigger error' wasn't added in IOS until 12.4(20)T.
I need to update the IOS unit tests to test this.

**Comment by dbench** [comment]
@ktbyers Hi Kirk. Do you know if the issue with the quit command within the self-signed cert ever get resolved, or is there a workaround?  I am having issues with ansible-napalm applying a Jinja2 template.  When attempting the "configure replace" command manually for cli, I get the below error.  Any guidance you can provide on this?

blah#configure replace flash:candidate_config.txt force revert trigger error
Failed to apply command   no    quit
Aborting Rollback.

Rollback failed.Reverting back to the original configuration: flash:archive-Sep--3-15-07-57.543-11 ..

**Comment by ktbyers** [comment]
@dbench Yep, looks like your configuration file (particularly your SSL certificate) is not valid (as per our other discussion in the separate GitHub thread).

Regards, Kirk
