### ISSUE TITLE
Traceroute response empty for IOS

### ISSUE THREAD

**Issue by miroistona** [napalm-automation/napalm#1354]
### Description of Issue/Question
Traceroute on IOS is not working - I receive only an empty 'success' dictionary: {'success': {}}

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [X] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm                3.2.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Cisco IOS Software, ME360x Software (ME360x-UNIVERSALK9-M), Version 15.4(3)S10,
```

### Steps to Reproduce the Issue
traceroute works on CLI but not via NAPALM - where I receive following output:
$ python traces.py
connecting..
connected
{'success': {}}

Code snippet:
        print(f"connecting..")
        device.open()
        print(f"connected ")
        trace = device.traceroute(ip, vrf='blue')
        print(trace)
        device.close()

CLI: #traceroute vrf blue 8.8.8.8

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
no exception is thrown, only the traceroute reply is empty and I see no hops
```

**Comment by mirceaulinic** [comment]
Can you share your exact script @miroistona, this information is not enough to understand what you're doing exactly.

**Comment by miroistona** [comment]
Code below - changed IPs & credentials & vrf name only. output I get:
connecting..
connected
{'success': {}}

`import napalm

if __name__ == "__main__":
    driver = napalm.get_network_driver('ios')

    device = driver(
        hostname="1.1.1.1",
        username="cisco",
        password="cisco",
    )
    try:       
        print(f"connecting..")
        device.open()
        print(f"connected ")
        trace = device.traceroute("2.2.2.2", vrf='vrf_name')
        print(trace)
        device.close()
    except:
        print("FAIL: Either can't connect to or traces errored- msg:", sys.exc_info()[0]) `

**Comment by mirceaulinic** [comment]
Could you also share what this code does? And please remove the try-except block.

**Comment by miroistona** [comment]
`import napalm

def napalm_trace_test(ip):
    driver = napalm.get_network_driver('ios')

    device = driver(
        hostname="1.2.3.4",
        username="username",
        password="ciscopw123",
    )
    print(f"connecting..")
    device.open()
    print(f"connected ")
    trace = device.traceroute(ip, vrf='ACME')
    print(trace)
    device.close()

if __name__ == "__main__":
    napalm_trace_test("9.9.9.9")`

this is equivalent to cli command on cisco:
#traceroute vrf ACME 9.9.9.9

**Comment by mirceaulinic** [comment]
@miroistona and what is the exact output when you run this? And go to https://guides.github.com/features/mastering-markdown/ and see how you should properly formatting.

**Comment by miroistona** [comment]
the output I get is:
```python
$ python traces.py
connecting..
connected
{'success': {}}
```
per napalm specification key 'success' should contain dict with hops - I do not see them in the response. when I try this on CLI - trace works fine. I tried this on both Cisco IOSXE and Juniper Junos

**Comment by mirceaulinic** [comment]
And the output from your device when you run that command on the CLI?

**Comment by miroistona** [comment]
router#traceroute vrf ACME 9.9.9.9
Type escape sequence to abort.
Tracing the route to 9.9.9.9
VRF info: (vrf in name/id, vrf out name/id)
  1 9.9.9.9 [AS 65016] 0 msec *  0 msec
