### ISSUE TITLE
question - junos vlan support

### ISSUE THREAD

**Issue by ckozler** [napalm-automation/napalm#1366]
Hi there -

I see in the support matrix table that vlan information for junos is not supported

I've actually begun implementing it on my own and was wondering if there was any particular reason napalm does not support it out of the box? Was that table/view not available when junos support was originally added to napalm or is there a reason you chose not to from a technical standpoint?

i.e you've done it but something is broken and cant be fixed so the feature doesnt make sense

I'd rather not waste any more time if you know something I don't about juniper vlan table support

**Comment by mirceaulinic** [comment]
Hi @ckozler. I think it was just not implemented, I don't think there is anything wrong with the juniper vlan table. Feel free to open a PR to add it if you wish, cheers!

**Comment by ckozler** [comment]
Thanks, working on it now! Just wanted to make sure there wasn't some specific reason why you had not implemented it
