### ISSUE TITLE
Support for EOS Commands in "EOS_Ver >= 4.23"

### ISSUE THREAD

**Issue by mfatty** [napalm-automation/napalm#1392]
### Description of Issue/Question
There is a bunch of changes that went into EOS => 4.23 as the settlement with Cisco vs Arista lawsuit. I ran into an issue with the command "show ipv6 bgp neighbors vrf all" because it's no longer supported in newer EOS versions. It has been changed to "show ipv6 bgp peers vrf all". A lot of other commands have changed. 

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==2.3.2
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Arista DCS-7050CX3M-32S-F
Hardware version:      10.01
Serial number:         JPE19290617
Hardware MAC address:  fcbd.675d.2831
System MAC address:    fcbd.675d.2831

Software image version: 4.24.2F-DPE
Architecture:           i686
Internal build version: 4.24.2F-DPE-18436385.4242F
Internal build ID:      16c1a81c-d289-4458-a544-573036ff9553

Uptime:                 0 weeks, 0 days, 2 hours and 31 minutes
Total memory:           8160640 kB
Free memory:            6547648 kB

```

### Steps to Reproduce the Issue
Configure Arista switch with EOS version 4.23 or above. I'm using 4.24.2F-DPE.
Configure BGP for ipv4 or ipv6 - this might not even be required because the show command fails regardless. 
Connect to the Arista switch vi eAPI and run execute method "get_bgp_neighbors()" against device. 
Essentially, this command tries to get all BGP neighbors on the device, ipv4 and ipv6. However, ipv6 show command fails because EOS has changed the syntax. Instead of "show ipv6 bgp neighbors vrf all", it is "show ipv6 bgp peers vrf all". This is not the only change. There is a bunch of changes that went into 4.23 and above as the settlement with Cisco vs Arista lawsuit. 

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
>>> dut.get_bgp_neighbors()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mfatty/.pyenv/versions/casc-env.3.6.11/lib/python3.6/site-packages/olympus_nqa/Device.py", line 520, in get_bgp_neighbors
    return executor()
  File "/home/mfatty/.pyenv/versions/casc-env.3.6.11/lib/python3.6/site-packages/olympus_nqa/Device.py", line 169, in _run
    return getattr(self.device, method)(*args, **kwargs)
  File "/home/mfatty/.pyenv/versions/casc-env.3.6.11/lib/python3.6/site-packages/napalm/eos/eos.py", line 400, in get_bgp_neighbors
    ['show ip ' + NEIGHBOR_FILTER, 'show ipv6 ' + NEIGHBOR_FILTER_v6],
  File "/home/mfatty/.pyenv/versions/casc-env.3.6.11/lib/python3.6/site-packages/pyeapi/client.py", line 730, in run_commands
    response = self._connection.execute(commands, encoding, **kwargs)
  File "/home/mfatty/.pyenv/versions/casc-env.3.6.11/lib/python3.6/site-packages/pyeapi/eapilib.py", line 499, in execute
    response = self.send(request)
  File "/home/mfatty/.pyenv/versions/casc-env.3.6.11/lib/python3.6/site-packages/pyeapi/eapilib.py", line 418, in send
    raise CommandError(code, msg, command_error=err, output=out)
pyeapi.eapilib.CommandError: Error [1002]: CLI command 3 of 3 'show ipv6 bgp neighbors vrf all | include remote AS | remote router ID |IPv[46] Unicast:.*[0-9]+|^Local AS|Desc|BGP state' failed: invalid command [Invalid input (at token 3: 'neighbors')]
>>> 
```

**Comment by mirceaulinic** [comment]
Hi @mfatty, have you tried to enable the `eos_fn0039_config` optional argument (see https://napalm.readthedocs.io/en/latest/support/index.html#list-of-supported-optional-arguments)?

**Comment by mirceaulinic** [comment]
Closing; @mfatty feel free to reopen or comment if you the issue persists.
