### ISSUE TITLE
NAPALM and Cisco IOS in GNS3 fails on save_config() due to prompting of a new OS version

### ISSUE THREAD

**Issue by FSociety07** [napalm-automation/napalm#1413]
### Description of Issue/Question
I am able to connect to the Cisco 7200 Router using Napalm. Can run get_facts without any issues.
When running the below script, getting error "**OSError: Search pattern never detected in send_command: R4\#** " where R4 is the Router's hostname.
Added the optional_argument "'**global_delay_factor':5**" as per kirk's advice from other similar threads. But, please note, other errors were not about **send_command**, they were about **send_command_expect**.
1st-time poster, advanced apologies for formatting mistakes. 
Please help

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### Setup
GNS3 version 2.2.19
Ubuntu version 18.04
Python version 3.8.3

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==3.2.0

```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Cisco IOS Software, 7200 Software (C7200-ADVIPSERVICESK9-M), Version 15.0(1)M, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2009 by Cisco Systems, Inc.
Compiled Wed 30-Sep-09 07:48 by prod_rel_team

ROM: ROMMON Emulation Microcode
BOOTLDR: 7200 Software (C7200-ADVIPSERVICESK9-M), Version 15.0(1)M, RELEASE SOFTWARE (fc2)

R4 uptime is 14 minutes
System returned to ROM by unknown reload cause - suspect boot_data[BOOT_COUNT] 0x0, BOOT_COUNT 0, BOOTDATA 19
System image file is "tftp://255.255.255.255/unknown"


This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

Cisco 7206VXR (NPE400) processor (revision A) with 491520K/32768K bytes of memory.
Processor board ID 4279256517
R7000 CPU at 150MHz, Implementation 39, Rev 2.1, 256KB L2 Cache
6 slot VXR midplane, Version 2.1

Last reset from power-on

PCI bus mb0_mb1 (Slots 0, 1, 3 and 5) has a capacity of 600 bandwidth points.
Current configuration on bus mb0_mb1 has a total of 200 bandwidth points.
This configuration is within the PCI bus capacity and is supported.

PCI bus mb2 (Slots 2, 4, 6) has a capacity of 600 bandwidth points.
Current configuration on bus mb2 has a total of 0 bandwidth points
This configuration is within the PCI bus capacity and is supported.

Please refer to the following document "Cisco 7200 Series Port Adaptor
Hardware Configuration Guidelines" on Cisco.com <http://www.cisco.com>
for c7200 bandwidth points oversubscription and usage guidelines.


1 FastEthernet interface
509K bytes of NVRAM.

8192K bytes of Flash internal SIMM (Sector size 256K).


Configuration register is 0x2102

```

### Steps to Reproduce the Issue
import json
from napalm import get_network_driver
driver = get_network_driver('ios')
opt_arg = {'dest_file_system':'nvram:','global_delay_factor':5}
iosvl2 = driver('192.168.122.254', 'sawn', 'sawn',optional_args=opt_arg)
iosvl2.open()

print('doing acl')
iosvl2.load_merge_candidate(filename='ACL1.cfg')
iosvl2.commit_config()
iosvl2.close()

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```

Traceback (most recent call last):
  File "acl.py", line 11, in <module>
    iosvl2.commit_config()
  File "/usr/local/lib/python3.8/dist-packages/napalm/ios/ios.py", line 556, in commit_config
    output += self.device.save_config()
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco/cisco_ios.py", line 36, in save_config
    return super().save_config(
  File "/usr/local/lib/python3.8/dist-packages/netmiko/cisco_base_connection.py", line 246, in save_config
    output = self.send_command(
  File "/usr/local/lib/python3.8/dist-packages/netmiko/utilities.py", line 430, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1529, in send_command
    raise IOError(
OSError: Search pattern never detected in send_command: R4\#

```

ACL1.cfg file contains below lines
'''
access-list 130 permit icmp any any
access-list 131 permit icmp any any
end

'''

**Comment by ggiesen** [comment]
I'm having the same issue with many Cisco Catalyst 6500s running 12.2(33)SXJ10:

```
$ cat test.tmpl 
hostname router-name
```

```
$ bin/napalm --user user --vendor ios --optional_args "dest_file_system='sup-bootdisk:'" router-name.example.com configure test.tmpl --strategy merge --dry-run
Enter password: 
2021-03-29 15:18:38,338 - napalm - ERROR - load_merge_candidate - Failed: Search pattern never detected in send_command: router\-name\#

================= Traceback =================

Traceback (most recent call last):
  File "bin/napalm", line 8, in <module>
    sys.exit(main())
  File "/home/user/temp/napalm/lib64/python3.7/site-packages/napalm/base/clitools/cl_napalm.py", line 308, in main
    run_tests(args)
  File "/home/user/temp/napalm/lib64/python3.7/site-packages/napalm/base/clitools/cl_napalm.py", line 293, in run_tests
    configuration_change(device, args.config_file, args.strategy, args.dry_run)
  File "/home/user/temp/napalm/lib64/python3.7/site-packages/napalm/base/clitools/cl_napalm.py", line 239, in configuration_change
    strategy_method(device, filename=config_file)
  File "/home/user/temp/napalm/lib64/python3.7/site-packages/napalm/base/clitools/cl_napalm.py", line 27, in wrapper
    r = func(*args, **kwargs)
  File "/home/user/temp/napalm/lib64/python3.7/site-packages/napalm/base/clitools/cl_napalm.py", line 217, in call_load_merge_candidate
    return device.load_merge_candidate(*args, **kwargs)
  File "/home/user/temp/napalm/lib64/python3.7/site-packages/napalm/ios/ios.py", line 320, in load_merge_candidate
    file_system=self.dest_file_system,
  File "/home/user/temp/napalm/lib64/python3.7/site-packages/napalm/ios/ios.py", line 286, in _load_candidate_wrapper
    file_system=file_system,
  File "/home/user/temp/napalm/lib64/python3.7/site-packages/napalm/ios/ios.py", line 625, in _scp_file
    TransferClass=FileTransfer,
  File "/home/user/temp/napalm/lib64/python3.7/site-packages/napalm/ios/ios.py", line 684, in _xfer_file
    output = self.device.send_command_expect(show_cmd)
  File "/home/user/temp/napalm/lib64/python3.7/site-packages/netmiko/base_connection.py", line 1576, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/home/user/temp/napalm/lib64/python3.7/site-packages/netmiko/utilities.py", line 430, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/home/user/temp/napalm/lib64/python3.7/site-packages/netmiko/base_connection.py", line 1531, in send_command
    search_pattern
OSError: Search pattern never detected in send_command: router\-name\#
```

I've tried many variations on the configuration file, without empty line at the end, with empty line at the end, with ! at the end. Make no difference.

**Comment by ktbyers** [comment]
You probably need to look at the Netmiko logging or the Netmiko session log to provide more details on what is happening (Netmiko is being used under the hood here).


Regards, Kirk

**Comment by ggiesen** [comment]
How do I go about enabling that logging? I don't see an `optional_args` for that

**Comment by ktbyers** [comment]
@ggiesen https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by ggiesen** [comment]
I managed to get it working using the CLI (and found out you can't have spaces between optional_args)

```
$ cat test.tmpl 
ip domain-name example.com
```

```
$ bin/napalm --user user --vendor ios --optional_args "dest_file_system='sup-bootdisk:',global_delay_factor=30,session_log='/tmp/netmiko.log',session_log_record_writes=True" router-name.example.com configure test.tmpl --strategy merge --dry-run
Enter password: 

```

```
$ tail -f /tmp/netmiko.log 
router-name#terminal width 511
router-name#terminal length 0 
terminal length 0
router-name#

router-name#

router-name#

router-name#dir sup-bootdisk:/merge_config.txt
dir sup-bootdisk:/merge_config.txt
%Error opening sup-bootdisk:/merge_config.txt (File not found)
router-name#

router-name#dir sup-bootdisk:
dir sup-bootdisk:
Directory of sup-bootdisk:/

    1  -rw-    26843548  Nov 14 2018 16:09:58 -05:00  sea_log.dat
    2  -rw-    71736676  Nov 14 2018 16:12:42 -05:00  s3223-advipservicesk9_wan-mz.122-33.SXJ10.bin
    3  -rw-    26843548  Nov 14 2018 16:10:56 -05:00  sea_console.dat
    4  -rw-      106480  Mar 26 2021 14:46:22 -04:00  archive-Mar-26-14-46-21-EST-0
    5  -rw-      106491  Mar 26 2021 14:59:28 -04:00  archive-Mar-26-14-59-28-EST-1
    6  -rw-      106897  Mar 27 2021 15:09:54 -04:00  archive-Mar-27-15-09-53-EST-2
    7  -rw-      106507  Mar 27 2021 21:00:50 -04:00  archive-Mar-27-21-00-51-EST-3
    8  -rw-      106100  Mar 27 2021 23:29:36 -04:00  archive-Mar-27-23-29-37-EST-4
    9  -rw-      106121  Mar 29 2021 03:16:12 -04:00  archive-Mar-29-03-16-12-EST-5

256503808 bytes total (130428928 bytes free)
router-name#

router-name#show running-config | inc ip scp server enable
show running-config | inc ip scp server enable
ip scp server enable
router-name#

router-name#verify /md5 sup-bootdisk:/merge_config.txt
verify /md5 sup-bootdisk:/merge_config.txt
.Done!
verify /md5 (sup-bootdisk:/merge_config.txt) = 4b48395cd63665ebe84ef1ebb44b6218


router-name#

router-name#show archive config incremental-diffs sup-bootdisk:/merge_config.txt ignorecase
show archive config incremental-diffs sup-bootdisk:/merge_config.txt ignorecase
!List of Commands:
end
!No changes were found

router-name#

router-name#exit
```

At first I thought it was enabling logging that had "fixed" it, but it ended up actually being global_delay_factor (It's tested good through the CLI at 2 so I set it to 4 to give some headroom). Will now test in my actual application (Salt) to see if it resolves the issue.

**Comment by FSociety07** [comment]
'''
DEBUG:paramiko.transport:starting thread (client mode): 0x85c16970
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-1.99-Cisco-1.25
INFO:paramiko.transport:Connected (version 1.99, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-cbc', '3des-cbc', 'aes192-cbc', 'aes256-cbc'] server encrypt:['aes128-cbc', '3des-cbc', 'aes192-cbc', 'aes256-cbc'] client mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] server mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:Got server p (2048 bits)
DEBUG:paramiko.transport:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 192.168.122.254: b'cbb39c34f03a240ddb6da9bf49ecb01d'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
DEBUG:paramiko.transport:Secsh channel 0 opened.
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
DEBUG:netmiko:write_channel: b'terminal width 511\n'
DEBUG:netmiko:Pattern is: terminal width 511
DEBUG:netmiko:_read_channel_expect read_data:
R4#
DEBUG:netmiko:_read_channel_expect read_data: terminal width 511
R4#
DEBUG:netmiko:Pattern found: terminal width 511
R4#terminal width 511
R4#
DEBUG:netmiko:In disable_paging
DEBUG:netmiko:Command: terminal length 0

DEBUG:netmiko:write_channel: b'terminal length 0\n'
DEBUG:netmiko:Pattern is: terminal\ length\ 0
DEBUG:netmiko:_read_channel_expect read_data: t
DEBUG:netmiko:_read_channel_expect read_data: erminal length 0
R4#
DEBUG:netmiko:Pattern found: terminal\ length\ 0 terminal length 0
R4#
DEBUG:netmiko:terminal length 0
R4#
DEBUG:netmiko:Exiting disable_paging
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:[find_prompt()]: prompt is R4#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: R4
DEBUG:netmiko:_read_channel_expect read_data:

DEBUG:netmiko:_read_channel_expect read_data: R4#
DEBUG:netmiko:Pattern found: R4
R4#
DEBUG:paramiko.transport:starting thread (client mode): 0x85c805e0
DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_2.7.2
DEBUG:paramiko.transport:Remote version/idstring: SSH-1.99-Cisco-1.25
INFO:paramiko.transport:Connected (version 1.99, client Cisco-1.25)
DEBUG:paramiko.transport:kex algos:['diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa'] client encrypt:['aes128-cbc', '3des-cbc', 'aes192-cbc', 'aes256-cbc'] server encrypt:['aes128-cbc', '3des-cbc', 'aes192-cbc', 'aes256-cbc'] client mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] server mac:['hmac-sha1', 'hmac-sha1-96', 'hmac-md5', 'hmac-md5-96'] client compress:['none'] server compress:['none'] client lang:[''] server lang:[''] kex follows?False
DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group-exchange-sha1
DEBUG:paramiko.transport:HostKey agreed: ssh-rsa
DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
DEBUG:paramiko.transport:MAC agreed: hmac-sha1
DEBUG:paramiko.transport:Compression agreed: none
DEBUG:paramiko.transport:Got server p (2048 bits)
DEBUG:paramiko.transport:kex engine KexGex specified hash_algo <built-in function openssl_sha1>
DEBUG:paramiko.transport:Switch to new keys ...
DEBUG:paramiko.transport:Adding ssh-rsa host key for 192.168.122.254: b'cbb39c34f03a240ddb6da9bf49ecb01d'
DEBUG:paramiko.transport:userauth is OK
INFO:paramiko.transport:Authentication (password) successful!
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:[find_prompt()]: prompt is R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'dir nvram:/merge_config.txt\n'
DEBUG:netmiko:Pattern is: dir\ nvram:/merge_config\.txt
DEBUG:netmiko:_read_channel_expect read_data: d
DEBUG:netmiko:_read_channel_expect read_data: ir nvram:/merge_config.txt
Directory of nvram:/merge_config.txt

    2  -rw-          76                    <no date>  merge_config.txt

522232 bytes total (519728 bytes free)
R4#
DEBUG:netmiko:Pattern found: dir\ nvram:/merge_config\.txt dir nvram:/merge_config.txt
Directory of nvram:/merge_config.txt

    2  -rw-          76                    <no date>  merge_config.txt

522232 bytes total (519728 bytes free)
R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:[find_prompt()]: prompt is R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'verify /md5 nvram:/merge_config.txt\n'
DEBUG:netmiko:Pattern is: verify\ /md5\ nvram:/merge_config\.txt
DEBUG:netmiko:_read_channel_expect read_data: v
DEBUG:netmiko:_read_channel_expect read_data: erify /md5 nvram:/merge_config.txt
.Done!
verify /md5 (nvram:/merge_config.txt) = a4195a04c195a88051eb29e8ca103ec8


R4#
DEBUG:netmiko:Pattern found: verify\ /md5\ nvram:/merge_config\.txt verify /md5 nvram:/merge_config.txt
.Done!
verify /md5 (nvram:/merge_config.txt) = a4195a04c195a88051eb29e8ca103ec8


R4#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: #
DEBUG:netmiko:_read_channel_expect read_data:

DEBUG:paramiko.transport:EOF in transport thread
DEBUG:netmiko:_read_channel_expect read_data: R4#
DEBUG:netmiko:Pattern found: #
R4#
DEBUG:netmiko:write_channel: b'configure terminal\n'
DEBUG:netmiko:Pattern is: configure\ terminal
DEBUG:netmiko:_read_channel_expect read_data: c
DEBUG:netmiko:_read_channel_expect read_data: onfigure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
R4(config)#
DEBUG:netmiko:Pattern found: configure\ terminal configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
R4(config)#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: #
DEBUG:netmiko:_read_channel_expect read_data:

DEBUG:netmiko:_read_channel_expect read_data: R4(config)#
DEBUG:netmiko:Pattern found: #
R4(config)#
DEBUG:netmiko:write_channel: b'file prompt quiet\n'
DEBUG:netmiko:Pattern is: file\ prompt\ quiet
DEBUG:netmiko:_read_channel_expect read_data: f
DEBUG:netmiko:_read_channel_expect read_data: ile prompt quiet
R4(config)#
DEBUG:netmiko:Pattern found: file\ prompt\ quiet file prompt quiet
R4(config)#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: #
DEBUG:netmiko:_read_channel_expect read_data:

DEBUG:netmiko:_read_channel_expect read_data: R4(config)#
DEBUG:netmiko:Pattern found: #
R4(config)#
DEBUG:netmiko:write_channel: b'end\n'
DEBUG:netmiko:Pattern is: end
DEBUG:netmiko:_read_channel_expect read_data: e
DEBUG:netmiko:_read_channel_expect read_data: nd
R4#
DEBUG:netmiko:Pattern found: end end
R4#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: #
DEBUG:netmiko:_read_channel_expect read_data:

DEBUG:netmiko:_read_channel_expect read_data: R4#
DEBUG:netmiko:Pattern found: #
R4#
DEBUG:netmiko:exit_config_mode: end
R4#
DEBUG:netmiko:configure terminal
Enter configuration commands, one per line.  End with CNTL/Z.
R4(config)#file prompt quiet
R4(config)#end
R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:[find_prompt()]: prompt is R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'copy running-config nvram:/rollback_config.txt\n'
DEBUG:netmiko:Pattern is: copy\ running\-config\ nvram:/rollback_config\.txt
DEBUG:netmiko:_read_channel_expect read_data: c
DEBUG:netmiko:_read_channel_expect read_data: opy running-config nvram:/rollback_config.txt
%Error copying nvram:/rollback_config.txt (Invalid argument)
R4#
DEBUG:netmiko:Pattern found: copy\ running\-config\ nvram:/rollback_config\.txt copy running-config nvram:/rollback_config.txt
%Error copying nvram:/rollback_config.txt (Invalid argument)
R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:[find_prompt()]: prompt is R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'dir nvram:/merge_config.txt\n'
DEBUG:netmiko:Pattern is: dir\ nvram:/merge_config\.txt
DEBUG:netmiko:_read_channel_expect read_data: d
DEBUG:netmiko:_read_channel_expect read_data: ir nvram:/merge_config.txt
Directory of nvram:/merge_config.txt

    2  -rw-          76                    <no date>  merge_config.txt

522232 bytes total (519728 bytes free)
R4#
DEBUG:netmiko:Pattern found: dir\ nvram:/merge_config\.txt dir nvram:/merge_config.txt
Directory of nvram:/merge_config.txt

    2  -rw-          76                    <no date>  merge_config.txt

522232 bytes total (519728 bytes free)
R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:[find_prompt()]: prompt is R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'copy nvram:/merge_config.txt running-config\n'
DEBUG:netmiko:Pattern is: copy\ nvram:/merge_config\.txt\ running\-config
DEBUG:netmiko:_read_channel_expect read_data: c
DEBUG:netmiko:_read_channel_expect read_data: opy nvram:/merge_config.txt running-config

76 bytes copied in 0.012 secs (6333 bytes/sec)

R4#
DEBUG:netmiko:Pattern found: copy\ nvram:/merge_config\.txt\ running\-config copy nvram:/merge_config.txt running-config

76 bytes copied in 0.012 secs (6333 bytes/sec)

R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:[find_prompt()]: prompt is R4#
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:Pattern is: R4
DEBUG:netmiko:_read_channel_expect read_data:

DEBUG:netmiko:_read_channel_expect read_data: R4#
DEBUG:netmiko:Pattern found: R4
R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'\n'
DEBUG:netmiko:read_channel:
R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:[find_prompt()]: prompt is R4#
DEBUG:netmiko:read_channel:
DEBUG:netmiko:write_channel: b'write mem\n'
DEBUG:netmiko:Pattern is: write\ mem
DEBUG:netmiko:_read_channel_expect read_data: w
DEBUG:netmiko:_read_channel_expect read_data: rite mem
Warning: Attempting to overwrite an NVRAM configuration previously written
by a different version of the system image.
Overwrite the previous NVRAM configuration?[confirm]
DEBUG:netmiko:Pattern found: write\ mem write mem
Warning: Attempting to overwrite an NVRAM configuration previously written
by a different version of the system image.
Overwrite the previous NVRAM configuration?[confirm]
DEBUG:netmiko:read_channel:
DEBUG:netmiko:read_channel:

'''



@ktbyers  above is the output of "netmiko" logging. 
"DEBUG:netmiko:read_channel:" goes on for like 50 lines
An important thing I missed to state is, the config is written to the Router's running-config despite the error message.
But I could not figure out what causes the error.

The device in question is C7200 Router  Version 15.0(1)M

**Comment by ktbyers** [comment]
`Overwrite the previous NVRAM configuration?[confirm]`

You are trying to do a save_config, but the save config is prompting for confirmation (due to the OS version on the device changing). You will need to use write_channel/read_channel to handle this "wr mem" that is prompting you for confirmation.

Also it looks like you might have run into issues earlier in the output trying to use "nvram" as the file-system. You probably need to make sure you have a file-system to store files on the device.

**Comment by FSociety07** [comment]
>You are trying to do a save_config, but the save config is prompting for confirmation (due to the OS version on the device changing). You will need to use write_channel/read_channel to handle this "wr mem" that is prompting you for confirmation.

I ran the "write' cmd in the Router CLI and it prompted the same you mentioned. I hit the enter button there and then ran the script and it executed flawlessly.
I will look up how to use the "write_channel/read_channel".

>Also it looks like you might have run into issues earlier in the output trying to use "nvram" as the file-system. You probably need to make sure you have a file-system to store files on the device.

I have added a disk0: and removed the dest_file_system argument, so I believe by default disk0: is being used as the file system by NAPALM.

Thanks Kirk. You the king.
Closing the issue now. Please reopen if necessary.
