### ISSUE TITLE
SR Linux Community Driver repo request

### ISSUE THREAD

**Issue by jmlcv** [napalm-automation/napalm#1450]
### Repo request for community driver for Nokia SR Linux

Nokia developed a new product, SR Linux, and as SR OS, we developed a Napalm driver for it. We would like you to enable a repo so we can make it available as a community driver.

We would like to name the repo 'napalm-srlinux'.

Please grant write access to the following users:
- jmlcv  (me)
- mfzhsn

As you create the repo I will push the code. Alternatively, I noted on [this napalm automation group thread](https://groups.google.com/g/napalm-automation/c/kOBoiWjEK0g) that I could create a repo and transfer ownership to you. Please advise the proper way forward.

Existing code [Is available in this repo](https://github.com/jmlcv/napalm-srlinux/) if repo ownership is the way forward.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [x] Yes
- [ ] No

### Did you follow the steps from https://napalm.readthedocs.io/en/latest/contributing/#proposing-a-new-driver
- [x] Yes
- [ ] No

**Comment by mirceaulinic** [comment]
Hi @jmlcv. I have created https://github.com/napalm-automation-community/napalm-srlinux for you and granted access as requested. Let me know if you have any issues or questions! :wink:

**Comment by ktbyers** [comment]
@mirceaulinic Thanks for doing this :-)

**Comment by jmlcv** [comment]
@mirceaulinic Thank you!
