### ISSUE TITLE
Can we use numpy with napalm 

### ISSUE THREAD

**Issue by sen2diwakar** [napalm-automation/napalm#1507]
### Description of Issue/Question
Hi Kirk and team , 

I have a general query i have observed on occasions that numpy is faster than lists . However numpy is a collection of similar data types . 

Kindly let me know if we can pass numpy Like one mentioned below . because this code is giving me error and is unable to execute device.cli() commands in array and simply failing. If there is an alternate option let me know  . If i pass the commands as simple list it works fine then there is no issue :

```
import numpy as np
import threading
import datetime
import os
import sys
from napalm import get_network_driver


def VerifyInititalConfig(self):
    try:
       time.sleep(5)
       arr = np.array(['conf t','int gi 0/6', 'shut','end'])
       print(arr) 
       driver = get_network_driver('ios')
       optional_args = {'port': console_port, 'transport': 'telnet', 'global_delay_factor': 1}
       AgsObj = driver(console_ip, username, password, optional_args=optional_args)
       AgsObj.open()
       time.sleep(5)
       output = AgsObj.cli(arr)
       AgsObj.close()
    except:
        print("not working") 
```
*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [] Yes
- [x] No

### Setup

cisco 

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==3.2.0
napalm-base==1.0.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```

```

### Steps to Reproduce the Issue
1) pass list as an numpy array with set of commands . device.cli() will not work 

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```

```

**Comment by ktbyers** [comment]
Does your exact same code work or fail if you pass it in as a list?

What error do you get when you use numpy.

Note, Network devices are very slow so they will have seconds of delay in general--so whatever performance improvements you get by doing this will be swamped out by these delays.

**Comment by sen2diwakar** [comment]
hi kirk, 

i have given above code as a sample config but yes we have created multiple scripts where the exact same code will work , with set of commands  being passed as list in device.cli but not as numpy . 

 I just want to only use numpy in initial config only to make the initial config faster and remove global delay factor and i fully understand as you are right that network devices do have seconds of delay in general 

Best Regards,
Diwakar

**Comment by ktbyers** [comment]
You won't be able to remove `global_delay_factor` that is not a function of the input data structure, but of the interaction between Netmiko and the device.

Can you post the error you get when you try to use the numpy data structure?

**Comment by ktbyers** [comment]
Note, what you are doing above with NAPALM is probably not really valid even with a list. If you want to do that, you should probably convert straight over to Netmiko and use send_config_set().

For config changes in NAPALM you should use the standard NAPALM config operations.

**Comment by sen2diwakar** [comment]
```
case1: napalm and passing list in device.cli() ----> here i passed list and it worked 

>>> import numpy as np
>>> import threading
>>> import datetime
>>> import os
>>> import sys
>>> from napalm import get_network_driver
/home/sun/taf/env/bin/myenv/lib/python3.6/site-packages/cryptography-3.1-py3.6-linux-x86_64.egg/cryptography/hazmat/bindings/openssl/binding.py:177: CryptographyDeprecationWarning: OpenSSL version 1.0.2 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will drop support for it.
  utils.CryptographyDeprecationWarning,
>>> list = ['conf t','int gi 0/6', 'shut','end']
>>> driver = get_network_driver('ios')
>>> optional_args = {'port': 23, 'transport': 'telnet', 'global_delay_factor': 1}
>>> AgsObj = driver('10.22.11.22', <username>, <password>, optional_args=optional_args)
>>> AgsObj.open()
>>> output = AgsObj.cli(list)
>>> print(output)
{'conf t': '', 'int gi 0/6': '', 'shut': '', 'end': ''}   ---> all commands executed successfully  , this is correct output 



case2: napalm and passing numpy in device.cli() ----> here i passed numpy array and it did not worked 

>>> arr = np.array(['conf t','int gi 0/6', 'shut','end'])
>>> driver = get_network_driver('ios')
>>> optional_args = {'port': 23, 'transport': 'telnet', 'global_delay_factor': 1}
>>> AgsObj = driver('10.22.11.22', <username>, <password>, optional_args=optional_args)
>>> AgsObj.open()
>>> output = AgsObj.cli(arr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sun/taf/env/bin/myenv/lib/python3.6/site-packages/napalm-3.2.0-py3.6.egg/napalm/ios/ios.py", line 2876, in cli
    raise TypeError("Please enter a valid list of commands!")
TypeError: Please enter a valid list of commands!   --------> device.cli did not worked on numpy, incorrect output 

case3: remove global delay factor from napalm optional_args and use lists in device.cli()

>>> list = ['conf t','int gi 0/6', 'shut','end']
>>> driver = get_network_driver('ios')
>>> optional_args = {'port': 23, 'transport': 'telnet'} ---> global delay factor removed 
>>> AgsObj = driver('10.22.11.22', <username>, <password>, optional_args=optional_args)
>>> AgsObj.open()
>>> output = AgsObj.cli(list)
>>> print(output)
{'conf t': '', 'int gi 0/6': '', 'shut': '', 'end': ''} ---> all commands executed successfully  , this is correct output and without global delay factor

```
