### ISSUE TITLE
Cisco IOS - Support revert timer for both replace and merge configuration

### ISSUE THREAD

**Issue by DanSheps** [napalm-automation/napalm#1512]
### Description of Issue/Question

This is a pretty simple feature request for the Napalm Cisco IOS driver, and that is to support the revert timer for both replace and merge configurations.  For the replace method, the process is relatively straight forward as there is a built in command to replace the configuration which supports a revert timer.  For merge, the process gets more complicated as the configuration is merged using `copy [file] running-config`, but still manageable.

The process for a merge operation would be as follows:

1. Enter configuration terminal mode with "revert timer x" set, where x is the number of minutes to wait.
2. Exit configuration terminal mode
3. copy as normal to merge the configuration
4. commit the configuration

There was some work on this previously under PR #550 and there are custom tests available here: https://github.com/ktbyers/napalm_custom_test/tree/master/napalm_custom_test

I would be willing to take this up unless someone from the core team wants to.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq

- [X] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==3.3.1
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Cisco IOS Software [Gibraltar], Catalyst L3 Switch Software (CAT9K_IOSXE), Version 16.12.4, RELEASE SOFTWARE (fc5)
BOOTLDR: System Bootstrap, Version 17.3.1r[FC3], RELEASE SOFTWARE (P)
```

**Comment by ktbyers** [comment]
Completed in:

https://github.com/napalm-automation/napalm/pull/1691
