### ISSUE TITLE
IOS-XRv fails get_environment test

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#152]
@fooelisa Not sure if you want to do anything about this, but since I dug into it a bit I thought I would post what I saw.

This was on a Cisco IOS-XRv device. It would probably be nice to have it pass the unit test (so you could use an IOS-XRv device for testing purposes).

Running .get_environment() method would cause:

<pre>
$ ./napalm_iosxr_test.py 

>>>Test device open

>>>Test get environment

Traceback (most recent call last):
  File "./napalm_iosxr_test.py", line 38, in <module>
    env = device.get_environment()
  File "/home/kbyers/venv/napalm_test/local/lib/python2.7/site-packages/napalm-0.50.3-py2.7.egg/napalm/iosxr.py", line 497, in get_environment
    if node.find('Naming/NodeName/Slot').text == active_modules['RSP'][0]:    # first enabled RSP
IndexError: list index out of range
</pre>

Printing out the XML response from the initial rpc_command in that method:

```xml
<Response MajorVersion="1" MinorVersion="0">
  <Get ItemNotFound="true">
  <AdminOperational>
  <PlatformInventory MajorVersion="0" MinorVersion="4">
  <RackTable>
  <Rack>
  <Naming>
  <Name>0</Name>
  </Naming>
  <SlotTable MajorVersion="0" MinorVersion="0" NotFound="true" />
  </Rack>
  </RackTable>
  </PlatformInventory>
  </AdminOperational>
  </Get>
  <ResultSummary ErrorCount="0" ItemNotFound="true" />
</Response>
```

Unit test will basically fail the same way.

**Comment by mirceaulinic** [comment]
I can probably have a look at this issue in the next couple of days.
Anyway ```get_environment``` is slightly sub-optimal, given that the XML agent can eat multiple requests at once.

**Comment by dbarrosop** [comment]
This issue has been 'moved' to napalm-automation/napalm-iosxr#39
