### ISSUE TITLE
Sensitive data leaked in Exception thrown by commit_config()

### ISSUE THREAD

**Issue by tomhol** [napalm-automation/napalm#1521]
### When the `commit_config()` fails, the exception dumps the output which (in ios, perhaps other platforms too)
can contain the full config. Potentially leaking credentials and sensitive info.

Possible solution: The existing function `sanitize_config()` could be applied to the `output` to minimize the chances of leaking sensitive data.

If 100% backward compatibility is necessary (is it, in this case?) we could introduce new argument "sanitize_exception" with default value False.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [] Yes
- [X] No, not really

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
3.3.1
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
ios, potentially others too
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```

```

**Comment by ktbyers** [comment]
I don't view this as much of an issue . The people running the script should generally be allowed to see this (the person/process executing the script has `commit_config` privileges).

If you are wrapping NAPALM in some other application / web interface then you should control what is allowed to be viewed between the end-user and the app (i.e. you shouldn't elevate exceptions back to them).
