### ISSUE TITLE
Question about napalm License

### ISSUE THREAD

**Issue by lordofire** [napalm-automation/napalm#1550]
### Description of Issue/Question

From the official napalm documentation, napalm has Apache 2.0 license. However, I do see in the napalm 3.3.1, there is one library, `ciscoconfparse` with GPL license. Does that mean napalm itself should come with GPL license as well?

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==3.3.1
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
N/A
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
linux# pipdeptree --packages napalm | grep cisco
  - ciscoconfparse [required: Any, installed: 1.5.46]

```

**Comment by ktbyers** [comment]
IMO it means we have to rip out CiscoConfParse from NAPALM. CiscoConfParse is trivial to NAPALM library itself.

Adding the GPL requirements to NAPALM (after the fact) would be incompatible with how the contributions were made (i.e. would be adding additional licensing burdens after the fact that weren't consistent with the license under which the contributions were made).

I will do a PR to do this and we should incorporate this in the next release.

We should also add an automated process that checks for any GPL dependencies as it can be easy for them to leak in and thus have a totally unintended and undesired effect of trying to change the explicit license requirements.

**Comment by ktbyers** [comment]
Code to remove:

```
./ios/ios.py:        bgp_config_text = napalm.base.helpers.cisco_conf_parse_objects(
./ios/ios.py:            afi_list = napalm.base.helpers.cisco_conf_parse_parents(
./ios/ios.py:                neighbor_config = napalm.base.helpers.cisco_conf_parse_objects(
./ios/ios.py:            neighbor_config = napalm.base.helpers.cisco_conf_parse_objects(
./ios/ios.py:            afi_list = napalm.base.helpers.cisco_conf_parse_parents(
./ios/ios.py:                afi_config = napalm.base.helpers.cisco_conf_parse_objects(
./base/helpers.py:def cisco_conf_parse_parents(parent, child, config):
./base/helpers.py:def cisco_conf_parse_objects(cfg_section, config):
```

**Comment by lordofire** [comment]
That would be super, thanks for your effort on this!

**Comment by jvanderaa** [comment]
Would https://github.com/netdevops/hier_config be a possible replacement?

**Comment by ktbyers** [comment]
@jvanderaa Yeah, we only use it in one area of the code...so need to look at easiest option (i.e. just regex, textfsm, or doing something similar as confparse, but with non-GPL license).

**Comment by lordofire** [comment]
Hi @ktbyers , just curious if you have any planned timeline for the change? Thanks.

**Comment by ktbyers** [comment]
Hopefully, I can get this done in a week or two.

**Comment by jvanderaa** [comment]
Or possibly even using netutils here.

https://netutils.readthedocs.io/en/latest/netutils/configs/index.html#netutils.config.parser.IOSConfigParser

**Comment by jvanderaa** [comment]
I should have the base of what I have tested out here shortly for review, then will add tests.

**Comment by ktbyers** [comment]
@jvanderaa Great...thanks for doing this. 

I updated the PR here and fixed some linting and mypy issues:

https://github.com/napalm-automation/napalm/pull/1564

Note, it looks like `get_bgp_config` is failing on the NAPALM tests. I only glanced at it quickly but that looked like a real test failure due to the netutils changes.
