### ISSUE TITLE
Inconsistent speed/uptime between model and documentation

### ISSUE THREAD

**Issue by M0NsTeRRR** [napalm-automation/napalm#1650]
Hello,

I'm currently implementing a napalm driver.
On NetworkDriver documentation it says `get_interfaces()` has an attribute speed that must be an int in Mbit.
https://napalm.readthedocs.io/en/latest/base.html#napalm.base.base.NetworkDriver.get_interfaces
But in testing framework the model says it must be a float
https://github.com/napalm-automation/napalm/blob/b223f100bec827a7e40a15bdceddc6f78d902a32/napalm/base/models.py#L33

Best regards,

**Comment by network-shark** [comment]
@M0NsTeRRR Speed change to float in one of the last releases. It seems that I forgot the change the documentation.

**Comment by M0NsTeRRR** [comment]
I've reverted code change & updated the doc @network-shark
