### ISSUE TITLE
FSOS SSH Community Driver repo request

### ISSUE THREAD

**Issue by M0NsTeRRR** [napalm-automation/napalm#1665]
### Repo request for community driver for FSOS with SSH
Hello,

I've developped a community driver for FSOS using SSH because some FS switch does not support RPC API like S3900 and your current fsos driver (not finished yet) use RPC API.

Link of current repository => https://github.com/M0NsTeRRR/napalm-fsos-ssh

I would like to name the repo 'napalm-fsos-ssh'.

Please grant write access to the following users:

    M0NsTeRRR (me)

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### Did you follow the steps from https://napalm.readthedocs.io/en/latest/contributing/#proposing-a-new-driver
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

**Comment by mirceaulinic** [comment]
All yours @M0NsTeRRR: https://github.com/napalm-automation-community/napalm-fsos-ssh. 😄

**Comment by M0NsTeRRR** [comment]
Thanks repo is initialized :)
