### ISSUE TITLE
Support need for ipv6-mapped-ipv4  get_bgp_neigbhours() , otherwise it is breaking by raising value exception

### ISSUE THREAD

**Issue by AshikKuppili** [napalm-automation/napalm#1711]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
4.0.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
nxos_ssh
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```

```

**Comment by AshikKuppili** [comment]
bgp_table_parser
    raise ValueError(ipv6:ipv4)

**Comment by AshikKuppili** [comment]
@ktbyers can you please look into this

**Comment by mirceaulinic** [comment]
@AshikKuppili please reopen and provide more information.
