### ISSUE TITLE
OneAccess OneOs communauty driver - repo request

### ISSUE THREAD

**Issue by robin-gllt** [napalm-automation/napalm#1712]
### Repo request for Oneaccess OneOs driver (oneaccess-oneos)

Hello,

I wrote a napalm driver for OneAccess oneos devices. 
It is currently stored here:
https://github.com/robin-gllt/napalm-oneaccess-oneos

Could it be possible to integrate my driver in the relevant communauty driver repo? I see it has already been created (but it's currently empty).
https://github.com/napalm-automation-community/napalm-oneaccess-oneos

Thanks,
Robin

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq

- [x] Yes
- [] No

### Did you follow the steps from https://napalm.readthedocs.io/en/latest/contributing/#proposing-a-new-driver

- [x] Yes
- [] No

**Comment by mirceaulinic** [comment]
https://github.com/napalm-automation-community/napalm-oneaccess-oneos created and gave you admin rights @robin-gllt! 😄

**Comment by robin-gllt** [comment]
Thanks @mirceaulinic  :)
