### ISSUE TITLE
Add mock data for IOS

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm#172]
Could we add some mocked data for IOS so we can test without a device? Let me know if you need help or if you can't do it.

**Comment by dbarrosop** [comment]
@ktbyers I can't assign tasks to you because you are not part of the organization. Do you want me to add you as a contributor?

**Comment by ktbyers** [comment]
@dbarrosop This is fine.

**Comment by ktbyers** [comment]
@dbarrosop Why do you want to do this? I am not seeing that much value in it. It seems better to just test against a real device.

So I wanted to here your take on this.

**Comment by dbarrosop** [comment]
Well, it's hard to test against a device. It's way easier to test agains mocked data. How would you ensure otherwise that everybody has the same environment and state to do proper tests? Take for example BGP, you might want BGP sessions up, down, shutdown, sending prefixes, etc... Or lldp, multiple neighbors in the same interface, interfaces with only one neighbor... etc. In addition, I am planning to start integrating Travis with PRs and we can only do it with mocked data.

**Comment by ktbyers** [comment]
@dbarrosop You can test Travis-CI against real devices. You just have to encrypt certain things like the credentials and device information. I do this with the Netmiko library. It only works for the branch owner (might be able to work for collaborators would have to look into this). This is probably fine, though, since this is the person that is approving pull requests (collaborators might be nice to have)

Yes, it is way easier, but does it tell you much from the testing perspective?

**Comment by fooelisa** [comment]
I personally like the offline tests as well and would like to see them across all the drivers. We added travis for the offline tests yesterday and there is great value in PR's being checked automatically. Where are your devices set up so they are reachable from travis for Netmiko? Does it also test PR's, or do you have to re-run each test as the owner somehow?

**Comment by ktbyers** [comment]
@dbarrosop @fooelisa Looks like David wrote the code for this. So it isfine with me...I was reluctant to do the work, but if someone else does the work, not a problem. I do still question the value of it for file operations for IOS, for get_operations it is probably okay (at least as a sanity check).

The devices are at my office and I have allowed the Travis-CI IP addresses through my firewall. They are just test devices.

Yes, it is problematic as only I can run the test. So if it was a big change, I would need to checkout the branch and test it (and then accept the merge). If it was a small change, I could just accept the merge and regression test it.

**Comment by dbarrosop** [comment]
This has been done. @ktbyers if you want to improve the mocked data feel free.
