### ISSUE TITLE
nxos_ssh - Pattern not detected: 'AAAA\\-BBBB\\-1234\\-5678

### ISSUE THREAD

**Issue by KDOTN** [napalm-automation/napalm#1752]
### Description of Issue/Question
Pattern not detected on the hostname/command prompt on nxos_ssh. I think it's got to do with the long hostname and the backslashes because some methods like get_arp_table work.

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### Setup
from napalm import get_network_driver

NXOS = 'nxos_ssh'

def connect_to_device():
    driver = get_network_driver(NXOS)
    napalm_driver = driver(
        hostname='ip',
        username='username',
        password='password'

    )
    print('Connecting....')
    napalm_driver.open()
 
    print(napalm_driver.get_arp_table()) # works
    print(napalm_driver.get_facts()) # don't work, also get_interfaces don't work.
    napalm_driver.close()
    print('Connection closed')

def main():
    connect_to_device()
    
if __name__ == "__main__":
    main()
### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm=4.0.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Nexus 9000v
```

### Steps to Reproduce the Issue
python3 main.py
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```

Pattern not detected: 'AAAA\\-BBBB\\-1234\\-5678\\#' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

```

**Comment by Kani999** [comment]
@KDOTN Did you solve this problem? I've run into this problem right now.
