### ISSUE TITLE
Domain is pointing to casino blogspam

### ISSUE THREAD

**Issue by rgmz** [napalm-automation/napalm#1790]
The Napalm Automation domain, which is still linked on the front page of this organization, seems to have lapsed in 2021 and is now being used for blackhat SEO to promote gambling websites.
<img width="324" alt="image" src="https://user-images.githubusercontent.com/32133502/199015923-595e2610-15eb-4f6a-9a0a-3d014cd0e7ee.png">

I am avoiding linking it from this issue, however, I'm guessing this was done because the website is still linked from a few places. It would be best to remove the aforementioned link, and any other occurrences you may find.

**Comment by itdependsnetworks** [comment]
thanks! will update

**Comment by mirceaulinic** [comment]
Updated, thanks for letting us know!
