### ISSUE TITLE
[IOSXR ] napalm get interfaces ip returns ipv4 adresse : 0.0.0.0/0 ?

### ISSUE THREAD

**Issue by ansible75013** [napalm-automation/napalm#1820]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [X] Yes
- [] No

### Setup

I have an ansible-napalm napalm_get_facts with interfaces_ip filter (like get_interfaces_ip in python napalm)

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
[napalm](https://pypi.python.org/pypi/napalm)==4.0.0
[napalm-ansible](https://pypi.python.org/pypi/napalm-ansible)==1.1.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
[ansible](https://pypi.python.org/pypi/ansible)==2.10.0
[ansible-base](https://pypi.python.org/pypi/ansible-base)==2.10.6
[ansible-inventory-grapher](https://pypi.python.org/pypi/ansible-inventory-grapher)==2.4.4
```

### Steps to Reproduce the Issue
When interface (Cisco) has `ipv4 unreachables disabled`, napalm returns : ipv4 : 0.0.0.0/0  ??
Is this normal ?
The interface config (CLI):
interface GigabitEthernet0/0/0/5
 description -Z-- LIBRE ----
 ipv4 unreachables disable
 shutdown
!

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```

```

**Comment by ktbyers** [comment]
@ansible75013 Can you post the data structure that is returned by NAPALM?

**Comment by ktbyers** [comment]
You probably also need to debug what is returned by the XML calls for get_interfaces_ip() in the IOS-XR and post it here.

**Comment by ansible75013** [comment]
Thank you @ktbyers. Below the debug :

I get facts from Cisco ASR 9K with :
```
- name: Get facts from device using napalm
  napalm_get_facts:
    filter: ['facts','config','interfaces','interfaces_ip','ntp_servers','bgp_neighbors_detail']
    optional_args:
      ssh_config_file: ~/.ssh/config

  register: result_napalm_get_facts
  ignore_errors: True
``` 
Below is the returned results. Some interfaces wich are not configured are returned with ipv4==0.0.0.0/0 ??!

```
        "GigabitEthernet0/0/0/16": {
            "ipv4": {
                "0.0.0.0": {
                    "prefix_length": 0
                }
            },
            "ipv6": {
                "2001:660:4700:1006:0:41:0:2200": {
                    "prefix_length": 64
                }
            }
        },
        "GigabitEthernet0/0/0/5": {
            "ipv4": {
                "0.0.0.0": {
                    "prefix_length": 0
                }
            }
        },  
        "GigabitEthernet0/0/0/6.102": {
            "ipv4": {
                "10.110.200.46": {
                    "prefix_length": 29
                }
            }
        },      
```        

Need you more debug ? like the returned : `result_napalm_get_facts` ? 

Regards,

**Comment by ktbyers** [comment]
We need this also.

```
You probably also need to debug what is returned by the XML calls for get_interfaces_ip() in the IOS-XR and post it here.
```

**Comment by ktbyers** [comment]
i.e. we need to see what XML the device is returning when you do this `get_interfaces_ip` call. You can probably get that from the debugger in Python.

**Comment by ansible75013** [comment]
@ktbyers, I have enabled full debug by :
```
export ANSIBLE_LOG_PATH=/tmp/ansible.log
export ANSIBLE_DEBUG=True
time ./playbooks/10-get-routers-facts.yml -vvvv
```

But I did not find details of the XML calls .... How to activate that ? 

```
2023-01-12 11:46:13,710 p=6931  n=ansible | META: ran handlers
2023-01-12 11:46:13,716 p=6931  n=ansible | TASK [role-get-facts : Get facts from device using napalm] ********************************************************************************************************************
2023-01-12 11:46:13,716 p=6931  n=ansible | Thursday 12 January 2023  11:46:13 +0100 (0:00:00.899)       0:00:00.923 ******
2023-01-12 11:46:13,728 p=6975 
2023-01-12 11:46:13,774 p=6975  n=ansible | redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
2023-01-12 11:46:13,776 p=6975  n=ansible | Loading collection 
2023-01-12 11:46:13,803 p=6975 n=ansible | Loading collection cisco.iosxr from /home/playbook-automation/lib/python3.8/site-packages/ansible_collections/cisco/iosxr
2023-01-12 11:46:13,807 p=6975  n=ansible | redirecting (type: cliconf) ansible.builtin.iosxr to cisco.iosxr.iosxr
2023-01-12 11:46:14,219 p=6981  n=ansible | redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
2023-01-12 11:46:14,236 p=6981 n=ansible | redirecting (type: terminal) ansible.builtin.iosxr to cisco.iosxr.iosxr
2023-01-12 11:46:14,241 p=6981 n=ansible | redirecting (type: cliconf) ansible.builtin.iosxr to cisco.iosxr.iosxr
...
...
...

```

**Comment by ansible75013** [comment]
Finally, we will clean our routers configs by removing the useless config piece:
`ipv4 unreachables disable`.
`ipv4 mtu 9180` 

For more infos, we have 0.0.0.0/0 response when we have the `ipv4 config ` into an interface that not have an ipv4 !

I think that the presence of the key `ipv4`  is causing this behavior
I will close this issue ?!

**Comment by ktbyers** [comment]
Yeah, you would need to get out of Ansible and look at the XML calls in Python.

I am going to re-open the issue as NAPALM really shouldn't exhibit this behavior.

**Comment by ansible75013** [comment]
I identified three cases when napalm returns 0.0.0.0/0.
So globaly we have a 0.0.0.0/0, if the interface has no IPv4 address and its config contains:
- `ipv4 unreachables disable`
- `ipv4 mtu`
- Or `ipv6 is configured`
