### ISSUE TITLE
 FSOSv2 SSH Community Driver repo request

### ISSUE THREAD

**Issue by M0NsTeRRR** [napalm-automation/napalm#1848]
### Repo request for community driver for FSOSv2 with SSH
Hello,

I'm the maintainer of https://github.com/napalm-automation-community/napalm-fsos-ssh
An user raised an issue about a new firmware version (v2) napalm-automation-community/napalm-fsos-ssh#15 that will not be supported for older switch. They have nothing in commons (different commands and output).

If you agree I would like to name the repo 'napalm-fsosv2-ssh'.

Please grant write access to the following users:

    M0NsTeRRR (me)

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### Did you follow the steps from https://napalm.readthedocs.io/en/latest/contributing/#proposing-a-new-driver
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

**Comment by mirceaulinic** [comment]
@M0NsTeRRR you're already admin on that repo, so feel free to update as you need. :)
Let me know otherwise and I shall assist.
