### ISSUE TITLE
canonical_map not case sensitive for vlans 

### ISSUE THREAD

**Issue by network-shark** [napalm-automation/napalm#1861]
Hey ,

it seems all interfaces in the canonical map are well defined except the vlan translation. 

```
import napalm
from napalm.base.helpers import (
    canonical_interface_name,
    split_interface,
    abbreviated_interface_name,
)
interface = 'Vl8'


canonical_interface_name(interface)
'VLAN8'
```

If I pass this to the napalm.config_tree it breaks , because it tries to lookup 
```
 KeyError: 'interface VLAN8'  

```
Return of the napalm.config_tree
```
interface Vlan8:
    ----------
    description test :
        ----------
    ip address 10.0.0.0 255.255.255.0:

```

I would suggest to change the cannonical map from VLAN to Vlan . This would be compatible with the napalm.config_tree function. 

Let me know what you think about and I will create a PR

best regards , sebastian

**Comment by ktbyers** [comment]
@itdependsnetworks Any issues here in making this change?

**Comment by network-shark** [comment]
@itdependsnetworks push

**Comment by itdependsnetworks** [comment]
I do not think it makes sense to change. This has come up before in netutils: https://github.com/networktocode/netutils/issues/158#issuecomment-1287046776, and the a reason to that you can bring your own mapping is just for this use case.

**Comment by ktbyers** [comment]
That sounds reasonable to me.

**Comment by network-shark** [comment]
Just for people how a stumpling across this ... just pass it to .capitalize() 

```
>>> text = 'VLAN999'
>>> text.capitalize()
'Vlan999'
```
