### ISSUE TITLE
Unknown device model

### ISSUE THREAD

**Issue by XioNoX** [napalm-automation/napalm#187]
Using the IOS driver on 3 different switches always returns 'model': u'Unknown'

>>> from netmiko import ConnectHandler
>>> from napalm import get_network_driver
>>> get_network_driver('ios')
<class napalm.ios.IOSDriver at 0x7fc3a1763a78>
>>> driver = get_network_driver('ios')
>>> device = driver('IP', 'xionox', 'pass')
>>> device.open()
>>> device.get_facts()

> {'os_version': u'IOS-XE Software, Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 03.03.05SE RELEASE SOFTWARE (fc1)', 'uptime': 6721260, 'interface_list': [u'Vlan1', u'Vlan206', u'GigabitEthernet0/0', u'GigabitEthernet1/0/1', u'GigabitEthernet1/0/2', u'GigabitEthernet1/0/3', u'GigabitEthernet1/0/4', u'GigabitEthernet1/0/5', u'GigabitEthernet1/0/6', u'GigabitEthernet1/0/7', u'GigabitEthernet1/0/8', u'GigabitEthernet1/0/9', u'GigabitEthernet1/0/10', u'GigabitEthernet1/0/11', u'GigabitEthernet1/0/12', u'GigabitEthernet1/0/13', u'GigabitEthernet1/0/14', u'GigabitEthernet1/0/15',......], 'vendor': u'Cisco', 'serial_number': u'ABCD', 'model': u'Unknown', 'hostname': u'switch1.df101-1', 'fqdn': u'switch1.df101-1.xxxxxxx'}

Show version returns:
cisco WS-C3850-48T (MIPS) processor with 4194304K bytes of physical memory.
And more down the page (as stacked switches)
Model Number                       : WS-C3850-48T

Same with:

> {'os_version': u'IOS-XE Software, Catalyst 4500 L3 Switch Software (cat4500e-UNIVERSALK9-M), Version 03.04.05.SG RELEASE SOFTWARE (fc1)',[...]

cisco WS-C4500X-32 (MPC8572) processor (revision 9) with 4194304K/20480K bytes of memory.

And

> {'os_version': u'CBS31X0 Software (CBS31X0-UNIVERSALK9-M), Version 12.2(58)SE1, RELEASE SOFTWARE (fc1)',[...]

show version:
cisco WS-CBS3120X-S (PowerPC405) processor (revision E0) with 262144K bytes of memory.
and more down the page (stacked as well):
Model number                    : WS-CBS3120X-S

Thanks

**Comment by ande0581** [comment]
I can take a look at this issue. The big difference offhand is the switches start with lowercase 'cisco'.
