### ISSUE TITLE
Pattern not detected: '(?:[>##]\\s*$|.*all username.*confirm)' in output

### ISSUE THREAD

**Issue by mkonagai** [napalm-automation/napalm#1897]
### Description of Issue/Question

*Note*: Please check https://guides.github.com/features/mastering-markdown/
to see how to properly format your request.

I am trying to replace the running config of the device to the backup file, and if the backup file contains version info in the content, it successfully replaces the running config and startup config of the device while it also throwing an error; Pattern not detected: '(?:[>##]\\s*$|.*all username.*confirm)' in output at the end.

If I remove the version info from the backup file, then it will generate another error; 
%The input file is not a valid config file.

Is it only applicable to Cisco IOSv version?

from napalm import get_network_driver
driver = get_network_driver('ios')
device = driver('192.168.0.11', 'admin', 'admin')
device.open()

#device.load_merge_candidate(filename='29_cisco_route')
device.load_replace_candidate(filename='30_cisco_backup')
print(device.compare_config())

if len(device.compare_config()) > 0:
    choice = input("\nWould you like to Replace the configuration? [yN]: ")
    if choice == "y":
        print("Committing ...")
        device.commit_config()
        choice = input("\nWould you like to Rollback to previous config? [yN]: ")
        if choice == "y":
            print("Committing ...")
            device.rollback()       
    else:
        print("Discarding ...")
        device.discard_config()
else:
    print('No difference')

# close the session with the device.
device.close()
print("Done.")

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==4.0.0
nornir-napalm==0.3.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
Cisco IOS Software, IOSv Software (VIOS-ADVENTERPRISEK9-M), Version 15.6(1)T, RELEASE SOFTWARE (fc1)
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
Traceback (most recent call last):
  File "/Users/Desktop/05_PYTHON_DEMO/30_napalm_cisco_config_replace_rollback.py", line 14, in <module>
    device.commit_config()
  File "/Users/Desktop/05_PYTHON_DEMO/P3.10/lib/python3.10/site-packages/napalm/ios/ios.py", line 559, in commit_config
    output = self._commit_handler(cmd)
  File "/Users/Desktop/05_PYTHON_DEMO/P3.10/lib/python3.10/site-packages/napalm/ios/ios.py", line 467, in wrapper
    return f(self, *args, **kwargs)
  File "/Users/Desktop/05_PYTHON_DEMO/P3.10/lib/python3.10/site-packages/napalm/ios/ios.py", line 484, in _commit_handler
    output = self.device.send_command(cmd, expect_string=patterns)
  File "/Users/Desktop/05_PYTHON_DEMO/P3.10/lib/python3.10/site-packages/netmiko/utilities.py", line 592, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/Users/Desktop/05_PYTHON_DEMO/P3.10/lib/python3.10/site-packages/netmiko/base_connection.py", line 1721, in send_command
    raise ReadTimeout(msg)
netmiko.exceptions.ReadTimeout: 
Pattern not detected: '(?:[>##]\\s*$|.*all username.*confirm)' in output.

Things you might try to fix this:
1. Explicitly set your pattern using the expect_string argument.
2. Increase the read_timeout to a larger value.

You can also look at the Netmiko session_log or debug log for more information.
```

**Comment by ktbyers** [comment]
@mkonagai It is failing on your commit_config() operation, you should do the commit_config() operation manually from the CLI and see what your device is doing when this happens.

NAPALM does a `configure replace` operation on a file stored in `flash:` (or other file-system on the device) to accomplish the commit_config.

**Comment by mkonagai** [comment]
@ktbyers It seems working fine after following your comment. Thank you!
