### ISSUE TITLE
EAPI does not work when python 3.10 or 3.11 is leveraged

### ISSUE THREAD

**Issue by ryanmerolle** [napalm-automation/napalm#1909]
### Description of Issue/Question

More of an upstream issue, that we can track here.
Relates to arista-eosplus/pyeapi/issues/246

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [X] Yes
- [ ] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==4.0.0
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
unrelated to Network OS, only related to python version
```

### Steps to Reproduce the Issue

Leverage python3.10 install and run any napalm script that connect to an EAPI device.

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)
Traceback (most recent call last):
  File "/home/rmerolle/.local/lib/python3.10/site-packages/pyeapi/eapilib.py", line 453, in send
    self.transport.endheaders(message_body=data)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)
Error connecting to the device: Socket error during eAPI connection: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)
```

**Comment by ktbyers** [comment]
@ryanmerolle Which version of pyeapi?

**Comment by ktbyers** [comment]
@ryanmerolle 

See:

https://github.com/napalm-automation/napalm/issues/1731

**Comment by ryanmerolle** [comment]
Apologies I missed this.  Then I guess its up to downstream dependent packages like netbox-napalm to implement this approach.  Sort of annoying its not handled natively in pyeapi.

**Comment by ktbyers** [comment]
Does netbox-napalm allow you to pass in NAPALM optional_args (in some way)?

Both pyeapi and napalm have a solution which allow you to pass in an SSL context that fixes the issue (albeit by using worse TLS security). The issue (if I am understanding it correctly) is that older versions of EOS have poor TLS settings which newer versions of Python do not allow.

**Comment by ryanmerolle** [comment]
It allows you to pass json optional_args via the ui.  This would require more than that.

I'll PR the workaround/helper to napalm-netbox.  The 2 options that I am testing (both work):

- if the driver used is eos and the python version is greater than 3.9, then apply the workaround
- try/except if the error condition presents itself with an eos driver, then apply the workaround
