### ISSUE TITLE
Deprecate EOS < 4.23F in next NAPALM release

### ISSUE THREAD

**Issue by bewing** [napalm-automation/napalm#1941]
Considering refactoring EOSDriver to only support newer versions of EOS in the next release.  This means removing the CLI translator for FN0039, updating all code to only use the new commands, and updating methods for newer JSON-enabled commands.

Please register any displeasure as comments to this issue.

**Comment by mirceaulinic** [comment]
I believe this is now merged into the develop branch? @bewing
