### ISSUE TITLE
Bump pyeapi to v1.0.0 to address 3.10 & 3.11 ssl issues

### ISSUE THREAD

**Issue by ryanmerolle** [napalm-automation/napalm#1958]
### Description of Issue/Question

Related issues: 
#1909
#1731 

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [ ] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
napalm==4.1.0
```

### Network operating system version
Any Arista EOS

**Comment by ryanmerolle** [comment]
I'll test this shortly and submit a PR

**Comment by bewing** [comment]
From the release notes:
* Arista EOS 4.22 or later is required

do we need to delay for #1941 ?

**Comment by ktbyers** [comment]
We should just couple those two together i.e. `develop` branch only supports `>= 4.23F` and both of these are part of that.

Since we just did a release, it will be a few months before we do the next release anyways.

Sound good?
