### ISSUE TITLE
Documentation is outdated due to a build error

### ISSUE THREAD

**Issue by M0NsTeRRR** [napalm-automation/napalm#2065]
Hello,

Documentation hosted on RTD is outdated, there is an issue when building the documentation

https://readthedocs.org/projects/napalm/builds

Last successfull operation was 7 months ago

**Comment by M0NsTeRRR** [comment]
We should have a failure notification from RTD and it should notify somewhere to prevents it again.
Linked to #1697

**Comment by ktbyers** [comment]
Read the docs changed things...

```
We are announcing the deprecation of build.image config key in favor of build.os. Read the Docs will start requiring a build.os config key for all projects in order to build documentation successfully. We will start failing builds for projects not using “build.os” in their config file on October 16, 2023.
```

The error is due to the missing `build.os`.

**Comment by ktbyers** [comment]
I will need @mirceaulinic to look at it (as I don't have access on the read-the-docs side). GitHub webhooks is stating a 400 error.

I suspect readthedocs changed things / broke things on their side.

**Comment by M0NsTeRRR** [comment]
Documentation build is now fixed. If we intend to have documentation for both versions 5.X and 4.X, we need to port changes similar to what @mirceaulinic did for the master branch. Otherwise, we can consider closing the issue.
