### ISSUE TITLE
get_vlans for ios not removing whitespace with no interfaces

### ISSUE THREAD

**Issue by Smertan** [napalm-automation/napalm#2086]
### Description of Issue/Question

When the `get_vlans` command was run via Nornir I noticed a few VLAN names did not strip the whitespace. Upon further investigation, I realised the VLAN `names` that suffered the issues had no interfaces assigned to them. 

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [] No

### napalm version

```
napalm 5.0.0
```

### Network operating system version

```
Cisco IOS XE software, Version 17.09.03
```

**Comment by ktbyers** [comment]
Fixed in this PR:

https://github.com/napalm-automation/napalm/pull/2087
