### ISSUE TITLE
Incomplete entries in IOS get_arp getter returns exception

### ISSUE THREAD

**Issue by fherbet** [napalm-automation/napalm#231]
in case of incomplete entries in IOS "sh arp"

PAR000621#sh arp          
Protocol  Address          Age (min)  Hardware Addr   Type   Interface
[...]
Internet  Y.Y.Y.Y             0   Incomplete      ARPA   
[...]

then ANSIBLE reports

TASK [get facts from device] ***************************************************
fatal: [X.X.X.X]: FAILED! => {"changed": false, "failed": true, "msg": "cannot retrieve device data: Unexpected output from: [u'Internet', u'Y.Y.Y.Y', u'0', u'Incomplete', u'ARPA']"}

works fine when there's no incomplete entry

**Comment by dbarrosop** [comment]
Hello @fherbet,
wo

**Comment by dbarrosop** [comment]
napalm-ios 0.1.3 has been released solving this problem.
