### ISSUE TITLE
1. Hackathon 2016 - Interest?

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm#273]
TBD

If you think you might be interested in joining a NAPALM hackathon feel free to add a comment saying "hi", "I'm in", "This is gonna be awesome", "Howdy" or just with your favorite emoji. That way I will be able to get a rough idea of how many people might be interested on this.

In addition, feel free to subscribe to this issue to get notifications as we start discussing potential dates and the scope of the hackathon.

**Comment by GGabriele** [comment]
Hi, I'm in since this is gonna be awesome :D

**Comment by viniciusarcanjo** [comment]
Let's do it! +1

**Comment by jtdub** [comment]
+1

**Comment by DiogoAndre** [comment]
Awesome!

**Comment by jedelman8** [comment]
All time permitting man, but if I'm free, I'm in.

**Comment by jwbensley** [comment]
Sounds great to me!

**Comment by fooelisa** [comment]
+1 - when and where?

**Comment by filapinoaquino** [comment]
I'm in

**Comment by laetrid** [comment]
Count me in, hope it will be online event :)

**Comment by dbarrosop** [comment]
Regarding when/where, give me a couple of days to look at a few options and I will open a couple of issues to discuss those.

Regarding being online, it's going to be online for sure. We might organize something physically as well but we will have hangouts, slack, etc, and communication should be primarily via those tools. So don't worry about that : )

**Comment by jejenone** [comment]
I'm in.

**Comment by chadell** [comment]
+1

**Comment by ktbyers** [comment]
I should be in.

**Comment by ebeahan** [comment]
+1

**Comment by cebotareanu** [comment]
+1 :)

**Comment by jathanism** [comment]
Sounds fun! This is the perfect excuse to contribute. 👍

**Comment by dbarrosop** [comment]
Announcement #276

**Comment by inetuid** [comment]
Wasn't watching, so missed the announcement. I'll try and make it.
