### ISSUE TITLE
Hackathon 2016 - Proposed tasks

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm#274]
# Drivers
## Minor enhancements

I would add the following in the list of minor enhancements:
- IOS-XR:
  - https://github.com/napalm-automation/napalm-iosxr/issues/28
  - https://github.com/napalm-automation/napalm-iosxr/issues/15
  - https://github.com/napalm-automation/napalm-iosxr/issues/29
  - napalm-automation/napalm-iosxr#17
  - napalm-automation/napalm-iosxr#18
  - napalm-automation/napalm-iosxr#20
- JUNOS:
  - https://github.com/napalm-automation/napalm-junos/issues/27
  - https://github.com/napalm-automation/napalm-junos/issues/20
  - https://github.com/napalm-automation/napalm-junos/issues/32
- EOS:
  - https://github.com/napalm-automation/napalm-eos/issues/31
- NXOS:
  - https://github.com/napalm-automation/napalm-nxos/issues/20

**Comment by mirceaulinic** [comment]
Can we group them by driver?

I would add the following in the list of minor enhancements:

- IOS-XR:
  - https://github.com/napalm-automation/napalm-iosxr/issues/28
  - https://github.com/napalm-automation/napalm-iosxr/issues/15
  - https://github.com/napalm-automation/napalm-iosxr/issues/29
- JUNOS:
   - https://github.com/napalm-automation/napalm-junos/issues/27
   - https://github.com/napalm-automation/napalm-junos/issues/20
  - https://github.com/napalm-automation/napalm-junos/issues/32
- EOS:
   - https://github.com/napalm-automation/napalm-eos/issues/31
- NXOS:
   - https://github.com/napalm-automation/napalm-nxos/issues/20

**Comment by dbarrosop** [comment]
Done
