### ISSUE TITLE
New docs section: installation

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#284]
### Description of Issue

Unfortunately a couple of libraries required in NAPALM drivers do not cover properly the installation steps for various operating systems.

### Solution

To make it simpler for NAPALM users, we should probably include all documentation bits in one single place.

**Comment by bordeltabernacle** [comment]
I also wonder if it's worth adding a `Automation Frameworks` page as well, for instructions on how to use and integrate with these frameworks?

**Comment by dbarrosop** [comment]
I have merged a bunch of stuff we had pending, I will close this for the moment. Feel free to create a new issue/send PR if you think something can be improved.
