### ISSUE TITLE
Adding CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md files

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm#297]
I would like to add two documents with guidelines regarding contributing and opening pull requests.

`CONTRIBUTING.md` should contain our guidelines, something detailed. For simplicity I would recommend implementing this into RTD documentation and linking there with this file.

`PULL_REQUEST_TEMPLATE.md` I would suggest here adding just a checklist, something like:
1. Have you added mocked data and enabled tests?
2. Do all the tests pass?
3. ...

things like that.

When we have decided on the contents I will "spread" this issue.

**Comment by mirceaulinic** [comment]
We should probably distinguish between a pull request for a driver and napalm-base.

For driver we can have pretty much the following options:

- bug fix
- method implementation

While in napalm-base would be different yet more complex:

- new helper
- new method
- new exception
- bug fix
- base test changes
- others?

We can add something like this for drivers:

```
### What does this PR do?

### What issues does this PR fix?

### Mock data provided?

[ ] Yes
[ ] No

### Tests enabled?

[ ] Yes
[ ] No
```

And something like this for napalm-base:

```
### What does this PR do?

### What issues does this PR fix?

### New method proposal? Please provide the motivation and expected usage.

### Tests written?

[ ] Yes
[ ] No
```

I'm sure we can find better description for the sections I have in mind.

Thoughts?

**Comment by dbarrosop** [comment]
I don't want to manage this in those files, I'd rather do it in RTD to avoid having to update all the repos for a slight change. So I went with this: https://github.com/napalm-automation/napalm-eos/pull/42

What do you think?

**Comment by mirceaulinic** [comment]
Makes sense, it would be a nightmare to maintain indeed. But I'm not sure how many will follow the link and read the RTD document :)

**Comment by mirceaulinic** [comment]
Already solved.
