### ISSUE TITLE
new napalm driver for MLXe routers

### ISSUE THREAD

**Issue by ckishimo** [napalm-automation/napalm#362]
I implemented a few methods for a new napalm driver for Brocade (now Extreme) MLXe routers based on naplam-skeleton. I ignore if there are some mandatory methods... please let me know how to proceed. I'm newbie developing/contributing code, so please bear with me 

https://github.com/ckishimo/napalm-extreme-netiron

Thanks!

**Comment by LindsayHill** [comment]
Cool, good start @ckishimo

**Comment by dbarrosop** [comment]
Great job! As there are no configuration related commands this should be fairly easy to validate and test but you will have to provide mocked data. You will have to patch this file to provide a test double:

https://github.com/ckishimo/napalm-extreme-netiron/blob/master/test/unit/conftest.py

You can probably look at that file on the `ios` driver for reference. Then you will have to provide mocked data. At the end, running `py.test` should run all the tests and return green (you can clone any other driver and run that command to see an example)

**Comment by ckishimo** [comment]
Thanks! taking the ios driver as a reference was very helpful. I just pushed a new version of the driver with the mocked data and passing all the tests. Please let me know next steps. Thanks

**Comment by dbarrosop** [comment]
Next steps:

1. Decide if the name is the one we want. I don't have an opinion about this. @LindsayHill would you care to chime in or bring someone else to the discussion that might be interested in (also see 2)?
2. Someone a part from you should test with a real device or VM. I am afraid I don't have access to any so I can really test myself :(
3. Send PR to main organization (if you want to move it there, ofc) and peer review
4. Publish

**Comment by ckishimo** [comment]
According to #https://github.com/napalm-automation/napalm-brocade-slxos/issues/5 
it was decided to name it <code>napalm-\<vendor\>-\<platform\></code>, so <code>napalm-extreme-netiron</code> should be ok :) but let's wait for @LindsayHill
Regarding 3) I'll be happy to send a PR once 1) and 2) are resolved

**Comment by LindsayHill** [comment]
Oh that's right, now we need to change to Extreme. I'm cool with napalm-extreme-netiron. Officially Brocade & Extreme are still separate companies, but looks like acquisition will go ahead, so might as well plan ahead

**Comment by dbarrosop** [comment]
Hi!
just wanted to check on this. Any update?

Regards

**Comment by thomarite** [comment]
Hi all

My employeer has several MLXe and I need an excuse to get involved in napalm and automation. I am very very new on this so I am happy to get involved and test this driver.

Regards

**Comment by dbarrosop** [comment]
Hi,
we should revisit this issue after the reunification event. The whole process should be easier then:

https://napalm-automation.net/reunification/

Thanks for your patience.
David

**Comment by dbarrosop** [comment]
So sorry for the late response. It's been crazy and we were trying to get some documentation around this topic so I have been hogging on this one for a while. Sorry again for the delay.

You have some info here:

http://napalm.readthedocs.io/en/develop/contributing/drivers.html#contributing-drivers

And even though is not 100% up to date there is a cookicutter template for a driver here:

https://github.com/napalm-automation/napalm-cookiecutter

If you have specific questions don't hesitate to drop by our slack channel or drop me an email.

**Comment by dbarrosop** [comment]
I am closing this ticket, feel free to reopen if you feel there is something to discuss or you need something from us.
