### ISSUE TITLE
Support Cisco AireOS (Wireless controller)

### ISSUE THREAD

**Issue by cognifloyd** [napalm-automation/napalm#376]
### Description of Issue/Question
Please add support for Cisco AireOS devices such as their Wireless LAN Controllers.
Configuration is over an SSH cli that looks similar to IOS and other devices.

The device I'm targeting is [Cisco 2500 Series WLC](http://www.cisco.com/c/en/us/products/wireless/2500-series-wireless-controllers/index.html). All of the other Cisco WLCs use the same OS, but might use later versions. Though the docs don't say "AireOS" the wifi guy I work with says that's what the OS on them is called. The docs call it "Cisco Unified Wireless Network Software Release" or "Cisco Wireless Release" (e.g. see the "bulletins" [here](http://www.cisco.com/c/en/us/products/wireless/2500-series-wireless-controllers/bulletin-listing.html) and [here](http://www.cisco.com/c/en/us/products/wireless/8500-series-wireless-controllers/bulletin-listing.html)).

**Comment by ktbyers** [comment]
@cognifloyd You are welcome to write it, but it is unlikely that someone will write it for you (unless someone has a significant need for this and wants to).

There is a Netmiko driver for Cisco WLC so you could see if that accomplishes what you need.

**Comment by dbarrosop** [comment]
I am closing this one as this is something the core group of napalm will not be working on. If you want to work on this yourself and need help or guidance feel free to reopen.
