### ISSUE TITLE
Not understanding diffs for IOS

### ISSUE THREAD

**Issue by herste** [napalm-automation/napalm#397]
### Description of Issue/Question

Having a running IOS router with a config snippet like
```
crypto keyring KEYRING_FOO vrf BAR
  pre-shared-key address 1.2.3.4 key mykey1
  pre-shared-key address 5.6.7.8 key mykey2
```

in the current configuration of the device, and using a local changeset with 

```
crypto keyring KEYRING_FOO vrf BAR
  pre-shared-key address 1.2.3.4 key mykey1
  pre-shared-key address 5.6.7.8 key mykey3
```

i would expect napalm to create a diff for the third line only and when converting that to IOS commands to execute something like

```
crypto keyring KEYRING_FOO vrf BAR
  no pre-shared-key address 5.6.7.8 key mykey2
  pre-shared-key address 5.6.7.8 key mykey3
```

But this does not seem to be executed. Are there any limitations with napalm on such a config where the existing lines are nested into a subcommand and have to be removed with the appropriate "no" before?

Thanks for your help!
Cheers,
Heri

**Comment by ktbyers** [comment]
@herste 

```
i would expect napalm to create a diff for the third line only and when converting that to IOS commands to execute something like

crypto keyring KEYRING_FOO vrf BAR
  no pre-shared-key address 5.6.7.8 key mykey2
  pre-shared-key address 5.6.7.8 key mykey3

**Comment by herste** [comment]
Thanks alot for explaining, I get the point that you dont expect target configuration and calculate the diff but more or less the commands that will result in the desired configuration.
