### ISSUE TITLE
common data models for getter methods should be improved

### ISSUE THREAD

**Issue by wisotzky** [napalm-automation/napalm#407]
Most get_XXX() seem to be relevant for LAN switches/routers only. It is needed to improve the data models to cover better with Carrier PE Routers, BNGs and Firewalls.

Some examples:
get_arp_table() does not specify the routing context. Does it mean the function is for base router instance only? In general it would be meaningful, the get_arp_table() method would have a parameter to define the context such as VRF, IP-VPN, Out-of-band Mgmt or Base router.

get_interfaces() seems to be about physical interfaces, like ports. What about logical interfaces, such as linkagg, ip-interfaces, L2VPN bindings, internal loopbacks, ...?

get_mac_address_table() assumes that the VLAN-Id defines the bridge instance per device. In the SP market typically the VLAN-Id is just port significant - so you could have much more than 4094 ELAN/VPLS services per device.

**Comment by dbarrosop** [comment]
Yes, that is correct. Take a look at `napalm-yang`, it's using OpenConfig so it should be generic enough. We haven't implemented there as many `getters` there yet but given that what you are asking is not here either we should implement it there.

**Comment by ktbyers** [comment]
I don't think there is any direct action to take here (individuals can work on contributing to napalm-yang to improve this situation and in certain cases there is ongoing work to add additional support into some existing getters).
