### ISSUE TITLE
documentation for templates are missing

### ISSUE THREAD

**Issue by wisotzky** [napalm-automation/napalm#408]
Is there any documentation for the Jinja2 configuration templates.
The only I've found is:
    set_hostname - Configures the hostname of the device.
    set_ntp_peers - Configures NTP peers of the device.
    delete_ntp_peers - Removes NTP peers form device’s configuration.
    set_probes - Configures RPM/SLA probes.
    schedule_probes - Cisco only
    delete_probes - Removes RPM/SLA probes.

Especially the set/schedule/delete probe is very dedicated to Cisco and Juniper. It would be good to generalize those functions to allow easier mapping to other vendor implementations.

Anyhow, some sort of documentation per function would be good - especially how the data instance looks like which should drive those templates. Today development of templates requires reverse engineering of existing templates.

**Comment by ktbyers** [comment]
Closing as it is very, very old.
