### ISSUE TITLE
Support for LCOS?

### ISSUE THREAD

**Issue by s-m-e** [napalm-automation/napalm#419]
This is not a feature request, more an inquiry: Has someone yet considered or started to work on support for LCOS (the "LANCOM Operating System")? Its driving a number of routers, switches and firewalls manufactured by LANCOM Systems GmbH in Germany. At a first glance, there is no API - just a web interface and a custom made console / shell, accessible by ssh and telnet, with a mix of custom dos-style and bash-style commands. 

Its manual can be found here: https://www.lancom-systems.de/docs/config/en/refmanual/

**Comment by dbarrosop** [comment]
I am afraid I have never heard of them and can't recall anyone mentioning them so I don't think anyone is working on it.

**Comment by s-m-e** [comment]
LANCOM was formed in 2002 after its de-facto predecessor, the original ELSA company, went bankrupt. I have seen their devices popping up more and more in the post-snowden area thanks to "initiatives" like "IT Security made in Germany" ... It's what you get when your compliance guidelines tell you to buy a domestic product. 

I'd like to add rudimentary support. I found [this page in the manual](http://napalm.readthedocs.io/en/latest/base.html) and [this driver skeleton repository](https://github.com/napalm-automation/napalm-skeleton) - beyond that, are there any guidelines I could or should read first?

**Comment by ktbyers** [comment]
@s-m-e I am going to close this, if you have more questions on how to create a driver just re-open a new issue.
