### ISSUE TITLE
Add VRF support to "get_bgp_neighbors" for IOS driver.

### ISSUE THREAD

**Issue by bdlamprecht** [napalm-automation/napalm#420]
### Description of Issue/Question
Currently, the `ios` driver only captures the "global" BGP neighbors and states this is the case in the documentation.
However, the `junos` driver captures **_both_** "global" as well as "VRF" BGP neighbors.

This is being opened under the generic `napalm` repo as directed by @dbarrosop since the re-unification process is underway.

**Comment by mirceaulinic** [comment]
This has been resolved via https://github.com/napalm-automation/napalm/pull/768, included in version 2.5.0.
