### ISSUE TITLE
reunification process

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm#421]
This issue tracks the progress of the reunification process. `STATUS` below will be updated to inform of steps carried out.

For more details on the plan visit: https://docs.google.com/document/d/1wxst7fuBxKxRP6mhN6MGxmyUn9inkn5HoXihZ9xpmf8/edit?usp=sharing

# How to help?

You can help by testing, reviewing the changes and informing of anything that might be broken. Anything you might highlight will be welcomed.

Feel free to add a comment below for general comments or in the following PR if you want to comment on a particular bit of code: https://github.com/napalm-automation/napalm/pull/422

### from a cloned repo

```
$ git clone git@github.com:napalm-automation/napalm.git
$ cd napalm
$ git checkout reunification
$ pip install -e .
```

### from github

```
pip install -e git://github.com/napalm-automation/napalm.git@reunification#egg=napalm_reunification
```

### from pip

Not yet, eventually we will publish beta versions on pip so you can install from there.

# STATUS

* reunification branch is ready for testing
* [doc](https://napalm.readthedocs.io/en/reunification/index.html) generation has been fixed

## Drivers migrated

* eos
* ios
* junos

# Tips

## Adapting import paths

If you have import paths like `napalm_eos` or `napalm_base` you can easily migrate your import paths with the following lines:

```
find path/to/your/code -type f -exec sed -i '' 's/napalm_base/napalm\.base/g' {} \;
find path/to/your/code -type f -exec sed -i '' 's/napalm_eos/napalm\.eos/g' {} \;
```

**Comment by ogenstad** [comment]
Should the docs for the "Partial Installation" just be wiped and perhaps replaced with extra drivers? Or converted into a section which points to the last released versions of the split drivers.

**Comment by ogenstad** [comment]
Also regarding the documentation it mentions `from napalm import get_network_driver` should that be supported or changed to `from napalm.base import get_network_driver`?

**Comment by dbarrosop** [comment]
> Should the docs for the "Partial Installation" just be wiped and perhaps replaced with extra drivers? 

We will adapt it soon for the new method. We are still unsure how it will but mostly likely something like:

```
pip install napalm --install-options='eos' --install-options='junos'
```

> Also regarding the documentation it mentions from napalm import get_network_driver should that 

We should probably just get rid of the `napalm.base` import and provide `napalm`. We have to adapt `napalm_base` endpoint either way so let's make it backwards compatible for the people using the `napalm` one.

**Comment by ogenstad** [comment]
>pip install napalm --install-options='eos' --install-options='junos'

I'm guessing that would be for the extra drivers and not the supported core ones? Not really sure if the above would be better than `pip install napalm[eos,junos]` It looks like that option came in pip 7.0 when using a requirements.txt file:
https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format

Though I would guess NAPALM wouldn't install with earlier versions regardless. A thought I had about this split was if anyone wanted to create NAPALM rpm or deb packages later. Don't know if it will have any impact, perhaps it would just be a matter of installing the extra requirements in a different way.

**Comment by dbarrosop** [comment]
we are not going to use `pip install napalm[eos]` format because that's hardcoded for a very specific use case that doesn't match ours so we will proceed with `--install-options` instead. We will allow installing individual drivers because luckily these two are equivalent:

```
pip install napalm-eos napalm-ios
pip install napalm --install-option="--drivers=eos,ios"
```

> A thought I had about this split was if anyone wanted to create NAPALM rpm or deb packages late

It should just work, as long as the maintainer respects the namespace of the python package it should be fine.

**Comment by mirceaulinic** [comment]
I would just like to clarify what are the requirements here:

- When executing `pip install napalm` this should install the entire lists of requirements (base + eos + junos + ... etc)

- When executing `pip install napalm --install-option="--drivers=eos,ios"`, this installs the requirements only for eos and ios.

Unfortunately something like `pip install napalm[eos]` is trying to install all the requirements from `pip install napalm` (i.e., everything) + the specific req for eos (which are actually already included when you do `pip install napalm`), which is not what we want.

I agree however that something like `pip install napalm --install-option="--drivers=eos,ios"` doesn't look very sexy, but we didn't find yet a better solution. Suggestions welcome, of course :-)

**Comment by dbarrosop** [comment]
Ok, that doesn't work. `pip` and the whole python packaging ecosystem is pretty terrible. A few notes:

1. pip will pass `--install-option` to dependencies so you get errors like this:

```
(reunification) ➜  napalm git:(reunification) ✗ pip install --no-cache-dir --pre --install-option="--drivers=ios" -U napalm
...
Installing collected packages: netmiko
  Running setup.py install for netmiko ... error
    Complete output from command /Users/dbarroso/.virtualenvs/reunification/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/t7/zfjhsch50sxb_c748t64wg2r0000gp/T/pip-build-MZBj8s/netmiko/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/t7/zfjhsch50sxb_c748t64wg2r0000gp/T/pip-3QxX5W-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/dbarroso/.virtualenvs/reunification/bin/../include/site/python2.7/netmiko --drivers=ios:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --drivers not recognized
```

2. I have been trying to create custom commands and see if setuptools would somehow expose the `extras_require` with no avail...

After 4 hours trying things I am out of ideas. If anyone has any, I will appreciate it.

**Comment by dbarrosop** [comment]
I finally got it working:

```
# to install everything
pip install napalm

# to install a driver (--pre is only necessary now because we are in beta)
pip install --pre --install-option="ios" napalm

# to install multiple drivers
pip install --pre --install-option="eos" --install-option="junos" napalm

# to add drivers to an existing instalation
pip install --pre --install-option="eos" --install-option="junos" --force-reinstall -U napalm
```

**Comment by ogenstad** [comment]
What would happen if someone were to install Napalm and later upgrade without specifying the install options?

```
pip install --install-option="eos" --install-option="junos" napalm==2.0.1
pip install napalm==2.0.2
```

Could there be problems if the 2.0.2 release requires later packages for some drivers compared to the 2.0.1 release?

**Comment by dbarrosop** [comment]
You are going to basically install **all** the requirements with the second commands. If versions are pinned in the requirement files for each specific drivers those should be enforced as usual.

**Comment by ogenstad** [comment]
Ah, saw in the setup file now. Had the impression that the drivers wouldn't be installed by default, was thinking about support questions related to that. This looks much better.

**Comment by ktbyers** [comment]
Reunification is done. Closing this issue.
