### ISSUE TITLE
Proposal: napalm library should abstract away internal files and directory structure

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#427]
There are two fundamental ways that `__init__.py` can be used:

1. As a way to enable directory traversal and with some very minimal level of code definition.

2. As a method of hiding the internal directory structure and file names of a library (or some meaningful part thereof).

There is disagreement in the Python community on how `__init__.py` should be used. Some projects use only item 1; others use item 1 and 2.

I researched some various large Python projects yesterday and here were some results:

### Largely use` __init__.py` for only directory traversal and minimal code definiton:
- twisted
- pytest
- boto

### Use `__init__.py` for directory traversal and abstracting library internals
- requests
- flask
- django (somewhat but it wrapped things inside a setup() function and was still pretty minimal)
- paramiko

I also looked at lxml also but it was integrating to C libraries.
 

I am pretty strongly in favor that we should use `napalm/__init__.py` to abstract away the internal library directory names and file names. In principle, this is exactly the same issue that the NAPALM library itself was created for. 

Basically, if we do not abstract these away, then are directories and file names become a part of our programming interface. This results in it being difficult for us to change library internals. It also makes it more likely for us to break code for users that are using our code.

Here is a first pass at some things that should be in `napalm/__init__.py`:

```
from napalm.base import get_network_driver
from napalm._SUPPORTED_DRIVERS import SUPPORTED_DRIVERS

from napalm.base.base import NetworkDriver
from napalm.base.exceptions import ReplaceConfigException, MergeConfigException, \
            ConnectionClosedException, CommandErrorException

from napalm.base.utils import py23_compat  # noqa
from napalm.base import constants       # noqa
from napalm.base import helpers     # noqa
```

Here is a test repo where I made the changes also to the IOS driver. 

https://github.com/ktbyers/napalm/commit/2a7c2bef5caf038c62c16ce8a24d7a0b0a5d59e0

I am less concerned about changing internal library references. I view this as largely optional (as we can always change internal references at a later date without breaking the code of any library users).

### What about performance?
I don't think this has a meaningful impact on memory size as `get_network_driver` will load `napalm.base.__init__` which will load almost all these things anyways. If we want to improve memory usage then we should figure out a way to not generally import large external libraries (in cases where they are not used).

### As part of this we should ensure that it is backwards compatible with Salt, StackStorm2, Ansible, and Netbox (if we do the above): 

Basically we should ensure that nothing here breaks backwards compatibility with other major tools that rely on us. I think this can be accomplished essentially equivalently with what is required for reunification. In other words, it will be the same level of difficulty as the problem we already have.

### Why it matters now?
Once we tell people to update the code to the new reunified structure and how to do that...we are exceptionally unlikely to ask them to do this again. This will potentially start publishing library internals to end-users and as more and more users rely on these things...it will be harder and harder to change.

**Comment by dbarrosop** [comment]
I am not a fan of hiding (hiding != abstracting) directory structure as it makes it harder to navigate the code as a developer but I see the value in our case to provide a "public API" so we can change the code structure without notifying people, specially given our track record.

How are we going to expose in this public API the drivers? I think we should extend this to the drivers so I can get things like the drivers and their constants directly. For example:

```
from napalm import eos
eos.EOSDriver
eos.constants
# not sure if there is anything else we might want to expose from the drivers themselves
```

**Comment by mirceaulinic** [comment]
I agree with both of you on some particular points:

From David:
> I am not a fan of hiding (hiding != abstracting) directory structure as it makes it harder to navigate the code as a developer

Yes, I am not a fan of hiding stuff either.

> I see the value in our case to provide a "public API" so we can change the code structure without notifying people, specially given our track record.

Indeed.

From Kirk:
> Use __init__.py for directory traversal and abstracting library internals

I'll add `pyzmq` to this list too (of course there are many many others, but for the point I'd like to make below): I was once trying to catch an exception in ZMQ, I had a block of code raising an exception called `Again`, so I started looking at the code, but I was surprised that the code was raising `zmq.Again`, instead of `zmq.error.Again` (somehow I would have expected that the `Again` class should be clearly in a separate module, making it self-explanatory that it is an exception class).

I identify the same pattern in:

```python
from napalm.base.exceptions import ReplaceConfigException, MergeConfigException, \
            ConnectionClosedException, CommandErrorException
```

I don't like that, and I don't see the value of `except napalm.ReplaceConfigException`, as in opposite to `napalm.exceptions.ReplaceConfigException`.

But I do like the following:

```python
from napalm.base.utils import py23_compat  # noqa
from napalm.base import constants       # noqa
from napalm.base import helpers     # noqa
```

Although I have mixed feelings about `napalm.py23_compat`, but that's just a small point anyway.

I do like however:

```python
from napalm.base import get_network_driver
from napalm._SUPPORTED_DRIVERS import SUPPORTED_DRIVERS
from napalm.base.base import NetworkDriver
```

With these said, I believe we shouldn't try to adopt a single pattern, but rather decide what makes sense and what doesn't.

**Comment by dbarrosop** [comment]
Yeah, I agree with you in the sense we should keep some sort of structure and not shove everything into `napalm`. So we should have things like:

```
napalm.base # for common things
napalm.eos # for eos related stuff
napalm.exceptions # for exceptions
...
```

`get_network_driver` and `SUPPORTED_DRIVERS` are probably the exception and can be just returned in the root namespace.

I am not so sure about `from napalm.base.utils import py23_compat`. I think that's an internal import, that's not part of the public API so we shouldn't have it in there. I think we should have in there only what we expect people to import use in their code.

I actually think we should extend this to `base`, `eos`, `ios`, etc... so we can clearly indicate what's part of the public API and what not. That way these two should be equivalent:

```
# neither of these two should let people use things we don't consider "public"
from napalm import eos  
import napalm.eos
```

So if people does:

```
from napalm.eos import something_not_public
```

it's up to them and completely at their own risk.

**Comment by ktbyers** [comment]
It sounds like we should decide the following:

1. What is public in the NAPALM library?
     a. Is this public for library consumers or public for library developers (I would include anyone that subclasses NAPALM to be in the developer category)?
     b. Assuming this is public for library consumers...do we have any notion of public for NAPALM developers?

2. Once we define what is going to be public, we should indicate where these things will live (this will define our public API i.e. what will be hard for us to change).

**Comment by ktbyers** [comment]
I would propose the following should be public to library consumers (not saying where they necessarily should live structurally or from an import perspective)

```
get_network_driver
SUPPORTED_DRIVERS
ReplaceConfigException, MergeConfigException, ConnectionClosedException, CommandErrorException
helpers
constants
```

I don't really think we need to expose the drivers as `get_network_driver` should be the proper way to retrieve the driver.

We could also directly expose the driver classes, but we would just have to do this in such a way as not to break our partial install of requirements (if you are only using a subset of drivers).

I didn't really see anything else in drivers that should be public (looking at 'eos' and 'ios'). Though there probably are some regular expression definitions in IOS that need moved to base (as they apply beyond IOS).

**Comment by bewing** [comment]
> We could also directly expose the driver classes, but we would just have to do this in such a way as not to break our partial install of requirements (if you are only using a subset of drivers).

We could probably do this with importlib and `SUPPORTED_DRIVERS` to import installed driver classes and append their names to `napalm.__all__` ?

**Comment by ktbyers** [comment]
I don't think there are additional actions here...
