### ISSUE TITLE
get_environment temperature generates an exception against SRX

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#429]
napalm-junos 0.12.0

get_environment against an Juniper SRX yielded:

```
  File "/home/kbyers/VENV/py35_venv/local/lib/python3.5/site-packages/napalm_junos/junos.py", line 399, in get_environment
    if structured_temperature_data['red-alarm'] <= temp:
TypeError: unorderable types: int() <= NoneType()
```

**Comment by ckishimo** [comment]
@mirceaulinic I think this should be fixed as well with https://github.com/napalm-automation/napalm/pull/552/commits/b2e6cb9cbcde6caa4aa91753152210910edd9f4e in PR #552 
Pls let me know if you have the chance to test that again. Thanks

**Comment by dbarrosop** [comment]
@mirceaulinic can you review this issue and the linked PR?
