### ISSUE TITLE
SRX get_facts() enhancement: clustering

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#432]
### Description of Issue/Question
Can we add clustering information to srx get_facts()?
```show chassis cluster summary```

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
[* ] Yes
[ ] No

### napalm-junos version
(Paste verbatim output from `pip freeze | grep napalm-junos` between quotes below)

```
0.11.0
```

### JunOS version
(Paste verbatim output from `show version and haiku` between quotes below)

```
srx firewall
```

### Steps to Reproduce the Issue
N/A
### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
N/A
```

----

Moved from https://github.com/napalm-automation/napalm-junos/issues/190, for further considerations for particular cases like that. We'll need to discuss what's the best way to handle platform-specific facts.

**Comment by bobthebutcher** [comment]
at $job we have lots of clustered juniper devices. I can work on this during the hackathon
