### ISSUE TITLE
get_facts() does report internal OS version, not the OS version. 

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#436]
### Description of Issue/Question
get_facts() does report internal OS version, not the OS version.

I assume that is by choice but I believe that is an incorrect behaviour.

### napalm-eos version
(Paste verbatim output from `pip freeze | grep napalm-eos` between quotes below)

```
 # pip freeze | grep napalm-eos
napalm-eos==0.6.0
```

---

Moved from https://github.com/napalm-automation/napalm-eos/issues/177, this discussion will be needed for the platform-specific facts.

**Comment by ktbyers** [comment]
I am going to close, I seem to vaguely recollect we were at disagreement over this. If this is still viewed as an issue, we can review the history and potentially re-address.
