### ISSUE TITLE
get_lldp_neighbors_detail() to include remote_port_type'

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#437]
### Description of Issue/Question

Not a bug but a proposal for an additional field in the response from get_lldp_neighbors_detail()

Currently the response data model includes "remote_port" which is mapped from the 'port ID' LLDP TLV.  However, the Port ID also has a type, 'Port ID type' which can be a number of different things.

The following are the types specified in IEEE's LLDP MIB, [LldpPortIdSubtype](url)

>     SYNTAX  INTEGER {
>             interfaceAlias(1),
>             portComponent(2),
>             macAddress(3),
>             networkAddress(4),
>             interfaceName(5),
>             agentCircuitId(6),
>             local(7)

The following example, taken from the mocked data tests, the  'remote_port" is of MAC address type.  Depending on the LLDP implementation, they may use different types. Arista switches use type 4 (interfaceName), Linux's lldpd uses type 3 (macAddress) while putting in the interface name in the port description TLV. If I remember correctly, NX-OS uses type 7 (local).

>  u'Ethernet9': [{u'parent_interface': u'Ethernet9',
>    u'remote_chassis_id': u'2C:60:0C:AD:2E:D2',
>    u'remote_port': u'000f.532e.f290',
>    u'remote_port_description': u'eth2',
>    u'remote_system_capab': u'bridge, router, wlanAccessPoint',
>    u'remote_system_description': u'Linux 3.18.22-cloudflare x86_64',
>    u'remote_system_enable_capab': u'',
>    u'remote_system_name': u'78m4'}]}
 
So the conclusion is that it would be quite useful to include the 'port id type' as well in the response to give a hint about what information is provided.

As it is right now, If I want to get the remote interface name, I have to apply some logic to try to guess such as regex matching the port ID against expected interface names and if it doesn't match use the remote port description instead.

In the eAPI result, the dictionary key describing the port ID type is called "interfaceIdType" 

Unfortunately, the cli output in IOS for instance, does not include the remote port ID type at all so it could be a challenge to implement for IOS. As far as I know that information can only be retrieved via SNMP from an IOS device, but hopefully I am wrong in that respect.

---

Issue moved from https://github.com/napalm-automation/napalm-eos/issues/178, fur further considerations.

**Comment by ktbyers** [comment]
I would have thought that we should normalize this behavior. In other words, we should have a dictionary key like `remote_port` that always returns the remote interface name (regardless of what the vendor does).

Or worded differently, we should normalize the behavior so that any ambiguity about what is returned in our dictionary keys is removed. So to me `remote_port` should always be the remote interface name.
