### ISSUE TITLE
Neither NX-OS SSH nor nx-api save the running-config to startup-config on replace

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#438]
Issue moved from https://github.com/napalm-automation/napalm-nxos/issues/145

**Comment by ktbyers** [comment]
NXOS_SSH doesn't save the configuration to startup on a replace operation. It does on a merge.

**Comment by ktbyers** [comment]
Fixed here: https://github.com/napalm-automation/napalm/pull/624
