### ISSUE TITLE
nxos replace operation - add to docs

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#446]
Can't use `show run` for initial config of replace operation; need to use a checkpoint file.

```
checkpoint test-checkpoint-kb description some text 
# need all to get defaults
show checkpoint test-checkpoint-kb all
```

need to be careful about copy-and-paste from box as line-wrap can introduce invalid newlines for very long lines.

**Comment by ktbyers** [comment]
This is documented here:

http://napalm.readthedocs.io/en/latest/support/nxos.html
