### ISSUE TITLE
Atomic Merge

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#447]
Could the merge process be made atomic by taking a snapshot that could be rolled back just before the merge? I thought about writing an enhancement, but I wanted to check here first to see if there is some other technical reason that merges cannot be atomic on this platform.

@jedelman8:

> Makes sense.  This is actually how we do atomic changes with Ansible on
nxos using the nxos_rollback and ntc_rollback modules.  So yes, in
agreement for merges:  Step 1.  Create a checkpoint file.  Step 2: send
commands.  Step 3: rollback on error

---

Issue moved from https://github.com/napalm-automation/napalm-nxos/issues/77

**Comment by ktbyers** [comment]
I think we should do this i.e. before merge operation create a checkpoint that could be rolled back to.

It still wouldn't be atomic as 1. if we are disconnected, there will be no rollback, 2. Partial changes could go through which you would have to manually handle and rollback, 3. You potentially would have to do this manually.

Though for both items 2 and 3 we could check for errors in the merge attempt and auto-rollback which we probably should do.

I probably view this as a bug i.e. we should already be doing some of this.

**Comment by ktbyers** [comment]
This should be fixed here https://github.com/napalm-automation/napalm/pull/833
