### ISSUE TITLE
Inconsistent MAC and IPv6 format for several IOS getters

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#451]
### Description of Issue/Question

https://github.com/napalm-automation/napalm-ios/pull/110 shows that as of napalm-ios 0.6.0, the following methods need a bit of work and use the `ip` and `mac` napalm-base helpers:

- [x] get_mac_address_table, fixed in https://github.com/napalm-automation/napalm-ios/pull/110
- [x] get_arp_table, fixed in https://github.com/napalm-automation/napalm-ios/pull/110
- [x] get_interfaces
- [ ] get_lldp_neighbors
- [ ] get_lldp_neighbors_detail
- [ ] get_bgp_neighbors
- [ ] get_interfaces_ip
- [ ] get_ntp_peers
- [ ] traceroute
- [ ] ping

### napalm-ios version
(Paste verbatim output from `pip freeze | grep napalm-ios` between quotes below)

```
0.6.0
```

---

Issue moved from https://github.com/napalm-automation/napalm-ios/issues/111

**Comment by mundruid** [comment]
I am interested in pushing this issue through the finish line. Let me know if this is still valid or it has already been fixed. Thanks!

**Comment by mirceaulinic** [comment]
Resolved via #1560.
