### ISSUE TITLE
Is autodetect dir always needed?

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#458]
### Description of Issue/Question

Using getters, would not seem like you would always need to auto_detect the dir filesytem. 

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
- [ x ] Yes
- [ ] No

### napalm-ios version
(Paste verbatim output from `pip freeze | grep napalm-ios` between quotes below)

```
napalm-ios==0.5.1
```

### IOS version
(Paste verbatim output from `show version` between quotes below)

```
Any
```

### Steps to Reproduce the Issue

Using Napalm-ansible and getters with napalm-ios, seems to require the dir check no matter what. This requires a different level of privileges then show commands. Is there a way to remove this dependency?

### Error Traceback

```

```

---

Issue moved from https://github.com/napalm-automation/napalm-ios/issues/148

**Comment by ktbyers** [comment]
This should be fixed.
