### ISSUE TITLE
get_mac_table not parsing routed ports correctly

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#464]
cat4500e-universalk9.SPA.03.04.05.SG.151-2.SG5.bin
Cisco IOS Software, IOS-XE Software, Catalyst 4500 L3 Switch Software (cat4500e-UNIVERSALK9-M), Version 03.04.05.SG RELEASE SOFTWARE (fc1)
WS-C4506-E

Unicast Entries
vlan mac address type protocols port
---------+---------------+--------+---------------------+-------------------------
60 0001.d800.022c dynamic ip,ipx,assigned,other GigabitEthernet2/10

60 0001.d800.023a dynamic ip,ipx,assigned,other GigabitEthernet2/25

60 000d.5d0a.e3cf dynamic ip,ipx,assigned,other FastEthernet6/40

60 0010.7f1f.a2bd dynamic ip,ipx,assigned,other GigabitEthernet5/45

60 0010.7f2c.2049 dynamic ip,ipx,assigned,other FastEthernet6/43

60 0010.7f2c.3b36 dynamic ip,ipx,assigned,other GigabitEthernet4/17

60 0010.7f2c.6ffa dynamic ip,ipx,assigned,other GigabitEthernet4/17

60 0010.7f2d.5fcd dynamic ip,ipx,assigned,other GigabitEthernet4/26

60 0010.7f2d.a114 dynamic ip,ipx,assigned,other GigabitEthernet4/26

60 0010.7f38.9bd3 dynamic ip,ipx,assigned,other GigabitEthernet5/42

60 0010.7f3d.e5cf dynamic ip,ipx,assigned,other GigabitEthernet4/13

60 0015.bd00.a940 dynamic ip,ipx,assigned,other FastEthernet6/48

60 0040.1135.3f3c dynamic ip,ipx,assigned,other FastEthernet6/44

60 0040.1136.c735 dynamic ip,ipx,assigned,other FastEthernet6/46

60 0050.6008.3dcb dynamic ip,ipx,assigned,other FastEthernet6/6

60 0050.6008.3dcf dynamic ip,ipx,assigned,other GigabitEthernet2/12

60 0050.600d.8c05 dynamic ip,ipx,assigned,other GigabitEthernet4/47

60 204c.9e7f.5541 dynamic ip,ipx,assigned,other GigabitEthernet5/31

60 204c.9e7f.7441 dynamic ip,ipx,assigned,other GigabitEthernet2/12

60 3c97.0e8f.9375 dynamic ip,ipx,assigned,other GigabitEthernet2/13

60 3c97.0e8f.97ee dynamic ip,ipx,assigned,other GigabitEthernet3/42

60 3c97.0e8f.d5cd dynamic ip,ipx,assigned,other GigabitEthernet4/32

60 3c97.0e93.840a dynamic ip,ipx,assigned,other GigabitEthernet4/30

60 3c97.0ec1.170d dynamic ip,ipx,assigned,other GigabitEthernet2/21

60 3c97.0ec1.2363 dynamic ip,ipx,assigned,other GigabitEthernet2/19

60 3c97.0ec3.3259 dynamic ip,ipx,assigned,other GigabitEthernet3/7

60 3c97.0ec3.32e2 dynamic ip,ipx,assigned,other GigabitEthernet3/32

60 3c97.0ec3.339f dynamic ip,ipx,assigned,other GigabitEthernet3/2

60 3c97.0ec3.355e dynamic ip,ipx,assigned,other GigabitEthernet3/5

60 3c97.0ec3.3680 dynamic ip,ipx,assigned,other GigabitEthernet5/4

60 3c97.0ec3.377b dynamic ip,ipx,assigned,other GigabitEthernet5/38

60 3c97.0ec3.37a3 dynamic ip,ipx,assigned,other FastEthernet6/19

60 3c97.0ec3.37cb dynamic ip,ipx,assigned,other GigabitEthernet3/45

60 3c97.0ec3.39e1 dynamic ip,ipx,assigned,other GigabitEthernet4/37

60 3c97.0ec3.3a6e dynamic ip,ipx,assigned,other GigabitEthernet2/6

60 3c97.0ec3.3efd dynamic ip,ipx,assigned,other GigabitEthernet5/30

60 3c97.0ec3.4073 dynamic ip,ipx,assigned,other GigabitEthernet3/6

60 3c97.0ec3.409b dynamic ip,ipx,assigned,other GigabitEthernet3/17

60 3c97.0ec3.4450 dynamic ip,ipx,assigned,other GigabitEthernet4/12

60 3c97.0ec5.5978 dynamic ip,ipx,assigned,other GigabitEthernet5/6

60 3c97.0ec8.4bbf dynamic ip,ipx,assigned,other GigabitEthernet5/11

60 3c97.0eda.42bb dynamic ip,ipx,assigned,other GigabitEthernet5/29

60 3c97.0ee3.6387 dynamic ip,ipx,assigned,other GigabitEthernet2/9

60 3c97.0ee3.7d3c dynamic ip,ipx,assigned,other GigabitEthernet3/46

60 4437.e6c5.e54f dynamic ip,ipx,assigned,other GigabitEthernet2/30

60 4437.e6c6.2426 dynamic ip,ipx,assigned,other GigabitEthernet2/42

60 4437.e6c6.4442 dynamic ip,ipx,assigned,other GigabitEthernet5/10

60 4437.e6c6.4458 dynamic ip,ipx,assigned,other GigabitEthernet5/2

60 507b.9d4e.1425 dynamic ip,ipx,assigned,other GigabitEthernet2/36

60 507b.9d4e.1eca dynamic ip,ipx,assigned,other GigabitEthernet5/22

60 507b.9d54.7543 dynamic ip,ipx,assigned,other GigabitEthernet3/48

60 507b.9d59.b90d dynamic ip,ipx,assigned,other GigabitEthernet2/40

60 507b.9d59.b9b6 dynamic ip,ipx,assigned,other GigabitEthernet3/47

60 507b.9d59.bbd5 dynamic ip,ipx,assigned,other GigabitEthernet5/3

60 54ee.7517.99c6 dynamic ip,ipx,assigned,other GigabitEthernet2/28

60 7081.0555.a77f static ip,ipx,assigned,other Switch

60 7081.05c9.6665 dynamic ip,ipx,assigned,other GigabitEthernet5/39

60 70ca.9b15.32d5 dynamic ip,ipx,assigned,other GigabitEthernet5/41

60 70ca.9b15.3312 dynamic ip,ipx,assigned,other GigabitEthernet5/37

60 70ca.9b25.5283 dynamic ip,ipx,assigned,other GigabitEthernet5/43

60 7486.7a6d.1028 dynamic ip,ipx,assigned,other FastEthernet6/26

60 9c93.4e33.13cc dynamic ip,ipx,assigned,other GigabitEthernet3/39

60 9c93.4e34.2e65 dynamic ip,ipx,assigned,other GigabitEthernet3/10

60 bc16.653e.a8f8 dynamic ip,ipx,assigned,other FastEthernet6/24

60 d867.d96f.bf71 dynamic ip,ipx,assigned,other GigabitEthernet5/12

60 dceb.946c.e7c1 dynamic ip,ipx,assigned,other GigabitEthernet5/14

60 dceb.946c.e941 dynamic ip,ipx,assigned,other FastEthernet6/43

60 e411.5bb2.d10c dynamic ip,ipx,assigned,other FastEthernet6/35

60 eca8.6bfc.05ba dynamic ip,ipx,assigned,other GigabitEthernet3/24

60 ecb1.d7f9.7481 dynamic ip,ipx,assigned,other GigabitEthernet4/9

170 7081.0555.a77f static ip,ipx,assigned,other Switch

170 9caf.ca7d.cbc1 dynamic ip,ipx,assigned,other GigabitEthernet1/6

506 001b.4f34.d1cd dynamic ip,ipx,assigned,other GigabitEthernet3/13

506 001b.4f34.e20a dynamic ip,ipx,assigned,other GigabitEthernet5/4

506 001b.4f34.e20b dynamic ip,ipx,assigned,other GigabitEthernet5/28

506 001b.4f35.1400 dynamic ip,ipx,assigned,other GigabitEthernet4/37

506 001b.4f35.1472 dynamic ip,ipx,assigned,other GigabitEthernet5/8

506 001b.4f35.1a45 dynamic ip,ipx,assigned,other GigabitEthernet2/15

506 001b.4f35.1c81 dynamic ip,ipx,assigned,other GigabitEthernet5/14

506 001b.4f42.e5b6 dynamic ip,ipx,assigned,other GigabitEthernet5/38

506 001b.4f42.f9b8 dynamic ip,ipx,assigned,other GigabitEthernet4/12

506 001b.4f42.fc30 dynamic ip,ipx,assigned,other GigabitEthernet2/42

506 001b.4f43.02ff dynamic ip,ipx,assigned,other GigabitEthernet5/16

506 001b.4f43.0495 dynamic ip,ipx,assigned,other GigabitEthernet4/32

506 001b.4f46.5cd5 dynamic ip,ipx,assigned,other GigabitEthernet2/32

506 001b.4f56.e0d2 dynamic ip,ipx,assigned,other FastEthernet6/15

506 001b.4f56.ec84 dynamic ip,ipx,assigned,other GigabitEthernet2/12

506 001b.4f56.ed45 dynamic ip,ipx,assigned,other GigabitEthernet3/30

506 001b.4f56.f585 dynamic ip,ipx,assigned,other GigabitEthernet3/43

506 001b.4f5a.e0ae dynamic ip,ipx,assigned,other GigabitEthernet5/20

506 001b.4f5a.f125 dynamic ip,ipx,assigned,other GigabitEthernet3/42

506 001b.4f5b.3c31 dynamic ip,ipx,assigned,other GigabitEthernet2/36

506 001b.4f5b.4cf7 dynamic ip,ipx,assigned,other GigabitEthernet3/2

506 001b.4f5b.4d2b dynamic ip,ipx,assigned,other FastEthernet6/47

506 001b.4f5b.4db9 dynamic ip,ipx,assigned,other GigabitEthernet3/15

506 001b.4f5b.4e18 dynamic ip,ipx,assigned,other GigabitEthernet4/18

506 001b.4f5b.4e76 dynamic ip,ipx,assigned,other GigabitEthernet5/27

506 001b.4f5b.5488 dynamic ip,ipx,assigned,other GigabitEthernet4/16

506 001b.4f5b.5edd dynamic ip,ipx,assigned,other GigabitEthernet3/3

506 001b.4f5b.5f14 dynamic ip,ipx,assigned,other GigabitEthernet4/4

506 001b.4f5b.5f5c dynamic ip,ipx,assigned,other GigabitEthernet4/2

506 001b.4f5b.6bf8 dynamic ip,ipx,assigned,other GigabitEthernet2/1

506 001b.4f5b.6d06 dynamic ip,ipx,assigned,other GigabitEthernet3/46

506 001b.4f5b.6d99 dynamic ip,ipx,assigned,other GigabitEthernet5/3

506 001b.4f5b.70aa dynamic ip,ipx,assigned,other GigabitEthernet3/4

506 001b.4f5b.7481 dynamic ip,ipx,assigned,other GigabitEthernet3/16

506 001b.4f5b.7537 dynamic ip,ipx,assigned,other GigabitEthernet4/23

506 001b.4f5b.753f dynamic ip,ipx,assigned,other GigabitEthernet2/11

506 001b.4f5b.7843 dynamic ip,ipx,assigned,other GigabitEthernet3/32

506 001b.4f5b.833b dynamic ip,ipx,assigned,other FastEthernet6/1

506 001b.4f5b.d8ab dynamic ip,ipx,assigned,other GigabitEthernet2/14

506 001b.4f5b.da16 dynamic ip,ipx,assigned,other GigabitEthernet4/38

506 001b.4f5b.e4f0 dynamic ip,ipx,assigned,other GigabitEthernet2/39

506 001b.4f5b.e54d dynamic ip,ipx,assigned,other GigabitEthernet2/46

506 001b.4f5b.e616 dynamic ip,ipx,assigned,other GigabitEthernet2/21

506 001b.4f5b.e626 dynamic ip,ipx,assigned,other GigabitEthernet4/43

506 001b.4f5b.e63e dynamic ip,ipx,assigned,other GigabitEthernet3/21

506 001b.4f5b.e659 dynamic ip,ipx,assigned,other GigabitEthernet2/19

506 001b.4f5b.e65f dynamic ip,ipx,assigned,other GigabitEthernet4/41

506 001b.4f5b.e690 dynamic ip,ipx,assigned,other GigabitEthernet2/40

506 001b.4f5b.e719 dynamic ip,ipx,assigned,other GigabitEthernet2/8

506 001b.4f5b.e737 dynamic ip,ipx,assigned,other GigabitEthernet3/45

506 001b.4f5b.ea38 dynamic ip,ipx,assigned,other GigabitEthernet3/7

506 001b.4f5b.ea3d dynamic ip,ipx,assigned,other GigabitEthernet5/47

506 001b.4f5b.eac4 dynamic ip,ipx,assigned,other GigabitEthernet3/11

506 001b.4f5b.eb6c dynamic ip,ipx,assigned,other GigabitEthernet3/19

506 001b.4f5b.ebd0 dynamic ip,ipx,assigned,other GigabitEthernet4/34

506 001b.4f5b.ef2f dynamic ip,ipx,assigned,other GigabitEthernet2/26

506 001b.4f5b.ef31 dynamic ip,ipx,assigned,other GigabitEthernet3/5

506 001b.4f5b.ef88 dynamic ip,ipx,assigned,other GigabitEthernet2/17

506 001b.4f5b.efb6 dynamic ip,ipx,assigned,other GigabitEthernet2/23

506 001b.4f5b.f0fb dynamic ip,ipx,assigned,other GigabitEthernet3/6

506 001b.4f5b.f961 dynamic ip,ipx,assigned,other GigabitEthernet3/47

506 001b.4f5b.f9ec dynamic ip,ipx,assigned,other GigabitEthernet5/10

506 001b.4f5b.faac dynamic ip,ipx,assigned,other GigabitEthernet2/6

506 001b.4f5b.fac9 dynamic ip,ipx,assigned,other GigabitEthernet4/40

506 001b.4f5b.fb3f dynamic ip,ipx,assigned,other GigabitEthernet4/30

506 001b.4f5b.fb47 dynamic ip,ipx,assigned,other GigabitEthernet5/36

506 001b.4f5b.fde8 dynamic ip,ipx,assigned,other GigabitEthernet3/17

506 001b.4f5b.fe1e dynamic ip,ipx,assigned,other GigabitEthernet4/42

506 001b.4f5b.fe2b dynamic ip,ipx,assigned,other GigabitEthernet2/24

506 001b.4f5b.fec9 dynamic ip,ipx,assigned,other GigabitEthernet3/9

506 001b.4f5c.001e dynamic ip,ipx,assigned,other GigabitEthernet3/48

506 001b.4f5c.0058 dynamic ip,ipx,assigned,other GigabitEthernet2/28

506 001b.4f5c.008a dynamic ip,ipx,assigned,other GigabitEthernet2/30

506 001b.4f5c.1c5d dynamic ip,ipx,assigned,other GigabitEthernet5/6

506 001b.4f5d.297d dynamic ip,ipx,assigned,other GigabitEthernet3/25

506 001b.4f5d.2ae7 dynamic ip,ipx,assigned,other FastEthernet6/10

506 001b.4f5d.4318 dynamic ip,ipx,assigned,other FastEthernet6/19

506 001b.4f5d.46a9 dynamic ip,ipx,assigned,other FastEthernet6/8

506 001b.4f5d.4800 dynamic ip,ipx,assigned,other GigabitEthernet3/23

506 001b.4f5d.4ded dynamic ip,ipx,assigned,other FastEthernet6/45

506 001b.4f6f.132d dynamic ip,ipx,assigned,other GigabitEthernet3/20

506 10cd.ae63.edf9 dynamic ip,ipx,assigned,other GigabitEthernet2/13

506 10cd.ae63.ee5d dynamic ip,ipx,assigned,other GigabitEthernet2/9

506 1461.2ffe.42a6 dynamic ip,ipx,assigned,other GigabitEthernet5/24

506 1461.2ffe.42e6 dynamic ip,ipx,assigned,other GigabitEthernet4/21

506 2893.fea2.b2c8 dynamic ip,ipx,assigned,other GigabitEthernet4/8

506 2893.fea2.e59b dynamic ip,ipx,assigned,other GigabitEthernet5/14

506 2893.fea2.e5f3 dynamic ip,ipx,assigned,other GigabitEthernet5/2

506 2cf4.c54b.05e2 dynamic ip,ipx,assigned,other GigabitEthernet5/22

506 2cf4.c54c.eb97 dynamic ip,ipx,assigned,other FastEthernet6/4

506 2cf4.c54e.6631 dynamic ip,ipx,assigned,other GigabitEthernet4/39

506 2cf4.c54e.688a dynamic ip,ipx,assigned,other FastEthernet6/31

506 3cb1.5b4b.a281 dynamic ip,ipx,assigned,other GigabitEthernet2/5

506 50cd.22b7.e5c0 dynamic ip,ipx,assigned,other GigabitEthernet5/31

506 7081.0555.a77f static ip,ipx,assigned,other Switch

506 b4b0.1780.a74f dynamic ip,ipx,assigned,other GigabitEthernet4/22

506 b4b0.1797.64ee dynamic ip,ipx,assigned,other GigabitEthernet2/3

506 b4b0.1798.0f60 dynamic ip,ipx,assigned,other GigabitEthernet4/44

Gi1/3 0025.b4ce.a800 dynamic ip,ipx,assigned,other GigabitEthernet1/3

Gi1/3 7081.0555.a77f static ip,ipx,assigned,other Switch

Gi1/5 0026.0a26.9a00 dynamic ip,ipx,assigned,other GigabitEthernet1/5

Gi1/5 7081.0555.a77f static ip,ipx,assigned,other Switch

Multicast Entries
vlan mac address type ports
---------+---------------+-------+--------------------------------------------
1 0100.0ccc.ccce system Gi1/6
1 ffff.ffff.ffff system Gi1/6
60 ffff.ffff.ffff system Gi2/1,Gi2/3,Gi2/5,Gi2/6,Gi2/8,Gi2/9,Gi2/10
Gi2/11,Gi2/12,Gi2/13,Gi2/14,Gi2/15,Gi2/17
Gi2/19,Gi2/20,Gi2/21,Gi2/23,Gi2/24,Gi2/25
Gi2/26,Gi2/28,Gi2/30,Gi2/32,Gi2/36,Gi2/39
Gi2/40,Gi2/42,Gi2/46,Gi3/2,Gi3/3,Gi3/4
Gi3/5,Gi3/6,Gi3/7,Gi3/9,Gi3/10,Gi3/11,Gi3/13
Gi3/15,Gi3/16,Gi3/17,Gi3/19,Gi3/20,Gi3/21
Gi3/23,Gi3/24,Gi3/25,Gi3/30,Gi3/32,Gi3/34
Gi3/39,Gi3/42,Gi3/43,Gi3/45,Gi3/46,Gi3/47
Gi3/48,Gi4/2,Gi4/4,Gi4/8,Gi4/9,Gi4/12,Gi4/13
Gi4/16,Gi4/17,Gi4/18,Gi4/21,Gi4/22,Gi4/23
Gi4/26,Gi4/30,Gi4/32,Gi4/34,Gi4/37,Gi4/38
Gi4/39,Gi4/40,Gi4/41,Gi4/43,Gi4/44,Gi4/47
Gi5/2,Gi5/3,Gi5/4,Gi5/6,Gi5/8,Gi5/10,Gi5/11
Gi5/12,Gi5/14,Gi5/16,Gi5/20,Gi5/22,Gi5/24
Gi5/27,Gi5/28,Gi5/29,Gi5/30,Gi5/31,Gi5/32
Gi5/36,Gi5/37,Gi5/38,Gi5/39,Gi5/41,Gi5/42
Gi5/43,Gi5/45,Gi5/47,Fa6/1,Fa6/4,Fa6/6
Fa6/8,Fa6/10,Fa6/15,Fa6/19,Fa6/24,Fa6/26
Fa6/31,Fa6/35,Fa6/40,Fa6/43,Fa6/44,Fa6/45
Fa6/46,Fa6/47,Fa6/48,Switch
170 ffff.ffff.ffff system Gi1/6,Switch
506 ffff.ffff.ffff system Gi2/1,Gi2/3,Gi2/5,Gi2/6,Gi2/8,Gi2/9,Gi2/10
Gi2/11,Gi2/12,Gi2/13,Gi2/14,Gi2/15,Gi2/17
Gi2/19,Gi2/20,Gi2/21,Gi2/23,Gi2/24,Gi2/25
Gi2/26,Gi2/28,Gi2/30,Gi2/32,Gi2/36,Gi2/39
Gi2/40,Gi2/42,Gi2/46,Gi3/2,Gi3/3,Gi3/4
Gi3/5,Gi3/6,Gi3/7,Gi3/9,Gi3/10,Gi3/11,Gi3/13
Gi3/15,Gi3/16,Gi3/17,Gi3/19,Gi3/20,Gi3/21
Gi3/23,Gi3/24,Gi3/25,Gi3/30,Gi3/32,Gi3/34
Gi3/39,Gi3/42,Gi3/43,Gi3/45,Gi3/46,Gi3/47
Gi3/48,Gi4/2,Gi4/4,Gi4/8,Gi4/9,Gi4/12,Gi4/13
Gi4/16,Gi4/17,Gi4/18,Gi4/21,Gi4/22,Gi4/23
Gi4/26,Gi4/30,Gi4/32,Gi4/34,Gi4/37,Gi4/38
Gi4/39,Gi4/40,Gi4/41,Gi4/42,Gi4/43,Gi4/44
Gi4/47,Gi5/2,Gi5/3,Gi5/4,Gi5/6,Gi5/8,Gi5/10
Gi5/11,Gi5/12,Gi5/14,Gi5/16,Gi5/20,Gi5/22
Gi5/24,Gi5/27,Gi5/28,Gi5/29,Gi5/30,Gi5/31
Gi5/32,Gi5/36,Gi5/37,Gi5/38,Gi5/39,Gi5/41
Gi5/42,Gi5/43,Gi5/45,Gi5/47,Fa6/1,Fa6/4
Fa6/6,Fa6/8,Fa6/10,Fa6/15,Fa6/19,Fa6/24
Fa6/26,Fa6/31,Fa6/35,Fa6/40,Fa6/43,Fa6/44
Fa6/45,Fa6/46,Fa6/47,Fa6/48,Switch
Gi1/3 ffff.ffff.ffff system Gi1/3,Switch
Gi1/5 ffff.ffff.ffff system Gi1/5,Switch

```
Traceback (most recent call last):
File "C:\Users\dhines3\AppData\Local\Programs\Python\Python35-32\Learning\Napalm\pull_mac_table.py", line 15, in 
pprint(device.get_mac_address_table())
File "C:\Users\dhines3\AppData\Local\Programs\Python\Python35-32\lib\site-packages\napalm_ios\ios.py", line 1594, in get_mac_address_table
raise ValueError("Unexpected output from: {}".format(repr(line)))
ValueError: Unexpected output from: 'Gi1/3 0025.b4ce.a800 dynamic ip,ipx,assigned,other GigabitEthernet1/3'
```

---

Issue moved from https://github.com/napalm-automation/napalm-ios/issues/164

**Comment by bbmin7b5** [comment]
I just ran into this issue myself. Is there a fix for the regex?
