### ISSUE TITLE
Implement `get_bgp_neighbors_detail`

### ISSUE THREAD

**Issue by mirceaulinic** [napalm-automation/napalm#465]
For framework consistency, this seems to be one of the most used methods (at least on Junos and XR).

**Comment by nickethier** [comment]
@mirceaulinic I'll take this one, you can assign me.

**Comment by mirceaulinic** [comment]
Hi @nickethier. I'm sorry I missed your comment, thankfully someone asked about this so I just saw it. Unfortunately, I cannot assign issues but to folks that are part of the napalm-automation organisation. But please feel free to implement it, and submit a PR once you have anything ready. Thanks!

**Comment by nickethier** [comment]
Started work here: https://github.com/nickethier/napalm/tree/ios/get_bgp_neighbors_detail

**Comment by darylturner** [comment]
Hi @nickethier, I needed this for a quick audit project so I ported your implementation to a custom_napalm driver and it works great. Looking forward to having this by default.
