### ISSUE TITLE
EOS: Empty serial number from facts on vEOS

### ISSUE THREAD

**Issue by Ragsboss** [napalm-automation/napalm#484]
### Description of Issue/Question
On vEOS, get_facts is returning empty serial number.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
[X] Yes
[ ] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
rags@Raghavendras-MacBook-Pro ~/src $ pip freeze | grep napalm
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
napalm==1.2.0
napalm-base==0.25.0
napalm-eos==0.6.1
napalm-fortios==0.4.0
napalm-ios==0.8.1
napalm-iosxr==0.5.6
napalm-junos==0.12.1
napalm-nxos==0.7.1
napalm-panos==0.4.0
napalm-pluribus==0.5.1
napalm-ros==0.2.2
napalm-vyos==0.1.3
```

### Network device software version
(Paste verbatim output from `show version` (or equivalent on your platform) between quotes below)

```
localhost(config)#show version
Arista vEOS
Hardware version:    
Serial number:       
System MAC address:  5254.00dc.d547

Software image version: 4.16.6M
Architecture:           i386
Internal build version: 4.16.6M-3205780.4166M
Internal build ID:      e796e94c-ba3b-4355-afcf-ef0abfbfaee3

Uptime:                 30 weeks, 3 days, 0 hours and 13 minutes
Total memory:           3893820 kB
Free memory:            143996 kB

localhost(config)#

```

### Steps to Reproduce the Issue

```
>>> from napalm import get_network_driver
>>> driver = get_network_driver('eos')
>>> d = driver('172.20.159.9', 'admin', 'admin')
>>> d.open()
>>> d.get_facts()
{u'os_version': u'4.16.6M-3205780.4166M', u'uptime': 18401696, u'interface_list': [u'Ethernet1', u'Ethernet2', u'Ethernet3', u'Ethernet4', u'Ethernet5', u'Ethernet6', u'Ethernet7', u'Loopback0', u'Management1', u'Port-Channel3'], u'vendor': u'Arista', u'serial_number': u'', u'model': u'vEOS', u'hostname': u'localhost', u'fqdn': u'localhost.dc1.apstra.com'}
```

I suggest we could take the management interface MAC address as serial number in this case.

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
NA
```

### Trace captured

```
Please, reproduce the issue with the cli tool in debug mode and paste the entire execution.

https://napalm.readthedocs.io/en/latest/cli.html
```

**Comment by dbarrosop** [comment]
From your own output:

```
Serial number:       
```

So behavior is correct. We can't return a serial number if there is none.

Closing issue, feel free to reopen if this response doesn't address your issue.

**Comment by Ragsboss** [comment]
From the perspective of NAPALM north bound consumer, this is a bug. I'm using NAPALM as a common abstraction layer to communicate with various network devices and NAPALM is not giving me a critical piece of info (i.e., reliable 'identity') for devices under management.

I understand your perspective that it's a bug in vEOS. In that vein, I'm trying to ping the vEOS guys. Perhaps, in their perspective, there is no hardware and hence there is no serial number. Let's see.

Assuming everyone sticks to their perspective (as in, vEOS doesn't change or even if they do, there will be vEOS versions with empty serial numbers), this has to be worked around at some layer. I was hoping NAPALM EOS driver is a good place for such logic, so it doesn't have to be repeated in every application built on top of NAPALM. What do you think?

**Comment by ktbyers** [comment]
I agree with @dbarrosop here. The device does not have a serial number so we are not returning one (nor are we making up an alternate identity).

If you want to make a broader abstraction, i.e. identity, you are free to create one. NAPALM returns the mac-address-table so if you want that for identity (you can obtain that). Or you could generate a custom identity in some way.
