### ISSUE TITLE
Add support for Cumulus devices

### ISSUE THREAD

**Issue by Ragsboss** [napalm-automation/napalm#486]
### Description of Issue/Question
https://cumulusnetworks.com is quite common with whitebox vendors and has a huge list of supported vendors (see https://cumulusnetworks.com/products/hardware-compatibility-list/). It would be very helpful for NAPALM's common device layer (as depicted in http://napalm.readthedocs.io/en/latest/support/) to support Cumulus devices.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
[X] Yes
[ ] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
napalm==1.2.0
napalm-base==0.25.0
napalm-eos==0.6.1
napalm-fortios==0.4.0
napalm-ios==0.8.1
napalm-iosxr==0.5.6
napalm-junos==0.12.1
napalm-nxos==0.7.1
napalm-panos==0.4.0
napalm-pluribus==0.5.1
napalm-ros==0.2.2
napalm-vyos==0.1.3
```

### Network device software version
Cumulus 3.4

### Steps to Reproduce the Issue
N/A

### Error Traceback
N/A

### Trace captured
N/A

**Comment by dbarrosop** [comment]
Regarding this, there is some basic support already but hasn't officially been announced as there is actually nobody maintaining it. If this is something you'd be willing to maintain yourself let us know. We will try to contact the original contributors but we as it stands now we won't be officially supporting it ourselves as our resources are limited.

**Comment by dbarrosop** [comment]
Closing this issue as we are discussing onwership here:

https://github.com/napalm-automation/napalm/issues/486

Feel free to reopen/comment if you have any question or corcern.
