### ISSUE TITLE
Add MTU to interfaces coming from get_interfaces

### ISSUE THREAD

**Issue by Ragsboss** [napalm-automation/napalm#490]
### Description of Issue/Question
MTU is becoming an important piece of information on interfaces especially with abundance of overlays these days, which is putting some specific requirements on MTU on the underlay. I see that this is not part of the interface model documented to be output from `get_interfaces` method. This issue is an enhancement request to extend the model to include MTU and all the drivers to start fetching MTU. In most cases, the commands drivers are using already have MTU in the output.

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
[X] Yes
[ ] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
napalm==1.2.0
napalm-base==0.25.0
napalm-eos==0.6.1
napalm-fortios==0.4.0
napalm-ios==0.8.1
napalm-iosxr==0.5.6
napalm-junos==0.12.1
napalm-nxos==0.7.1
napalm-panos==0.4.0
napalm-pluribus==0.5.1
napalm-ros==0.2.2
napalm-vyos==0.1.3
```

### Network device software version
N/A

### Steps to Reproduce the Issue
N/A

### Error Traceback
N/A

### Trace captured
N/A

**Comment by dbarrosop** [comment]
Yeah, I think it makes sense. We should probably add it to the output of `get_interfaces`. @mirceaulinic @ktbyers thoughts?

@Ragsboss is this something you'd want to work on?

**Comment by targuan** [comment]
I'm working on the implementation for junos driver. I don't have any junos device, I'm working with the test output.
Some logical interfaces don't report the mtu (for instance ge-0/0/0.0 in [this test cast](https://github.com/napalm-automation/napalm/blob/develop/test/junos/mocked_data/test_get_interfaces/normal/get-interface-information.xml#L209).
 Anybody know how this should be reported by the driver ? With a special value ? Inherit the value from the physical interface ? Inherit the value from the physical interface with a delta to report the encapsulation ?

**Comment by afourmy** [comment]
@targuan it is already done for junos, see https://github.com/napalm-automation/napalm/compare/get_interfaces_mtu3

**Comment by targuan** [comment]
@afourmy the test of get_interfaces has not been updated with the mtu values and some interfaces where added inbetween in the test set and are not handled.

**Comment by ktbyers** [comment]
Should be implemented here:

https://github.com/napalm-automation/napalm/pull/940
