### ISSUE TITLE
Junos: missing PR after reunification

### ISSUE THREAD

**Issue by ckishimo** [napalm-automation/napalm#500]
There may be some PR that were merged in `napalm-junos` that are missing in the `junos` driver after the reunification. In particular https://github.com/napalm-automation/napalm-junos/pull/216, there may be others... Thanks!

**Comment by dbarrosop** [comment]
That sucks, I wonder how that happened with the code freeze and all :S Would you mind reopening the PR against this repo?

Thanks and sorry :(

**Comment by ktbyers** [comment]
I talked to @mirceaulinic about this...I think some of the PRs that he released into napalm-junos late in the reunification process weren't resubmitted to the reunification branch (i.e. they occurred after you did the reunification so he needs to resubmit them manually).

I think he will follow up on this and resubmit them.
