### ISSUE TITLE
Panos driver missing after unification

### ISSUE THREAD

**Issue by alcidessd37** [napalm-automation/napalm#501]
After upgrading to 2.0.0 napalm-panos and its dependencies are not installed with napalm.

**Comment by dbarrosop** [comment]
Yeah, "community" drivers haven't been merged into the core and won't be. Community drivers will still be kept separated, under a different org and maintained by the community.

You can find panos here:

https://github.com/napalm-automation-community/napalm-panos

I suggest you to open an issue there asking them to migrate to napalm 2.0.0.

I am closing this issue but feel free to reopen or comment if you have any questions/concerns.
