### ISSUE TITLE
get_isis_neighbors

### ISSUE THREAD

**Issue by afourmy** [napalm-automation/napalm#525]
Do you think it would make sense to have a get_isis_neighbors as a new getter ? The format could be something like: (list of dict like get_ipv6_neighbors format)

```
        [
            {
                'interface' : 'Gi0/1/1.1501',
                'ip'        : '192.168.244.17',
                'state'     : 'UP',
                'hostname'  : 'test0',
                'type'      : 'L2'
            },
            {
                'interface' : 'Te2/0/0.1501',
                'ip'        : '192.168.244.189',
                'state'     : 'UP',
                'hostname'  : 'test1',
                'type'      : 'L2'
            }
        ]
```

Any suggestions to change the format is welcome.
I would need it for my work so I can implement it for ios to begin with, then maybe junos too.

**Comment by mirceaulinic** [comment]
Hi @afourmy - In my option it would be nice to have that. Can you propose a complete structure that you think it would be suitable and then we start to discuss?
I think at least the following fields would be interesting too:

- System ID
- Uptime
- Area address

Others?

**Comment by afourmy** [comment]
Hello @mirceaulinic OK for these three fields. (no hostname needed then as the system ID and hostname should be more or less the same). We can also add the SNPA if you think it's useful.

So far we would have something like:

```
[
    {
        'interface'   : 'Gi0/1/1.1501',
        'ip'          : '192.168.244.17',
        'state'       : 'UP',
        'system_id'   : 'test0',
        'type'        : 'L2',
        'area_address : '...',
        'uptime'      : '...'
        'snpa'        : 'some mac address usually'
    },
    {
        'interface'   : 'Te2/0/0.1501',
        'ip'          : '192.168.244.189',
        'state'       : 'UP',
        'system-id'   : 'test1',
        'type'        : 'L2',
        'area_address : '...',
        'uptime'      : '...'
        'snpa'        : 'some mac address usually'
    }
]
```

**Comment by dbarrosop** [comment]
Is there any openconfig model we can just copy?

**Comment by jamesboswell** [comment]
Perhaps this should be `get_isis_adjacency`?   That's the term used in IOS-XR and JUNOS for sure, both are `show isis adjacency` on CLI.

Also there is an openconfig model  https://github.com/openconfig/public/blob/master/release/models/isis/openconfig-isis.yang#L1450

I think this thread might be relevant here https://github.com/robshakir/pyangbind/issues/135

I'm poking around on this,  I've got some learning to do re: generating the napalm-yang model.  @dbarrosop if you have any pointers, I'd be glad to take a swing at this

**Comment by mirceaulinic** [comment]
I don't think anyone is working on this. Otherwise, please comment / open a separate issue, or even submit a PR (with the mention that it should provide the implementation of at least 3 core platforms).
