### ISSUE TITLE
[feature request]: get_acl Method

### ISSUE THREAD

**Issue by sincerywaing** [napalm-automation/napalm#546]
Just wondering if we can implement a method to get acl configuration on devices - 

def get_acl(self, name=''):
    """
        Returns a dict of list of dicts containing acl configuration.
        Each inner list contains these fields
            * protocol (string)
            * src_ip (string)
            * src_mask (string)
            * src_port (string)
            * dest_ip (string)
            * dest_mask (string)
            * dest_port (string)
        Example::
            {
                'name': u'acl_wan_in',
                    [ 
                        {'protocol': 'ip'
                         'src_ip': '192.168.1.0'
                         'src_mask': '255.255.255.0' or '24'
                         'src_port': '0-65535'
                         'dest_ip': '192.168.2.0'
                         'dest_mask': '255.255.255.0' or '24'
                         'dest_port': '22' },
                        {'protocol': 'tcp'
                         'src_ip': '192.168.5.0'
                         'src_mask': '255.255.255.0' or '24'
                         'src_port': '0-65535'
                         'dest_ip': '192.168.6.0'
                         'dest_mask': '255.255.255.0' or '24'
                         'dest_port': '80' },
                     ]
              }
"""

Maybe there are more considerations to it - just thinking if we can implement something similar to it.

**Comment by dbarrosop** [comment]
There is one already: https://github.com/napalm-automation/napalm/blob/develop/napalm/base/base.py#L1500

Closing the ticket, feel free to reopen if you have any concerns or the existing getter doesn't cover something.

**Comment by sincerywaing** [comment]
@dbarrosop but it does not seem to be implemented in any driver. is there any intention to have one at least in ios and junos?
