### ISSUE TITLE
VLAN Getter for NAPALM

### ISSUE THREAD

**Issue by mattschwen** [napalm-automation/napalm#571]
I propose that we implement a VLAN getter for NAPALM using the following model:

{
    "vlan_id": 300,
    "vlan_name": "cool_vlan",
    "vlan_state": "active",
    "vlan_int": ["port-channel1,port-channel101-117,ethernet1/1]
}

If someone wants to open a branch with the initial structure in place, I can assist in work on a PR for Cisco NXOS, Cisco NXOS-SSH, Cisco NXOS-SSH (XML), Cisco IOS, and JUNOS.

**Comment by mattschwen** [comment]
For NXOS API, we have to use XML vs JSON. The reason being is a bug that does not include all interfaces associated with a particular VLAN. This is only fixed in the very latest code in Cisco. Parsing XML vs JSON for NXOS API is a much safer way to get valid data as Cisco does not do a good job of converting XML to JSON.

**Comment by mattschwen** [comment]
NXAPI Function for show vlan:

```python
def show_commands(url, un, pw, command):
"""XML for NXAPI show vlan"""
  myheaders = {'content-type': 'application/xml'}

  payload = """<?xml version="1.0"?>
    <ins_api>
      <version>1.0</version>
      <type>cli_show</type>
      <chunk>0</chunk>
      <sid>sid</sid>
      <input>show vlan</input>
      <output_format>xml</output_format>
    </ins_api>"""

  response = requests.post(url, data=payload, headers=myheaders, auth=(un, pw))

  vlan_data_xml = xmltodict.parse(response.text, xml_attribs=True)

  return vlan_data_xml
```

**Comment by ktbyers** [comment]
@mattschwen We need to complete our NXOS XML work and submit a PR on that before we do this.

The next steps for the XML work our to get the testing framework done. Also we need to get the XML working with NX-API for get_mac_address_table using the same parsing that we used for SSH `| xml`.

**Comment by dbarrosop** [comment]
Just for reference; https://github.com/napalm-automation/napalm-base/issues/252#issuecomment-305963170

**Comment by ktbyers** [comment]
I don't think we are doing any work on this and I am generally opposed to new getters. I am going to close this for now. We can reopen this discussion if someone is actively working on this task.
