### ISSUE TITLE
[new feature]: get_acl method

### ISSUE THREAD

**Issue by sincerywaing** [napalm-automation/napalm#577]
looking to implement something similar to ‘get_firewall_policies’ but better than that.

**Comment by dbarrosop** [comment]
Do you have more details or a proposal regarding this?

**Comment by sincerywaing** [comment]
@dbarrosop

in junos it's equal to 
```        <get-firewall-policies>
                <policy-name>xxx</policy-name>
                <detail/>
        </get-firewall-policies>
```

in IOS it's equal to `show run | in access-list <policy-name>`

some additional details - 

we don't need put the specific `sequence` into consideration, just use list's position to mark that.

we only put the most important src/dst/port/protocol/action into `mandatory fields`, and leave rest as `driver specific fields`, thus to keep consistency.

returns:
```
    {
    policy-name: xxx
        [
        {
        source-address: [string/ipaddress], if we use ipaddress, we can combine address and prefix
        source-prefix: [string]
        source-port: [list]
        destination-address: [string/ipaddress], if we use ipaddress, we can combine address and prefix
        destination-prefix: [string]
        destination-port: [list]
        protocol: [string]
        action: [string]
        other:
            {
            # the most important stuff are listed above, we put those less important here:
            inactivity-timeout:
            log: true/false
            ALG: 
            ...
            }
        },
        {
        source-address:
        source-prefix:
        source-port:
        destination-address:
        destination-prefix
        destination-port:
        protocol:
        other:
            {
            # the most important stuff are listed above, we put those less important here:
            inactivity-timeout:
            log: true/false
            ALG: 
            ...
            }
        },
        ...
        ]
    }
```

**Comment by dbarrosop** [comment]
> we don't need put the specific sequence into consideration, just use list's position to mark that.

We need sequence number or this info can't be used to regenerate the configuration. 

> we only put the most important src/dst/port/protocol/action into mandatory fields, and leave rest as driver specific fields, thus to keep consistency.

That sounds sane to me. However, I'd differentiate between `protocol` (ipv4, ipv6, ...) and `transport_protocol` (tcp/udp).

@mirceaulinic I think you were planning to look into this, if you are still planning to do that, would you mind checking this issue?

**Comment by ktbyers** [comment]
Whoever implements this needs to make sure they at least consider extended, standard, and named ACLs in Cisco land.

I would also say at a minimum that any data structure created needs to consider all five of the core platforms.

I am against implementing this as I think the parsing on Cisco IOS and NXOS is going to be a nightmare. I also think this data structure is going to be hard to implement correctly and hard to maintain (even outside of the screen-scraping mess).

**Comment by sincerywaing** [comment]
@ktbyers Yeah. However from what I see the acl implementation in Cisco land is near-structural, or is easier to parse than `show environment` or `show lldp nei`...  its tricky part might be the fields are not always static, people may omit wild cards or using other words to replace them.

**Comment by mirceaulinic** [comment]
I was about to suggest a similar structure, and in addition to what @sincerywaing proposed, I think the following cross-platform fields would be useful too:

- policer
- icmp_type
- routing_instance
- next_ip?
- qos
- option (e.g. `tcp-established` etc.)
- source_interface
- destination_interface

Not sure about the last two however. Of course there can be many others, which we can either add later, or include in the `others` even though they might not necessarily be platform-specific.

A major difference I would like to discuss is having `terms`, as a list. But given that only Junos (AFAIK has this), maybe it makes more sense to have it into the `others`, e.g.,

```python
'others': {
    'term': 'my-slick-term`
}
```
 
But at the end of the day we can somehow look at the Cisco-ish platforms' ACL sequence as a term basically, e.g.,

- Cisco-ish platforms

```python
{
    'my-policy': {
        'terms': {
            '10': [ ... list of options for this sequence ...]
    }
}
```

- Junos (and maybe others):

```python
{
    'my-policy': {
        'terms': {
            'my-slick-term': [ ... list of options for this term ...]
    }
}
```

What do you think?

**Comment by mirceaulinic** [comment]
> That sounds sane to me. However, I'd differentiate between protocol (ipv4, ipv6, ...) and transport_protocol (tcp/udp).

I would also argue about this one - I'm not convinced we should have subclasses, as this would need us to discuss every time from now on where shall we include protocol X; for example, it is not immediately obvious to me whether `vrrp` would belong to `transport_protocol` or the other one. I would suggest to keep things simple. Also, this should be a list, otherwise it won't work cross platform. Same for all the others (source address, port, etc.).

**Comment by sincerywaing** [comment]
@mirceaulinic shall we first make an agreement on the overall structure and see how we can proceed?

**Comment by mirceaulinic** [comment]
Yes, please let's discuss first and then we can start implementing the tests with the expected structure.

**Comment by dbarrosop** [comment]
I personally think this one should be "extensible". For instance, I'd rather start with something like:

```
position: position of the ace in the ACL
protocol: ip, ipv6, arp, etc...
protocol_options: if needed, TBD as needed
source: whatever the source may be
source_options: if needed, TBD as needed
source_interface:
destination: whatever the destination may be
destination_options: if needed, TBD as needed
destination_interface:
transport_protocol: l4 protocol
transport_options: if needed, TBD as needed
```

So, for instance, TCP would have as transport_options source_port, destination_port, flags (SYN, ACK), established... UDP would have only source and destination ports, ICMP would have type and code and other protocols may have other options or just a subset of them.

For QoS we should do something similar but I refuse to spend brain cycles thinking about anything related to QoS so I would leave it to other people :P

An alternative is to have different data structures depending on the ACE and discuss them as needed. For instance:

```
---
type: tcp
source:
source_port:
destination:
destination_port:
is_established:
flags
---
type: udp
source:
source_port:
destination:
destination_port:
---
type: icmp
source:
destination:
type:
code:
```

In any case, if we do a flat structure this is going to grow into a million heads hydra that is going to be pretty much useless or unnecessarily complex to use (from a user perspective).

**Comment by ktbyers** [comment]
I am going to close this...per previous agreement all new getters need to be implemented in napalm-yang.
