### ISSUE TITLE
local variable 'system_temp' referenced before assignment - get_environment, napalm-ios 0.8.1

### ISSUE THREAD

**Issue by slinderud** [napalm-automation/napalm#582]
Using netbox and trying to retrieve data via napalm.
Getting the error "local variable 'system_temp' referenced before assignment"

kcelenza from slack suggested this could be related to different output from sh env temp status.
Looks like he's correct:

 #sh environment temperature status
Inlet Temperature Value: 25 Degree Celsius
Temperature State: GREEN
Yellow Threshold : 46 Degree Celsius
Red Threshold    : 56 Degree Celsius

Hotspot Temperature Value: 38 Degree Celsius
Temperature State: GREEN
Yellow Threshold : 105 Degree Celsius
Red Threshold    : 125 Degree Celsius

This output is from a 3850 running IOS-XE 16.06

expected:

https://github.com/napalm-automation/napalm/blob/develop/test/ios/mocked_data/test_get_environment/normal/show_env_temperature_status.txt

**Comment by cspeidel** [comment]
Can you provide output for the following commands in case there are other quirks in get_environment:

show memory statistics
show proc cpu

**Comment by slinderud** [comment]
Sure.

https://pastebin.com/0LsHHsuQ

**Comment by ktbyers** [comment]
Okay, someone will have to do a PR to create a fix...to handle the output variations in the command.
