### ISSUE TITLE
Unambiguous LICENSE

### ISSUE THREAD

**Issue by mrstell** [napalm-automation/napalm#587]
The project lacks clear license.
I see APACHE LICENSE in some source files, but no evidence in documentation or anywhere else that whole project could be distributed under this license.
Please, consider also adding license to PyPI: https://pypi.python.org/pypi/napalm/2.2.0

**Comment by dbarrosop** [comment]
You are right, me "lost" during the reunification of the repos. Adding it back.

https://github.com/napalm-automation/napalm/pull/588

**Comment by ktbyers** [comment]
License PR was merged.
