### ISSUE TITLE
Drivers reports free memory instead of memory installed

### ISSUE THREAD

**Issue by targuan** [napalm-automation/napalm#593]
In base, the documentation states that ```available_ram``` is the total amount of RAM installed in the device.
IOS and EOS driver parse the output of show memory statistics but return the sum on the column Free instead of the column Total.

Should it be fixed in the drivers or in the documentation of base ?

**Comment by mirceaulinic** [comment]
Hi @targuan - I think we should fix this in the drivers. I'll also ask @ktbyers for more opinions.

**Comment by ktbyers** [comment]
Yes, this is a bug...so we should fix it.

**Comment by ktbyers** [comment]
Fixed here:

https://github.com/napalm-automation/napalm/pull/605
