### ISSUE TITLE
windows live environment all outputs { }

### ISSUE THREAD

**Issue by vampep** [napalm-automation/napalm#606]
I have tested my script which is simple compare_config script in gns3 and it works fine, so it's using unix and test routers with ver 15.6 ios.

When i move to my windows pc and a live environment my script is unable to get any output which causes an early error when trying to write to directory. When i test it in the interpreter and i do anything like device.get_interfaces() the output is a blank dictionary:  { }. If i do a device.is_alive() it comes up as true. I can't for the life of me figure out where the problem is since i do the same on the GNS3 environment and it works. 

PS.
Is there a way for me to print the current terminal output so i can see what the program has been doing and what it is seeing?

**Comment by ktbyers** [comment]
Can you post your code and the output from your code?

**Comment by vampep** [comment]
@ktbyers below is just a quick test so you can see the blank result from get_interfaces. this is my live environment so i just x.x.x.x'd the ip address and generic'd the username/password but i connect just fine (I can see the additional user if I ssh into the router myself and do "show users") and you can see its "alive". Again, if tested in my gns3 environment on Unix i have no issues. The only difference i'm realizing is this is python 3.6 and my gns3 is python2.7. I'll be trying that next and will post if that was the problem. 

U:\>python
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import napalm import get_network_driver
  File "<stdin>", line 1
    import napalm import get_network_driver
                       ^
SyntaxError: invalid syntax
>>> from napalm import get_network_driver
>>> driver = get_network_driver("ios")
>>> optional_args = {'dest_file_system': 'flash0:'}
>>> ERI = driver('x.x.x.x', 'user', 'password', 10, optional_args=optional_args)
>>> ERI.open()
>>> ERI.is_alive()
{'is_alive': True}
>>> ERI.get_interfaces()
{}
>>> ERI.load_merge_candidate(config='access-list 23 permit 10.2.5.0 0.0.0.255')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python3\lib\site-packages\napalm\ios\ios.py", line 273, in load_merge_candidate
    file_system=self.dest_file_system)
  File "C:\python3\lib\site-packages\napalm\ios\ios.py", line 233, in _load_candidate_wrapper
    file_system=file_system)
  File "C:\python3\lib\site-packages\napalm\ios\ios.py", line 485, in _scp_file
    file_system=file_system, TransferClass=FileTransfer)
  File "C:\python3\lib\site-packages\napalm\ios\ios.py", line 516, in _xfer_file
    if transfer.check_file_exists() and transfer.compare_md5():
  File "C:\python3\lib\site-packages\netmiko\scp_handler.py", line 128, in check_file_exists
    raise ValueError("Unexpected output from check_file_exists")
ValueError: Unexpected output from check_file_exists

**Comment by vampep** [comment]
same problem with 2.7. i feel like i'm missing some module (i'm a newb) or something. I was having trouble getting driver ('ios') to work until i realize i needed "terminal" installed, didn't auto download with netmiko or napalm. I'm sure i'm missing something else, which i didn't have to do on my unix vm.

**Comment by vampep** [comment]
i went through the required txt but i have everything there. but like i said, when i just installed netmiko and napalm for some reason i was missing terminal and that caused an error loading the driver for ios. Now i'm getting this problem but haven't been able to figure out why. Any idea?

**Comment by ktbyers** [comment]
@vampep I would focus on the `get_interfaces` failure right now and not the `merge_config` (as other things could go wrong there).

I recommend turning on additional logging and see if that gives you clues as to what is occurring:

https://github.com/ktbyers/netmiko/blob/develop/COMMON_ISSUES.md#enable-netmiko-logging-of-all-reads-and-writes-of-the-communications-channel

**Comment by vampep** [comment]
i agree with that assessment. i believe the blank output of get_interfaces (and everything else i try) is sending blank stuff to merge_config when it's looking for the flash memory and thats not normal and sends an error. I'll try the logging and see what happens.

**Comment by vampep** [comment]
There doesn't seem to be a problem. Might I ask how does the script collect the info to be shown? I know merging creates a file on the flash, is it trying to download something from the router? if so that might be the problem. if it's just reading it as a string, then idk. Attached is the logging output but i removed the interfaces that were shown since it is a live environment. 
[test.log](https://github.com/napalm-automation/napalm/files/1599624/test.log)

**Comment by ktbyers** [comment]
@vampep When you enable logging...Netmiko then logs all reads and writes of the SSH channel.

So are you getting a valid `get_interfaces` data structure back from your program then?

The two `show interfaces` are the first one when you write the channel and then the router echo's the command back on the CLI (and you read this back during a read operation). So it is just once and an echo of the command.

**Comment by vampep** [comment]
well the logging showed that it could see the router responded to the "show interfaces" but i still got a blank list as the output in the program.

**Comment by ktbyers** [comment]
What version of Netmiko are you using?

```
import netmiko
netmiko.__version__
```

Can you post the output of `show interface` for the first couple of interfaces?

**Comment by vampep** [comment]
sorry i fixed it. I started playing with netmiko and realized i was having the same problem. After testing all day i realized what the logging file was actually showing me. The command were taking to long to get to the router therefore the output was always showing as nothing, or just the router prompt. A search found you had someone complain about the same issue. You addressed it by adding a "global_delay_factor" which worked perfectly for me as well.

is there the same with napalm?

**Comment by dbarrosop** [comment]
It's documented here: http://napalm.readthedocs.io/en/latest/support/index.html#optional-arguments

**Comment by ktbyers** [comment]
@vampep were you using `send_command_timing` or `send_command`. It really shouldn't be showing nothing or just the prompt if you are using `send_command`; `send_command_timing` might do this (but you shouldn't normally be using `send_command_timing`).

I am going to close this as there doesn't appear to be any more actions to do here.
