### ISSUE TITLE
Unable to push napalm script to an Cisco IOU L3 device

### ISSUE THREAD

**Issue by sagarh9** [napalm-automation/napalm#612]
Hi Guys,

I'm trying to push the configurations to an IOU L3 cisco router through a python-napalm script and i'm getting the below error:

 Traceback (most recent call last):
  File "napalmcfg4.py", line 13, in <module>
    iosv.load_merge_candidate(filename='ACL1.cfg')
  File "/usr/local/lib/python2.7/dist-packages/napalm/ios/ios.py", line 271, in load_merge_candidate
    file_system=self.dest_file_system)
  File "/usr/local/lib/python2.7/dist-packages/napalm/ios/ios.py", line 241, in _load_candidate_wrapper
    file_system=file_system)
  File "/usr/local/lib/python2.7/dist-packages/napalm/ios/ios.py", line 483, in _scp_file
    file_system=file_system, TransferClass=FileTransfer)
  File "/usr/local/lib/python2.7/dist-packages/napalm/ios/ios.py", line 534, in _xfer_file
    return (False, '')
  File "/usr/local/lib/python2.7/dist-packages/netmiko/scp_handler.py", line 87, in __exit__
    raise exc_type(exc_value)
AttributeError: 'NoneType' object has no attribute 'group'

The script is as follows:
import json
from napalm import get_network_driver

device_list = ['192.168.122.72',
               '192.168.122.71'
			   ]

for ip_address in device_list:
	print ("Connecting to " + str(ip_address))
	driver = get_network_driver('ios')
	iosv = driver(ip_address, 'sagar', 'cisco')
	iosv.open()

	iosv.load_merge_candidate(filename='ACL1.cfg')

	diffs = iosv.compare_config()
	if len(diffs) > 0:
		print(diffs)
		iosv.commit_config()
	else:
		print('No ACL changes required.')
		iosv.discard_config()
	
	iosv.load_merge_candidate(filename='ospf1.cfg')
	
	diffs = iosv.compare_config()
	if len(diffs) > 0:
		print(diffs)
		iosv.commit_config()
	else:
		print('No OSPF changes required.')
		iosv.discard_config()
		
	iosv.close()

Please assist me in finding what's wrong with the script. The same script works well on cisco IOSvl2 switch.

Thanks,
Sagar Hiremath

**Comment by ktbyers** [comment]
It looks like it is failing on the secure copy to the device.

What does a `dir` on the device show?

**Comment by sagarh9** [comment]
Sorry, i was away from work for a while. Will let you know the output of 'dir' by EOD. But to clarify, i do not understand **AttributeError: 'NoneType' object has no attribute 'group'**. I haven't seen this error with IOSv devices.

**Comment by sagarh9** [comment]
root@NetworkAutomation-1:~# dir
ACL.cfg  ACL1.cfg  napalmcfg3.py  napalmcfg4.py  ospf1.cfg
root@NetworkAutomation-1:~#

This is what i see when i do a 'dir'. 

NOTE: I'm running this inside GNS3.

**Comment by ktbyers** [comment]
@sagarh9 No I was referring to `dir` on one of the network devices. 

For example, here is the output from an IOS router.

```
pynet-rtr1#dir
Directory of flash:/

    1  -rw-           9  Oct 17 2016 15:53:00 -07:00  ea2.txt
   73  -rw-          12   Sep 3 2016 12:21:24 -07:00  testx.txt
    2  -rw-        3331  Mar 17 2011 13:04:18 -07:00  cpconfig-8xx.cfg
    3  -rw-     2941440  Mar 17 2011 13:04:36 -07:00  cpexpress.tar
    4  -rw-        1038  Mar 17 2011 13:04:44 -07:00  home.shtml
    5  -rw-      115712  Mar 17 2011 13:04:52 -07:00  home.tar
...
```

**Comment by sagarh9** [comment]
Oops, sorry...

This is the info:
R1#dir
Directory of system:/

  758  drwx           0                    <no date>  cme
    2  -r--           0                    <no date>  default-running-config
    3  drwx           0                    <no date>  its
  105  dr-x           0                    <no date>  memory
    1  -rw-        1944                    <no date>  running-config
  104  dr-x           0                    <no date>  vfiles

No space information available

**Comment by ktbyers** [comment]
@sagarh9 NAPALM IOS for the configuration operation requires a file system that you can create a file on. 

So this probably won't work:

```
R1#dir
Directory of system:/

758 drwx 0 cme
2 -r-- 0 default-running-config
3 drwx 0 its
105 dr-x 0 memory
1 -rw- 1944 running-config
104 dr-x 0 vfiles

No space information available
```

Is there a way on the L3 IOU device to create a `flash:` file system. At the end it needs to look more like what you have for the L2 IOU device.

**Comment by sagarh9** [comment]
@ktbyers you're right. I replaced the IOUl3 with the IOSvl3 router which had the flash: file system and the script ran successfully.

'dir' output of the IOSvl3 device:
r1#dir
Directory of flash0:/
    1  drw-           0  Jan 30 2013 00:00:00 +00:00  boot
  264  drw-           0  Oct 14 2013 00:00:00 +00:00  config
  267  -rw-   143178592  Mar 22 2016 00:00:00 +00:00  vios-adventerprisek9-m
  268  -rw-      524288  Jan 15 2018 06:08:52 +00:00  nvram
  269  -rw-          79  Jan 15 2018 06:08:58 +00:00  e1000_bia.txt
  272  -rw-         119  Jan 15 2018 06:36:32 +00:00  merge_config.txt
  273  -rw-        3473  Jan 15 2018 06:36:50 +00:00  rollback_config.txt

2142715904 bytes total (1994395648 bytes free)

root@NetworkAutomation-1:~# python napalmcfg3.py
Accessing 192.168.122.71
+access-list 100 permit icmp any any
+access-list 100 permit tcp any any eq domain
+access-list 100 permit tcp any any eq www
+access-list 100 permit tcp any any eq 443
+router ospf 1
+ network 10.1.1.0 0.0.0.255 area 0
+ network 10.1.2.0 0.0.0.255 area 2
+ network 10.1.3.0 0.0.0.255 area 3

Thank you for your help!

Cheers,
Sagar Hiremath

**Comment by ktbyers** [comment]
It looks like there is no issue here. For IOS virtual devices to work; they must have some file system which NAPALM-IOS can SCP files to.

**Comment by shyarkhan** [comment]
hello everyone,

Can someone help me with IOSVl3 or  IOSvl2... ?

**Comment by ktbyers** [comment]
@shyarkhan If you run `dir` on the device, what does your device show?

You are also going to have to post your stack trace at a minimum.


Kirk

**Comment by shyarkhan** [comment]
@ktbyers  Dir shows nothing , i need VIOS as per above posts i have the same issue, but i dont know from where i can get VIOS free version.

**Comment by ktbyers** [comment]
napalm-ios requires a file system to transfer a file into for any of the configuration operations.

**Comment by phobozad** [comment]
On IOUL3 there is a writable filesystem under ```unix:/```

```
IOU1#dir unix:
Directory of unix:/

7733292  -rw-        1136   May 5 2020 23:29:36 +00:00  NETMAP
7733289  -rw-        1392   May 5 2020 23:29:48 +00:00  startup-config.cfg
7733291  -rw-         191   May 5 2020 23:29:36 +00:00  ubridge.log
7733293  -rw-       65536   May 5 2020 23:29:47 +00:00  nvram_00001

2147479552 bytes total (2147479552 bytes free)
IOU1#copy run unix:/running.txt
Destination filename [running.txt]?
1193 bytes copied in 0.129 secs (9248 bytes/sec)

IOU1#
```

Not sure what modifications would be required to leverage that.  It seems like its just doing a ```dir``` command and assuming that is a full list of writable filesystems.  ```dir all``` does report the ```unix:/``` filesystem

**Comment by ktbyers** [comment]
@phobozad What does `dir` by itself show (with no trailing filesystem specified)?

**Comment by ktbyers** [comment]
You can specify the file-system using optional_args, however. The argument is:

```python
self._dest_file_system = optional_args.get("dest_file_system", None)
```

So:

```python
optional_args = {
    dest_file_system = "unix:",
}
```

Then that needs to be passed in as an argument when creating the NAPALM object.

**Comment by phobozad** [comment]
```dir``` just shows the system: filesystem.

Thanks for the tip about manually passing that in.  I ran across that in the documentation as I was looking for something else following my post. 

Explicitly passing that is working correctly so that’s probably good enough given the unique nature of the platform in question.
