### ISSUE TITLE
On logical interface the "is_enabled" is FALSE with link down on Juniper

### ISSUE THREAD

**Issue by jemcek** [napalm-automation/napalm#651]
On Juniper MX, if the physical link is down, the "is_enabled" status for the logical interface is FALSE instead of TRUE:

servis@router1.re1> show configuration interfaces xe-2/2/5
description test;
mtu 9192;
unit 0 {
    family inet {
        mtu 9000;
        address 10.200.7.100/31;
    }
}

servis@router1.re1> show interfaces terse
xe-2/2/5                up    down
xe-2/2/5.0              up    down inet     10.200.7.100/31

But with the get facts, the result is:

 "xe-2/2/5": {
                    "description": "test",
                    "is_enabled": true,
                    "is_up": false,
                    "last_flapped": 68971.0,
                    "mac_address": "40:71:83:A2:81:A1",
                    "speed": 10000
                },
                "xe-2/2/5.0": {
                    "description": "",
                    "is_enabled": false,   <----- this should be TRUE
                    "is_up": false,
                    "last_flapped": 68971.0,
                    "mac_address": "40:71:83:A2:81:A1",
                    "speed": 10000
                },

**Comment by jemcek** [comment]
I have done some more research regarding this issue. Depending the admin/link state of logical interface the xml result on Junos is:

1) if the logical interface is admin up and link is up
show interface xe-2/2/5.0 | display xml
...
   <if-config-flags>
      <iff-up/>

2) if the logical interface is admin up but link is down
show interface xe-2/2/5.0 | display xml
...
   <if-config-flags>
      <iff-device-down/>

3) if the logical interface is admin down 
show interface xe-2/2/5.0 | display xml
...
   <if-config-flags>
      <iff-device-down/>
      <iff-down/>

So in short, if logical interface is/has:
admin up ----> 
admin down ---> <iff-down/> 
link up   ---> <iff-up/> 
link down. ---> <iff-device-down/> 

I don't know if this is some standard way how to describe the logical interface states, but it is strange anyway :)

Comparing the above return values with the code inside napalm/junos/utils/junos_views.yml, I would say that there is a mismatch:
junos_logical_iface_view:
  fields:
    is_up: { ../oper-status: True=up }
    is_enabled: { if-config-flags/iff-up: flag } 
...

It should be more something like:
    is_up: { if-config-flags/iff-up: flag } 
    is_up: {if-config-flags/iff-device-down: not flag} <---- however this does not work, don't know how to "invert" the flag??

I don't know is it worth bothering with this states, since Junos can change and everything will need to be updated again, but it is pretty silly right now if you want to check the states of your interfaces automatically in a simple way across different platforms. 

Testing was done on Junos: 16.1R1.7

**Comment by dbarrosop** [comment]
That's weird. At least older platforms had this:

```
<admin-status format="Enabled">up</admin-status>
<oper-status>down</oper-status>
```

Are you positive that has changed to something else? What is the output of the RPC call `get-interface-information`?

**Comment by jemcek** [comment]
The problem is only with logical interfaces (for example xe-2/2/5.0 or xe-2/2/5 unit 0)), the physical interfaces behave like you described.

**Comment by jemcek** [comment]
The solution for 'is_up' is like you said pretty clear, but I think the 'is_enabled' is more complex. I don't know if I understood you correctly but what you proposed is more a check if this interface exists at all (was created) or not. But I think that 'is_enabled' should indicate that an interface that was created and exists, is disabled ('set interfaces xe-2/2/5 unit 0 disable'). So for example with the following configuration, interface xe-2/2/5.0 (unit 0) exists but is disabled:

test@router2.re1> show configuration interfaces xe-2/2/5
mtu 9192;
unit 0 {
    disable;
    family inet {
        mtu 9000;
        address 10.200.7.100/31;
    }
}

show interface terse shows this as:
xe-2/2/5                up    down
xe-2/2/5.0              down  down inet     10.200.7.100/31

and also the xml output includes information about this interface:
mihaj@rarnes2.re1> show interfaces xe-2/2/5.0 | display xml
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/16.1R1/junos">
    <interface-information xmlns="http://xml.juniper.net/junos/16.1R1/junos-interface" junos:style="normal">
        <logical-interface>
            <name>xe-2/2/5.0</name>
            <local-index>359</local-index>
            <snmp-index>559</snmp-index>
            <if-config-flags>
                <iff-device-down/>
                <iff-down/>
                <iff-snmp-traps/>
                <internal-flags>0x4004000</internal-flags>
            </if-config-flags>
            <encapsulation>ENET2</encapsulation>
            <policer-overhead>
            </policer-overhead>
            <traffic-statistics junos:style="brief">
                <input-packets>381719</input-packets>
                <output-packets>81931</output-packets>
            </traffic-statistics>
            <filter-information>
            </filter-information>
            <address-family>
                <address-family-name>inet</address-family-name>
                <mtu>9000</mtu>
                <max-local-cache>75000</max-local-cache>
                <new-hold-limit>75000</new-hold-limit>
                <intf-curr-cnt>0</intf-curr-cnt>
                <intf-unresolved-cnt>0</intf-unresolved-cnt>
                <intf-dropcnt>0</intf-dropcnt>
                <address-family-flags>
                    <ifff-mtu-user-conf/>
                    <ifff-sendbcast-pkt-to-re/>
                    <internal-flags>0x0</internal-flags>
                </address-family-flags>
                <interface-address>
                    <ifa-flags>
                        <ifaf-down/>
                        <ifaf-current-preferred/>
                        <ifaf-current-primary/>
                    </ifa-flags>
                    <ifa-destination>10.200.7.100/31</ifa-destination>
                    <ifa-local>10.200.7.100</ifa-local>
                </interface-address>
            </address-family>
            <address-family>
                <address-family-name>multiservice</address-family-name>
                <mtu>Unlimited</mtu>
                <address-family-flags>
                    <internal-flags>0x0</internal-flags>
                </address-family-flags>
            </address-family>
        </logical-interface>
    </interface-information>
    <cli>
        <banner>{master}</banner>
    </cli>
</rpc-reply>

{master}

I think the solution would be to check for the 'if-config-flags/iff-up: flag' , which indicates that interface is disabled. But I don't know how to invert this check, to have the 'is_enabled: True' when this field is missing.

**Comment by dbarrosop** [comment]
I think your logic is correct so let's move forward and try to fix it..

> But I don't know how to invert this check, to have the is_enabled: True when this field is missing.

Not sure if the junos views let you do that. Maybe @mirceaulinic knows. Worst case we can just invert it with python code.

**Comment by jemcek** [comment]
I'm just doing some further testing and I found out that my logic does not handle well interfaces like:
`lo0.0, lc-2/0/0.32769,  pfe-2/0/0.16383`. There is no `{ if-config-flags/iff-up: flag }` when this logical interfaces are up, so I have to find out a better way of detecting the states of logical interfaces. 

Even though some of this interfaces are internal and not configurable and maybe not that important I would still like to have a working solution so that output from `show interfaces terse` will match the output of the `napalm_get_facts: interfaces` for all the logical interfaces.

**Comment by jemcek** [comment]
I fixed my problem by changing the junos_views.yml and junos.py (unfortunately). The Junos logic for logical interfaces is pretty weird and I still don't know if I covered all the cases. But at least now I'm able to get a close match between the `show interfaces` output and `napalm_get_facts` output. 
My logic follows this rules:
1) all the internal interfaces that are non configurable are in my case always up/up. So I just set the state of logical interface based on state of its parent interface `{ ../oper-status: True=up }`
2) if the logical interface has the iff-up flag present, then it is up / up
3) if the logical interface hat the iff-device down flag present (link down), but the iff-down flag is missing (not disabled), then it's state is up / down
4) if the logical interface has the iff-devide down flag present and the iff-down flag present, then it's state is down / down

Below are the two diffs if someone would like to do some more testing. Because I had to test on production hardware I couldn't completely prove that this works well for all loopback scenarios. 

```
--- orig/junos.py	2018-03-21 09:03:09.000000000 +0100
+++ junos.py	2018-03-21 09:42:43.000000000 +0100
@@ -283,7 +283,7 @@
         interfaces_logical.get()

         # convert all the tuples to our pre-defined dict structure
-        def _convert_to_dict(interfaces):
+        def _convert_to_dict(interfaces, logical):
             for iface in interfaces.keys():
                 result[iface] = {
                     'is_up': interfaces[iface]['is_up'],
@@ -298,6 +298,18 @@
                 }
                 # result[iface]['last_flapped'] = float(result[iface]['last_flapped'])

+                if logical == True:
+                    if interfaces[iface]['is_iff_up'] == True:
+                        result[iface]['is_enabled'] = True
+                        result[iface]['is_up'] = True
+                    elif interfaces[iface]['is_iff_down'] == False and interfaces[iface]['is_iff_device_down'] == True:
+                        result[iface]['is_enabled'] = True
+                        result[iface]['is_up'] = False
+                    elif interfaces[iface]['is_iff_down'] == True and interfaces[iface]['is_iff_device_down'] == True:
+                        result[iface]['is_enabled'] = False
+                        result[iface]['is_up'] = False
+
+
                 match = re.search(r'(\d+)(\w*)', interfaces[iface]['speed'] or u'')
                 if match is None:
                     continue
@@ -311,8 +323,8 @@

             return result

-        result = _convert_to_dict(interfaces)
-        result.update(_convert_to_dict(interfaces_logical))
+        result = _convert_to_dict(interfaces, False)
+        result.update(_convert_to_dict(interfaces_logical, True))
         return result

     def get_interfaces_counters(self):
``` 

```
--- orig/junos_views.yml	2018-03-21 09:03:16.000000000 +0100
+++ utils/junos_views.yml	2018-03-21 09:03:30.000000000 +0100
@@ -30,7 +30,12 @@
 junos_logical_iface_view:
   fields:
     is_up: { ../oper-status: True=up }
-    is_enabled: { if-config-flags/iff-up: flag }
+    is_enabled: { ../oper-status: True=up }
+    #added
+    is_iff_up: { if-config-flags/iff-up: flag }
+    is_iff_down: { if-config-flags/iff-down: flag }
+    is_iff_device_down: { if-config-flags/iff-device-down: flag }
+
     description: { description: unicode }
     last_flapped: { ../interface-flapped/@seconds: int }
     speed: ../speed
```

**Comment by dbarrosop** [comment]
I think the best approach would be to open a PR and relevant test cases and see which existing tests break (if any). Would you mind doing so, please?

Thanks and good job :)

**Comment by ckishimo** [comment]
@jemcek are you still working on this ? if not, I can have a look...thanks

**Comment by jemcek** [comment]
Please go ahead, maybe you will find even a better solution.

**Comment by ckishimo** [comment]
> I think the solution would be to check for the if-config-flags/iff-down: flag 

@jemcek I agree with you. The idea is to check if the flag `iff-down` is present
Then if present, interface is `disabled`, otherwise is `enabled`

Doing like that we do not need to look for the `iff-up` flag, therefore status
for interfaces like `lo0.0, lc-2/0/0.32769, pfe-2/0/0.16383` is covered as well

Also the `iff-up` flag is not always present, for instance if the physical interface
is down, flag `iff-device-down` is present but not the `iff-up`

I simplified the code so we only need to look for `iff-down`, it would be great if
you could give it a try please!

Regarding the test case was reporting `is_enabled: False` which was wrong as the flag `iff-down`
is not present anywhere, so I just fixed it to `True` in all interfaces
