### ISSUE TITLE
NAPALM returns two equal IPv6 with get_bgp_neighbors()

### ISSUE THREAD

**Issue by respawner** [napalm-automation/napalm#659]
I have found a strange issue on JUNOS and IPv6 BGP neighbors.

When using the `get_bgp_neighbors` method the inner the dictionary of peers for a given VRF might return two times the same IPv6 address. Here is a minimized output of a result.

```python
            '2001:db8:10:100:0:5:4100:1': {
                'uptime': 738
            },
            '2001:db8:10:100::5:4100:1': {
                'local_as': 64545,
                'remote_as': 64546,
                'remote_id': '',
                'is_up': False,
                'is_enabled': True,
                'description': '',
                'uptime': 0,
                'address_family': {
                    'ipv4': {
                        'received_prefixes': -1,
                        'accepted_prefixes': -1,
                        'sent_prefixes': -1
                    },
                    'ipv6': {
                        'received_prefixes': -1,
                        'accepted_prefixes': -1,
                        'sent_prefixes': -1
                    }
                }
            }
```

If you take a look this is the same peer but with the address in two different format. The issue may come from JUNOS itself. In fact I've noticed that in the configuration the `2001:db8:10:100::5:4100:1` is used but when showing the BGP summary on the router itself the address is expanded to `2001:db8:10:100:0:5:4100:1`.

The expected output would be to have only one peer in the dictionary (address being expanded or not).

**Comment by dbarrosop** [comment]
That's unfortunate, I guess we will have to parse the IP with `netaddr` library to make sure this doesn't happen.

**Comment by KalleDK** [comment]
You might want to use the official module instead https://docs.python.org/3/library/ipaddress.html

**Comment by ckishimo** [comment]
#761 should fix it. @respawner are you able to test ? I was not able to reproduce it using Junos 14.1

**Comment by respawner** [comment]
@ckishimo it seems to be working with your PR yes. Thank you 👍
