### ISSUE TITLE
Stack elements information from get_facts (tested on IOS)

### ISSUE THREAD

**Issue by matthieugouel** [napalm-automation/napalm#663]
hello !

I noticed that get_facts() get only the facts of the master element of a stack, at least with the IOS driver (I haven't tested with other drivers yet).

I don't have Cisco IOS switches in stack at home so I use mocked data of the `show version` command to do the tests.

Here is the output of the `show version` of a stacked device I found on the Cisco website [here](https://www.cisco.com/c/en/us/support/docs/switches/catalyst-3750-series-switches/64898-upgrade-3750-stack.html). It may be differ depending on the version of IOS (here is a 3750 stack with IOS 12.2(20)SE).

```
Cisco Internetwork Operating System Software
IOS (tm) C3750 Software (C3750-I5-M), Version 12.2(20)SE, RELEASE SOFTWARE (fc1)
Copyright (c) 1986-2004 by cisco Systems, Inc.
Compiled Wed 19-May-04 11:52 by yenanh
Image text-base: 0x00003000, data-base: 0x00B53B10

ROM: Bootstrap program is C3750 boot loader
BOOTLDR: C3750 Boot Loader (C3750-HBOOT-M) Version 12.1(14)EA1, RELEASE SOFTWARE (fc1)

3750 uptime is 2 minutes
System returned to ROM by power-on
System image file is "flash:c3750-i5-mz.122-20.SE/c3750-i5-mz.122-20.SE.bin"

cisco WS-C3750G-12S (PowerPC405) processor (revision A0) with 118784K/12280K bytes of
memory.
Processor board ID CAT0732R0JU
Last reset from power-on
Bridging software.
5 Virtual Ethernet/IEEE 802.3  interface(s)
40 Gigabit Ethernet/IEEE 802.3 interface(s)
The password-recovery mechanism is enabled.

512K bytes of flash-simulated non-volatile configuration memory.
Base ethernet MAC Address       : 00:0D:BD:5C:16:80
Motherboard assembly number     : 73-8307-06
Power supply part number        : 341-0048-01
Motherboard serial number       : CAT073205SU
Power supply serial number      : DTH073004US
Model revision number           : A0
Motherboard revision number     : A0
Model number                    : WS-C3750G-12S-E
System serial number            : CAT0732R0JU
Top Assembly Part Number        : 800-23419-01
Top Assembly Revision Number    : A0
Hardware Board Revision Number  : 0x06


Switch   Ports  Model              SW Version              SW Image
------   -----  -----              ----------              ----------
     1   28     WS-C3750G-24TS     12.2(20)SE              C3750-I5-M
*    2   12     WS-C3750G-12S      12.2(20)SE              C3750-I5-M


Switch 01
---------
Switch Uptime                   : 2 minutes
Base ethernet MAC Address       : 00:0C:30:AE:4F:00
Motherboard assembly number     : 73-7058-07
Power supply part number        : 341-0045-01
Motherboard serial number       : CSJ0708020N
Power supply serial number      : LIT07050027
Model revision number           : 01
Motherboard revision number     : 03
Model number                    : WS-C3750G-24TS-E
System serial number            : CSJ0711U03G

Configuration register is 0xF
```

Ok so we can see that there is two elements of the stack and the master is in second position.
When I run the get_facts() command with the following code I get that output : 

```python
with PatchedIOSDriver('', '', '') as device:
    print(device.get_facts())
```
```
{'uptime': 120, 'vendor': 'Cisco', 'os_version': 'C3750 Software (C3750-I5-M), Version 12.2(20)SE, RELEASE SOFTWARE (fc1)', 'serial_number': 'CAT0732R0JU', 'model': 'WS-C3750G-12S', 'hostname': '3750', 'fqdn': '3750.int.ogenstad.com', 'interface_list': ['Vlan1', 'Vlan20', 'Vlan40', 'Vlan41', 'GigabitEthernet0/1', 'GigabitEthernet0/2', 'GigabitEthernet0/3', 'GigabitEthernet0/4', 'GigabitEthernet0/5', 'GigabitEthernet0/6', 'GigabitEthernet0/7', 'GigabitEthernet0/8', 'Port-channel1']}
```

I think that the relevant information that differs depending on the stack element are (at least) the `serial` and the `model` so let's focus on that : 

```
Serial : CAT0732R0JU
Model : WS-C3750G-12S
```
We can see that it is the information of the master device.

I made a little class that extends the regular IOSDriver (here PachedIOSDriver) and add the `serial` and `model` of the slave elements using textfsm.

```python
import napalm.base.helpers

from fake_ios_device import PatchedIOSDriver
from collections import Counter


class StackIOSDriver(PatchedIOSDriver):
    """Fake IOS driver which get the serial and model of all stack elements."""

    def is_stack(self):
        """Check if the device is a stack."""
        # Not used here. Just an example.
        try:
            raw = self._send_command('show Switch')
            # If more than one element is in `Ready` state, it's a valid stack.
            return bool(Counter(raw.split())['Ready'] > 1)
        except ValueError:
            # The command does not exist in the switch, so it's not a stack.
            return False

    def get_facts(self):
        """Return a set of facts from all stack devices."""
        legacy = super().get_facts()
        raw_show_ver = self._send_command('show version')
        show_ver = napalm.base.helpers.textfsm_extractor(
                                self, 'show_version', raw_show_ver)

        # This is the relevant infos of stack devices.
        legacy['serial_number'] = show_ver[0]['serial']
        legacy['model'] = show_ver[0]['hardware']

        return legacy


if __name__ == '__main__':
    with StackIOSDriver('', '', '') as device:
        print(device.get_facts())
```

Here is the textfsm template i use : 

```
Value VERSION (.+?)
Value ROMMON (\S+)
Value HOSTNAME (\S+)
Value UPTIME (.+)
Value RUNNING_IMAGE (\S+)
Value List HARDWARE (\S+\d\S+)
Value List SERIAL (\S+)
Value CONFIG_REGISTER (\S+)

Start
  ^.*Software\s.+\),\sVersion\s${VERSION},*\s+RELEASE.*
  ^ROM: ${ROMMON}
  ^\s*${HOSTNAME}\s+uptime\s+is\s+${UPTIME}
  ^[sS]ystem\s+image\s+file\s+is\s+"(.*?):${RUNNING_IMAGE}"
  ^[Pp]rocessor\s+board\s+ID\s+${SERIAL}
  ^[Cc]isco\s+${HARDWARE}.+
  ^[Cc]onfiguration\s+register\s+is\s+${CONFIG_REGISTER}
  ^Switch -> Stack


Stack
  ^[Ss]ystem [Ss]erial [Nn]umber\s+:\s+${SERIAL}
  ^[Mm]odel\s+[Nn]umber\s+:\s+${HARDWARE}\s*
  ^[Cc]onfiguration\s+register\s+is\s+${CONFIG_REGISTER}
```
And finally this is the output : 

```
{'uptime': 120, 'vendor': 'Cisco', 'os_version': 'C3750 Software (C3750-I5-M), Version 12.2(20)SE, RELEASE SOFTWARE (fc1)', 'serial_number': ['CAT0732R0JU', 'CSJ0711U03G'], 'model': ['WS-C3750G-12S', 'WS-C3750G-24TS-E'], 'hostname': '3750', 'fqdn': '3750.int.ogenstad.com', 'interface_list': ['Vlan1', 'Vlan20', 'Vlan40', 'Vlan41', 'GigabitEthernet0/1', 'GigabitEthernet0/2', 'GigabitEthernet0/3', 'GigabitEthernet0/4', 'GigabitEthernet0/5', 'GigabitEthernet0/6', 'GigabitEthernet0/7', 'GigabitEthernet0/8', 'Port-channel1']}
```

We can see we now have a list instead of a string for `serial_number` and `model`. The first element is the info of the master and then the info of the slaves. 

I don't know if this modification would be good to integrate on Napalm because it breaks the output model. This post is more meant to give an example of getting stack elements information and maybe start a conversation about it.

I hope it's not a duplicate.

So sorry for that long post ! 
Have a good day.

**Comment by ktbyers** [comment]
Related discussion here https://github.com/napalm-automation/napalm/issues/374

**Comment by ktbyers** [comment]
Another related issue here:

https://github.com/napalm-automation/napalm/issues/468

**Comment by ktbyers** [comment]
In the issue #468 I had added the following comment a few days ago which probably generally applies here.

```
So what do we want to do here (i.e. in the switch stack case).

Options

1. Just set it to 0
2. Set it to the value of the primary/master switch stack master
3. Parse all stack members and return a list (though causes compatibility/migration issues in napalm).
4. Aggregate values (which doesn't sound like a good idea to me).

If we go with 3, then that brings up questions about other data structure elements (like power, fans, temperature).

Item 2 is probably the easy solution...I am a bit worried we are opening a big can of worms if we try to do 3.
```

I am past my limit of getter maintenance so more people will have to step up to work on these items (if they want these items).

**Comment by matthieugouel** [comment]
Yes you came to the same conclusion that changing the output model would cause a certain amount of  issues... I think item 4 would be the same, and maybe less clean than a list.

I would be happy to help working on it if the item 3 appears to be the best idea or if a more convenient solution is found !

**Comment by dbarrosop** [comment]
I don't think we should change anything. I think stack members should be queried independently.

**Comment by matthieugouel** [comment]
Is there a way to access to a stack member independently with Napalm ?

**Comment by dbarrosop** [comment]
not today, if that's a feature we want we will have to discuss how to do it. It shouldn't be difficult to do via `optional_args` (assuming you can't just access them via a dedicated port or something like that). Do you have any preference/idea?

**Comment by ktbyers** [comment]
@dbarrosop I think for several Cisco stack platforms there is only a single management IP address. There is neither a dedicated port nor a dedicated management IP address. You would have to query the stack members by custom CLI commands.

People can chime in if my statement is not factually correct.

Solving this problem...is probably not going to be easy.

**Comment by matthieugouel** [comment]
Indeed, to my knowledge you can't directly access by SSH to a IOS stack element (or at least it's not a classic behavior). So you must either collect the stack data from the master or using a custom CLI non-agnostic command as you said.

This is the first solution I used in my example above, using the `show version` of the master to get the serial numbers and models of the stack. 

So IMO the question is all about choosing between the item 2 and 3 of the first  @ktbyers response. If we choose to handle the issue, we might change the output model of all `get_facts()` methods and return a list of serials, model, etc ... 
Indeed if we do that, it will bring the question of include other info like module facts for instance.

I would understand that the most reasonable solution is to do nothing :)

**Comment by FloLaco** [comment]
Maybe we can add and use optional argument on this method `def get_facts(stack_member=0)` for choosing which device we are trying to get. And the returned info are still the same as for other drivers.

**Comment by matthieugouel** [comment]
Yes it could do the trick. The stack_member=0 would always be the master,  but, for instance, that same info could be recovered from stack_member=2 if the master is the second element. 
One think I wonder is how you get the number of stack elements this way ? 

One think I thought also is maybe we could create an other method like `get_elements()` which would return the facts of all stack / module elements independently of `get_facts()`with a whole new output model (ex. is it a stack or a module, how many elements, serial, model, ...)

**Comment by FloLaco** [comment]
It's not mandatory to return, by default, the master's `get_facts`.
But we should have a new method about stack information which will return this kind of info (for example) :
`show switch` -> 
{
id_stack : 
role : 
mac_address : 
state : 
priority : 
hw_version : 
}

OR 
show version -> 
```
{
id_stack : 
role : 
model : 
sw_version : 
port_number : 
}
```

**Comment by dbarrosop** [comment]
Unless this can be implemented in such a way it works "automagically" I am inclined to discard support for this. And by automagically I mean that there is a way of implementing this in such a way all the current and future methods support it without extra consideration (hence why I was asking before about dedicated ports and what not). This could be possible if those "custom" commands are consistent. For instance:

- no stack: `show ip route`
- stack member 0: `stack 0 show ip route`
- stack member 1: `stack 1 show ip route`
...

I am completely made up that, just wanted to illustrate that this has to be something consistent that can be implemented as a wrapper.
