### ISSUE TITLE
Recording branch merging

### ISSUE THREAD

**Issue by anochens** [napalm-automation/napalm#667]
Is there any timeframe on merging in https://github.com/napalm-automation/napalm/pull/590 to the main branch of this project? It looks like everything was sufficiently tested. I would like to rely on this capability, and would prefer not to hardcode a branch into my requirements file

**Comment by dbarrosop** [comment]
Have you tested it? If you can confirm it works we can proceed and merge it. The only reason it hasn't been merged is because I was waiting for the community to test it.

**Comment by anochens** [comment]
I did test it a little but found it lacked the functionality that I needed. All this does is allow saving to a file. I'd like a List of the commands with outputs, etc. (essentially this without the yaml-bit.) And, even with that enabled, it didn't record 100% everything. I ended up going in another direction.
