### ISSUE TITLE
implement timeout

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm#67]
* Add to all drivers
* Add to base
* Add to unittests

**Comment by fooelisa** [comment]
looks like junos and the ansible module were done and have been merged 
I submitted a pull request that adds timeout to iosxr and the base class 
the IBM driver accepts it as well 
eos, fortios and unittests are still open

**Comment by dbarrosop** [comment]
All of them are implemented. We have to fix EOS and IBM which actually ignores the parameter.

**Comment by ktbyers** [comment]
IOS driver supports the timeout argument, but doesn't do anything with it.

**Comment by fooelisa** [comment]
Since EOS, IOS and IBM don't actually do anything with this parameter, should we maybe move it into the optional_args?

**Comment by ktbyers** [comment]
Fine with me.

**Comment by dbarrosop** [comment]
I agree but that's tricky as that changes the API and it might break existing code.

**Comment by fooelisa** [comment]
I would be ok with changing this in a major version bump, and documenting it well, it seems cleaner that way (I really like the optional_args way)

**Comment by dbarrosop** [comment]
I am going to close this one. I don't think it's worth the trouble and, in any case, it should be implemented everywhere.
