### ISSUE TITLE
get_environment does not collect memory correctly for IOS-XE

### ISSUE THREAD

**Issue by mattelphick** [napalm-automation/napalm#680]
The 'show memory statistics' command is used to collect memory data in the IOS get_environment getter.  However this command does not work on IOS-XE devices.

The example device I have is WS-C3850-48P running 03.06.05E.

```
lab-3850-01#show memory statistics
                                  ^
% Invalid input detected at '^' marker.

lab-3850-01#show memory
System memory   : 3931596K total, 1553652K used, 2377944K free, 221424K kernel reserved
Lowest(b)       : 1783259788

                Total(K)     Used(K)      Free(K)
Process         3931596      1553652      2377944
Config          0            0            0

usdal1-03lab-3850-01#
```

**Comment by itdependsnetworks** [comment]
Since spacing is so important, you will need to enclose your output in triple backticks, as described here: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code
