### ISSUE TITLE
NAPALM with JumpServer

### ISSUE THREAD

**Issue by ameer131** [napalm-automation/napalm#682]
Hi there,

I am trying to find a way how can I write a NAPALM script with JumpServer enabled for IOS devices.
It seems there is limited number of args that I can supply:
`        # Netmiko possible arguments
        netmiko_argument_map = {
            'port': None,
            'secret': '',
            'verbose': False,
            'keepalive': 30,
            'global_delay_factor': 1,
            'use_keys': False,
            'key_file': None,
            'ssh_strict': False,
            'system_host_keys': False,
            'alt_host_keys': False,
            'alt_key_file': '',
            'ssh_config_file': None,
            'allow_agent': False,
        }`

Is there any way I can use NAPALM to connect to an IOS device using a JumpServer as what netmiko can do?

**Comment by ktbyers** [comment]
@ameer131 Are you connecting through a terminal server or an SSH Jump Server?

**Comment by ameer131** [comment]
Hi @ktbyers , it is through a terminal server. I am using terminal_server as the device_type and do the connection to the device manually. You have advised me before to use SSH config as that is the proper way to do it but unfortunately, I am using Windows (https://github.com/ktbyers/netmiko/issues/588) . So far its being working just fine and really wish to convert my machine to unix based soon.

is there any plan to support jumpserver soon?

**Comment by ktbyers** [comment]
Both SSH jump servers and terminal servers are supported. They are two different use cases, however.

For SSH Proxy support: https://pynet.twb-tech.com/blog/automation/netmiko-proxy.html

In napalm, you would feed the Netmiko arguments in using the optional_args dictionary. Also see the Netmiko 1.4.0 or 1.4.1 release notes as there were some changes on SSH proxy.

**Comment by ameer131** [comment]
Hi @ktbyers, i can see the **device_type** args is already pre-defined in the library itself.

>         device_type = 'cisco_ios'
        if self.transport == 'telnet':
            device_type = 'cisco_ios_telnet'
        self.device = ConnectHandler(device_type=device_type,
                                     host=self.hostname,
                                     username=self.username,
                                     password=self.password,
                                     **self.netmiko_optional_args)


Here is the code snippet for netmiko that I am using:

> ip = 2.2.2.2
jumpserver = {'device_type': 'terminal_server','ip': '1.1.1.1','username': 'myUsername','password': 'myPassword', 'global_delay_factor':3}
net_connect = ConnectHandler(**jumpserver)
net_connect.find_prompt()
net_connect.write_channel('ssh -o StrictHostKeyChecking=no -l ' + user + ' ' + ip)
time.sleep(2)
prompt =  net_connect.find_prompt()
if 'ssword' in prompt:
    net_connect.write_channel(password)
    time.sleep(3)
redispatch(net_connect, device_type = 'cisco_ios')

From my understanding, in order to use terminal server, the device_type must be set to **terminal_server**. Is there any way I can supply the above code into the optional_args dictionary without modifying the library itself?

I had to do the above as I am using a Windows machine where I don't have much option to use SSH proxy. Hope to change to a unix-based machine soon.

**Comment by ktbyers** [comment]
NAPALM doesn't support terminal servers so unfortunately no.

It supports SSH proxy using an SSH config file.

Brigade would have this support (using Netmiko). In other words, you would have the flexibility of writing your own glue code in Brigade.

**Comment by ameer131** [comment]
I see, thanks for letting me know. Will put Brigade in my next study chapter :)
Thanks @ktbyers, always been helpful!
