### ISSUE TITLE
OSError: Search pattern never detected in send_command_expect: [>##]\s*$

### ISSUE THREAD

**Issue by LongBeachHXC** [napalm-automation/napalm#687]
Is the below problem because a command that was sent down the channel produced a different output such as something like "confirm"?

I ran into this error so I cut down all unnecessary commands from the templates I was referencing and I still encountered the same error. As a result, I rewrote my code to leverage Netmiko directly.

Thank you for any assistance. 

``` Python
#!/usr/bin/env python

from getpass import getpass
from netmiko import ConnectHandler
from netmiko.ssh_exception import NetMikoTimeoutException
from paramiko.ssh_exception import SSHException
from netmiko.ssh_exception import AuthenticationException
from napalm import get_network_driver

username = input('Enter your SSH username: ')
password = getpass()

with open('devices_file') as f:
    devices_list = f.read().splitlines()

for devices in devices_list:
    print ('Connecting to device ' + devices)

    driver = get_network_driver('ios')
    device = driver(devices, username, password)
    device.open()

    device.load_merge_candidate(filename=devices + 'config_final.cfg')

    diffs = device.compare_config()
    if len(diffs) > 0:
        print ('Committing Configuration Differences')
        device.commit_config()
    else:
        print ('No Changes Required')
        device.discard_config()

    device.close()
```

Traceback (most recent call last):
  File "applyconfig.py", line 28, in <module>
    device.commit_config()
  File "/mnt/c/Users/forwein/linuxFileFolder/venv/westfield/wtc/interfacestandardPython3/lib/python3.6/site-packages/napalm/ios/ios.py", line 458, in commit_config
    output = self._commit_hostname_handler(cmd)
  File "/mnt/c/Users/forwein/linuxFileFolder/venv/westfield/wtc/interfacestandardPython3/lib/python3.6/site-packages/napalm/ios/ios.py", line 393, in wrapper
    retval = f(self, *args, **kwargs)
  File "/mnt/c/Users/forwein/linuxFileFolder/venv/westfield/wtc/interfacestandardPython3/lib/python3.6/site-packages/napalm/ios/ios.py", line 418, in _commit_hostname_handler
    output = self.device.send_command_expect(cmd, expect_string=pattern)
  File "/mnt/c/Users/forwein/linuxFileFolder/venv/westfield/wtc/interfacestandardPython3/lib/python3.6/site-packages/netmiko/base_connection.py", line 1069, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/mnt/c/Users/forwein/linuxFileFolder/venv/westfield/wtc/interfacestandardPython3/lib/python3.6/site-packages/netmiko/base_connection.py", line 1051, in send_command
    search_pattern))
OSError: Search pattern never detected in send_command_expect: [>##]\s*$

**Comment by ktbyers** [comment]
Make sure you are using the latest released version of Netmiko and of NAPALM.

Then I would try:

```
    driver = get_network_driver('ios')
    device = driver(devices, username, password, optional_args={'global_delay_factor': 2})
    device.open()
```

Try adding the global_delay_factor (try both 2 and 4 for a value).

**Comment by LongBeachHXC** [comment]
@ktbyers Hey I should have updated this thread but the devices are in production and we were working on them during a maintenance window. By them time I received this suggestion I was outside the maintenance window  where it has become difficult to test that. I will keep this in mind for next time though.

Thank you for following up!

**Comment by ktbyers** [comment]
No worries. Just let me know if there is still an issue. I am going to close this issue for now.

**Comment by awilki01** [comment]
the global_delay_factor of 2 helped me out. Thank you!

**Comment by ktbyers** [comment]
@suhasbhoir Please create a new/separate issue for this and please make sure to format your code properly using GitHub markdown formatting.

Regards, Kirk

**Comment by gomens** [comment]
Kirk,
I was having the same issue and ---optional_args={'global_delay_factor': 2}--- helped fixed it!

Thank you very much. You are awesome!

**Comment by arunsingh1234** [comment]
Hi Kirk,

My issue got solved with --optional_args={'global_delay_factor': 2}

Thank you very much.

Arun

**Comment by syedgaffar1** [comment]
@ktbyers, I too face similar issue and the optional_args={'global_delay_factor': 2} helped to fix it. Thanks a lot

**Comment by mmorteza** [comment]
> Make sure you are using the latest released version of Netmiko and of NAPALM.
> 
> Then I would try:
> 
> ```
>     driver = get_network_driver('ios')
>     device = driver(devices, username, password, optional_args={'global_delay_factor': 2})
>     device.open()
> ```
> 
> Try adding the global_delay_factor (try both 2 and 4 for a value).

**Comment by mmorteza** [comment]
Hi ktbyers
thanks 
my problem was solve with optional_args={'global_delay_factor': 2} .
but whats it does exactly?
