### ISSUE TITLE
NAPALM isn't working

### ISSUE THREAD

**Issue by BlyatFirmeza** [napalm-automation/napalm#690]
When i try to do 

> pip3 install napalm

it gives this output:

Collecting napalm
  Downloading napalm-2.3.0.tar.gz (147kB)
    100% |████████████████████████████████| 153kB 2.3MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-h1r3rl6y/napalm/setup.py", line 6, in <module>
        from pip.req import parse_requirements
    ImportError: No module named 'pip.req'

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-h1r3rl6y/napalm/

It is a fresh install so i don't know what is  missing. Can someone give me a quick answer so i don't have to wait 10days in the group.google chat? Thank you

**Comment by hslabbert** [comment]
Sounds like #689. Are you on pip 10?

**Comment by BlyatFirmeza** [comment]
Yes im indeed on pip10:
`pip 10.0.0b2 from /usr/local/lib/python3.5/dist-packages/pip-10.0.0b2-py3.5.egg/pip (python 3.5)`

**Comment by ktbyers** [comment]
You need to reinstall pip9 until we change our setup.py file (and release a new version). PIP10 broke their API.
