### ISSUE TITLE
Netmiko error/problem

### ISSUE THREAD

**Issue by BlyatFirmeza** [napalm-automation/napalm#691]
I'm getting a error with netbox while using napalm and I think its origin comes from [Netmiko](https://pynet.twb-tech.com/blog/automation/netmiko.html). 
Is it required to install Netmiko in the switch or as a intermediate SSH server for it to work properly?
I'm completly in the dark here, if someone could help i would be very much obliged

**Comment by ktbyers** [comment]
You need to post your error. 

NAPALM requires Netmiko and will automatically install it (when you install NAPALM).

**Comment by BlyatFirmeza** [comment]
I have NAPALM already installed but it didn't worked with netbox, it said i needed to install the driver on the component thats why i don't understand you saying it installs automatically...

**Comment by dbarrosop** [comment]
I am closing this issue due to lack of information. Installing napalm via pip installs netmiko automatically. If netbox is doing something else I suggest raising the issue with them.
