### ISSUE TITLE
Error for 'get_lldp_neighbors()' on 'ios'

### ISSUE THREAD

**Issue by bdlamprecht** [napalm-automation/napalm#695]
I discovered a "strange" error while using NetBox which simply wraps around the NAPALM libraries.
This is what I encountered (I apologize for the extremely long line):

```
{
  "detail": "Error connecting to the device at 9.88.0.5: LLDP details could not determine the value of local interface:\n{'TenGigabitEthernet1/6': [{'port': 'Te1/3', 'hostname': 'bld-vwd-d35a'}], 'TenGigabitEthernet1/5': [{'port': 'xe-0/0/2', 'hostname': 'bld-vwd-d34a'}], 'TenGigabitEthernet5/4': [{'port': 'Te3/2', 'hostname': 'bld-vsl-a'}], 'TenGigabitEthernet2/3': [{'port': 'Te5/4', 'hostname': 'bld-vsd-d32b'}], 'GigabitEthernet9/16': [{'port': 'Gi2/1', 'hostname': 'bld-sc-b'}], 'GigabitEthernet8/16': [{'port': 'Gi2/1', 'hostname': 'bld-sc-a'}], 'TenGigabitEthernet1/4': [{'port': 'Eth3/1', 'hostname': 'bld-vdd-d33a'}], 'TenGigabitEthernet2/8': [{'port': 'xe-0/0/2', 'hostname': 'bld-vdd-d37b'}], 'TenGigabitEthernet2/4': [{'port': 'Eth3/1', 'hostname': 'bld-vdd-d33b'}], 'GigabitEthernet8/18': [{'port': 'Gi1/25', 'hostname': 'bld-vsd-d17a'}], 'TenGigabitEthernet1/8': [{'port': 'xe-0/0/2', 'hostname': 'bld-vdd-d37a'}], 'TenGigabitEthernet2/2': [{'port': 'Te5/4', 'hostname': 'bld-vid-31b'}], 'TenGigabitEthernet2/5': [{'port': 'xe-0/0/2', 'hostname': 'bld-vwd-d34b'}], 'TenGigabitEthernet2/6': [{'port': 'Te1/3', 'hostname': 'bld-vwd-d35b'}], 'TenGigabitEthernet5/5': [{'port': 'Te3/2', 'hostname': 'bld-vsl-b'}], 'TenGigabitEthernet1/2': [{'port': 'Te5/4', 'hostname': 'bld-vid-31a'}], 'TenGigabitEthernet1/3': [{'port': 'Te5/4', 'hostname': 'bld-vsd-d32a'}], 'TenGigabitEthernet1/1': [{'port': 'Te1/1', 'hostname': 'bld-vsc-b'}]}\n\nChassis id: 3820.56c1.4d29\nPort id: Te1/3\nPort Description: bld/vWD35a-vSCa/global\nSystem Name: bld-vwd-d35a.attmgmt.ibm.com\n\nSystem Description: \nCisco IOS Software, c6848x Software (c6848x-ADVENTERPRISEK9-M), Version 15.4(1)SY1, RELEASE SOFTWARE (fc8)\nTechnical Support: http://www.cisco.com/techsupport\nCopyright (c) 1986-2016 by Cisco Systems, Inc.\nCompiled Fri 09-Dec-16 07:37 by prod_rel_team\n\nTime remaining: 100 seconds\nSystem Capabilities: B,R\nEnabled Capabilities: B,R\nManagement Addresses:\n    IP: 9.88.1.89\n    IPV6: 2620:1F7:9C2:C388::A\nAuto Negotiation - supported, enabled\nPhysical media capabilities:\n    Other/unknown\nMedia Attachment Unit type - not advertised\nVlan ID: - not advertised\n\n"
```

I brought this issue up in the NetworkToCode Slack channel and I was asked to include the above along with the following two files for `show lldp neighbors` and `show lldp neighbors detail`:

[show_lldp_neighbors.txt](https://github.com/napalm-automation/napalm/files/1900003/show_lldp_neighbors.txt)
[show_lldp_neighbors_detail.txt](https://github.com/napalm-automation/napalm/files/1900008/show_lldp_neighbors_detail.txt)

This error is really odd because this device's "partner" (`bld-vsc-b`) is running the same code level is connected to the same basic devices, but isn't exhibiting any problems when attempting to use this method on it.

If you need any other information from me for this scenario, please let me know.
Thanks again.

**Comment by bdlamprecht** [comment]
Also thought I would comment that the outputs above were taken from devices in a lab which emulates the production network as best as possible, but is definitely not as "clean" as I would like them to be.

**Comment by itdependsnetworks** [comment]
Trying to understand your comment that this was not taken from production device. Does that mean this device in which you are showing output, does or does not exhibit the same issue?

**Comment by bdlamprecht** [comment]
I was just stating the I didn't do an in-depth review or other "scrubbing" of any proprietary information from the posted files and wanted to cover myself from the corporate overlords in case they found this one day with the hostnames and IP addresses publicly available.

That is all I was trying to communicate.

**Comment by BlyatFirmeza** [comment]
Fix didn't worked for me please #open @ktbyers 
ERROR LOG:
Server Error
