### ISSUE TITLE
LLDP details could not determine the value of local interface

### ISSUE THREAD

**Issue by BlyatFirmeza** [napalm-automation/napalm#709]
I discovered a "strange" error while using NetBox which simply wraps around the NAPALM libraries.
I have tried the fix on #695 but it returns the error "Server Error".
Napalm seems to work on 2960-X and newer ones but in this one (Catalyst 3750-X) it returns this error:

`{"detail":"Error connecting to the device at 10.250.0.33: LLDP details could not determine the value of local interface:\n
{'GigabitEthernet1/0/10': [{'port': 'Gi1/0/50', 'hostname': 'PoloA3'}]
, 'GigabitEthernet1/0/1': [{'port': 'Gi1/0/49', 'hostname': 'PoloA4'}]}
\n\n
Chassis id: f8b7.e2d7.9f00\nPort id: Gi1/0/49
\nPort Description: GigabitEthernet1/0/49
\nSystem Name: PoloA4.nms.unl.pt
\n\nSystem Description: 
\nCisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(2)E7, RELEASE SOFTWARE (fc3)
\nTechnical Support: http://www.cisco.com/techsupport\nCopyright (c) 1986-2017 by Cisco `

Meaning that it does get the interfaces, it just can't display it well. Since i know nothing about Python can anyone tell me what i need to change in 'ios.py'?

**Comment by ktbyers** [comment]
@BlyatFirmeza Please post the following from the device that is failing:

show_lldp_neighbors.txt
show_lldp_neighbors_detail.txt

You can obscure any confidential info in the LLDP just avoid changing the formatting.

**Comment by BlyatFirmeza** [comment]
[show_lldp_neighbors.txt](https://github.com/napalm-automation/napalm/files/1938954/show_lldp_neighbors.txt)
[show_lldp_neighbors_detail.txt](https://github.com/napalm-automation/napalm/files/1938955/show_lldp_neighbors_detail.txt)

**Comment by BlyatFirmeza** [comment]
Hey @ktbyers 
Any news on the subject?

**Comment by ktbyers** [comment]
Someone will have to look at it and submit a PR on it. I haven't done it, not sure I will as I have already done so much work on LLDP parsing and Mac table parsing on Cisco IOS.


Regards, Kirk

**Comment by ogenstad** [comment]
Has this been tested against the latest commit to the develop branch?

**Comment by ktbyers** [comment]
Good point, we should re-test this since there was a recent fix to LLDP parsing.

**Comment by BlyatFirmeza** [comment]
I upgraded today the napalm ( pip install napalm -U) but the problem persists... Any ideas for a manual fix?

**Comment by ogenstad** [comment]
I just tested this with [napalm-inspector](https://github.com/napalm-automation/napalm-inspector), it hasn't been released yet but there's a PR if you want to test it (https://github.com/napalm-automation/napalm-inspector/pull/1).

What I found using that with the input from your files above is that the latest version of Napalm (2.3.1) on pypi raises an exception, however when I instead install the latest development version it succeeds. Here is the returned data:

```json
{
    "GigabitEthernet1/0/1": [
        {
            "parent_interface": "N/A",
            "remote_chassis_id": "f8b7.e2d7.9f00",
            "remote_port": "Gi1/0/49",
            "remote_port_description": "GigabitEthernet1/0/49",
            "remote_system_capab": "B,R",
            "remote_system_description": "Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(2)E7, R                                                                                                                     ELEASE SOFTWARE (fc3)",
            "remote_system_enable_capab": "B",
            "remote_system_name": "PoloA4.nms.unl.pt"
        }
    ],
    "GigabitEthernet1/0/10": [
        {
            "parent_interface": "N/A",
            "remote_chassis_id": "5006.ab57.6180",
            "remote_port": "Gi1/0/50",
            "remote_port_description": "GigabitEthernet1/0/50",
            "remote_system_capab": "B,R",
            "remote_system_description": "Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(2)E7, R                                                                                                                     ELEASE SOFTWARE (fc3)",
            "remote_system_enable_capab": "B",
            "remote_system_name": "PoloA3.nms.unl.pt"
        }
    ]
}
```

So, this has already been fixed in Napalm, it's just not available in a stable release. Once the next version is released it will work.

**Comment by ktbyers** [comment]
I am going to assume this is fixed (given Patrick's last statement). If this is still an issue, please re-open.
