### ISSUE TITLE
NAPALM's use of jtextfsm breaks textfsm in Python 3

### ISSUE THREAD

**Issue by OzNetNerd** [napalm-automation/napalm#730]
Hi all,

I'm working on a tool which uses both textfsm and NAPALM. The problem is that if NAPALM is installed after textfsm, textfsm breaks. 

The issue is due to NAPALM's use of jtextfsm. This package overwrites textfsm's version of `texttable.py` with a version which was written for Python 2.6 and uses the `xrange()` function. As this function is not supported in Python 3, a `NameError: name 'xrange' is not defined` exception is raised when I try to use textfsm.

If feasible, I suggest NAPALM use textfsm instead of jtextfsm, as it now supports Python 3. Furthermore, jtextfsm has not been updated for a few years whereas textfsm is still being maintained by Google.

**Comment by ogenstad** [comment]
For a long time Textfsm wasn’t supported by Google so jtextfsm was used instead. But you are right it should be replaced now.

**Comment by ktbyers** [comment]
This is a long and convoluted tale...

So the above doesn't sound right jtextfsm was used specifically because at the time Google was no longer maintaining textfsm and didn't have (at the time) PY3 support. In other words, jtextfsm was used because of its PY3 support.

Also, I looked through the jtextfsm support and there is no references to texttable or to xrange (nor does jtextfsm install any other packages).

```
$ cat jtextfsm.py | grep -i texttable
$ cat jtextfsm.py | grep xrange
```

So you probably need to post your full stack trace to get a better understanding of what is going on.

Note, Google's textfsm breaks Windows support (at least when you import certain things). In other words, they use certain Linux specific items so it might not be practical just to switch to their version of textfsm. In Netmiko, I had to make a custom version of textFSM for parts of the textFSM library (so Windows support didn't break).

So we would have to test if we run into issues on Windows with Google's TextFSM and NAPALM to see if installing this breaks NAPALM on Windows. 

It might be a non-issue as I think it was clitable that was breaking which we might be using in NAPALM.

Agreed though we should probably look at migrating back to Google's TextFSM, but it might be a meaningful amount of work (depending this Windows issue).

**Comment by OzNetNerd** [comment]
> I looked through the jtextfsm support and there is no references to texttable or to xrange (nor does jtextfsm install any other packages).

That's correct. I did the same and was quite confused by it. Therefore before lodging this ticket I went and installed the NAPALM `requirements.txt` manually. Sure enough, things broke after `jtextfsm` was installed.

> So you probably need to post your full stack trace to get a better understanding of what is going on.

Fair call. Apologies for not providing more details in my original post. Here's what I believe to be the "smoking gun":

```$ sudo pip3 uninstall jtextfsm
Uninstalling jtextfsm-0.3.1:
  Would remove:
    /usr/local/lib/python3.6/dist-packages/clitable.py
    /usr/local/lib/python3.6/dist-packages/copyable_regex_object.py
    /usr/local/lib/python3.6/dist-packages/jtextfsm-0.3.1.dist-info/*
    /usr/local/lib/python3.6/dist-packages/jtextfsm.py
    /usr/local/lib/python3.6/dist-packages/textfsm.py
    /usr/local/lib/python3.6/dist-packages/texttable.py
Proceed (y/n)? 
```
As we can see, `texttable.py` is there and it is the one which is raising the exception:

```$ python3.6 d-extractor.py 
Traceback (most recent call last):
  File "d-extractor.py", line 93, in <module>
    cli_table = clitable.CliTable('index', 'templates')
  File "/usr/local/lib/python3.6/dist-packages/clitable.py", line 155, in Wrapper
    return func(main_obj, *args, **kwargs)  # pylint: disable-msg=E1102
  File "/usr/local/lib/python3.6/dist-packages/clitable.py", line 176, in __init__
    self.ReadIndex(index_file)
  File "/usr/local/lib/python3.6/dist-packages/clitable.py", line 191, in ReadIndex
    self.index = IndexTable(self._PreParse, self._PreCompile, fullpath)
  File "/usr/local/lib/python3.6/dist-packages/clitable.py", line 74, in __init__
    self._ParseIndex(preread, precompile)
  File "/usr/local/lib/python3.6/dist-packages/clitable.py", line 93, in _ParseIndex
    self.index.CsvToTable(self._index_handle)
  File "/usr/local/lib/python3.6/dist-packages/texttable.py", line 943, in CsvToTable
    header_row[entry] = entry
  File "/usr/local/lib/python3.6/dist-packages/texttable.py", line 90, in __setitem__
    for i in xrange(len(self)):
NameError: name 'xrange' is not defined
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "d-extractor.py", line 93, in <module>
    cli_table = clitable.CliTable('index', 'templates')
  File "/usr/local/lib/python3.6/dist-packages/clitable.py", line 155, in Wrapper
    return func(main_obj, *args, **kwargs)  # pylint: disable-msg=E1102
  File "/usr/local/lib/python3.6/dist-packages/clitable.py", line 176, in __init__
    self.ReadIndex(index_file)
  File "/usr/local/lib/python3.6/dist-packages/clitable.py", line 191, in ReadIndex
    self.index = IndexTable(self._PreParse, self._PreCompile, fullpath)
  File "/usr/local/lib/python3.6/dist-packages/clitable.py", line 74, in __init__
    self._ParseIndex(preread, precompile)
  File "/usr/local/lib/python3.6/dist-packages/clitable.py", line 93, in _ParseIndex
    self.index.CsvToTable(self._index_handle)
  File "/usr/local/lib/python3.6/dist-packages/texttable.py", line 943, in CsvToTable
    header_row[entry] = entry
  File "/usr/local/lib/python3.6/dist-packages/texttable.py", line 90, in __setitem__
    for i in xrange(len(self)):
NameError: name 'xrange' is not defined
```

Here's the [texttable.py code](https://www.pastiebin.com/5aff6b165ad0a) after textfsm is installed. And here's the [texttable.py code](https://www.pastiebin.com/5aff6a79aec63) after NAPALM/jtextfsm is installed.

**Comment by ktbyers** [comment]
That texttable.py code is not coming from jtextfsm. It is coming from somewhere else.

**Comment by ktbyers** [comment]
Okay, I take it back...it is jtextfsm that is messing up things.

What they have in their repo is significantly different than what they have on their released version that is on PYPI. The released version on pypi is not PY3 compatible, has texttable.py in it (and that texttable.py had xrange embedded in it).

$ md5sum texttable.py     (this is the file from jtextfsm.py)
d5d06a72a553310a1fe9efa04a1204f7  texttable.py

I verified this by downloading the jtextfsm tar from here:

https://github.com/jonathanslenders/textfsm/releases

This is the same texttable.py that gets installed with pip install jtextfsm.

**Comment by ktbyers** [comment]
Okay, yes we need to fix this.

**Comment by ktbyers** [comment]
Okay, I did a first pass on a PR here:

https://github.com/napalm-automation/napalm/pull/731

I think we will probably be okay on the Windows issue (as we are not using 'clitable.py'), but I will do some more verification on this.

**Comment by OzNetNerd** [comment]
Thanks for looking into this so promptly @ktbyers and @ogenstad.

**Comment by ktbyers** [comment]
@OzNetNerd Should be fixed here:

https://github.com/napalm-automation/napalm/pull/731

**Comment by OzNetNerd** [comment]
Excellent. Thank you @ktbyers.
