### ISSUE TITLE
get_bgp_config is not implemented for the NAPALM ios driver

### ISSUE THREAD

**Issue by sarlacpit** [napalm-automation/napalm#742]
Hi,

I am new to Salt & NAPALM.
I'm trying to see some basic bgp information on a Cisco ASR903 and I keep getting a traceback error:
`
[DEBUG   ] minion return: {u'fun_args': [], u'jid': u'20180604120248428710', u'return': {u'comment': u'get_bgp_config is not implemented for the NAPALM ios driver!', u'traceback': 'Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 167, in call\n    out = getattr(napalm_device.get(\'DRIVER\'), method)(*args, **kwargs)\n  File "/usr/lib/python2.7/dist-packages/napalm_base/base.py", line 605, in get_bgp_config\n    raise NotImplementedError\nNotImplementedError\n', u'result': False, u'out': {}}, u'retcode': 0, u'success': True, u'fun': u'bgp.config'}`

There is BGP configured on the test router but I can't see any information.

Any help would be great.

Thanks

**Comment by ktbyers** [comment]
@sarlacpit You are trying to use a NAPALM method that hasn't been implemented on that platform.

`get_bgp_neighbors` should probably work, but `get_bgp_config` someone would need to write (for Cisco IOS).

See the NAPALM getters matrix here:

http://napalm.readthedocs.io/en/latest/support/#getters-support-matrix
