### ISSUE TITLE
How to use a community driver with napalm-ansible?

### ISSUE THREAD

**Issue by shibumi** [napalm-automation/napalm#743]
Hello,
How can I use a community driver with napalm_ansible? I know that I would need for napalm to import the module, but I can't do this with ansible.. is there any directory where I need to put the community driver?

**Comment by dbarrosop** [comment]
Assuming the driver is built correctly you just install it as a regular python library and use it as any other napalm driver. There is nothing to do unless the driver says so. Basically if it works with `get_network_driver` in the REPL it should just work with the ansible modules.

Closing this one but feel free to keep asking or reopen if you think there is anything broken.

**Comment by shibumi** [comment]
@dbarrosop sorry but you didn't get my question.. I am asking for napalm-ansible(!). I know how I can use the community driver via programming python, but I have no idea how to tell ansible that ansible should use the community driver with napalm and napalm-ansible.

**Comment by dbarrosop** [comment]
I did get your question and I answered it. Happy to provide clarifications if something wasn't clear.

> There is nothing to do unless the driver says so. Basically if it works with get_network_driver in the REPL it should just work with the ansible modules

So basically if it works with `get_network_drivers("blah")` use that same blah as os in the ansible module.

**Comment by shibumi** [comment]
@dbarrosop Thanks for your answer. Sorry seems like I was the one who didn't got your answer. I have executed napalm with `aos` now and this is what I got:
```
2018-06-05 11:55:38,937 - napalm - DEBUG - Gathering napalm packages
2018-06-05 11:55:38,945 - napalm - DEBUG - napalm-ansible==0.9.1
2018-06-05 11:55:38,945 - napalm - DEBUG - napalm-aos==0.1.0
2018-06-05 11:55:38,945 - napalm - DEBUG - napalm-base==1.0.0
2018-06-05 11:55:38,945 - napalm - DEBUG - napalm==2.3.1
2018-06-05 11:55:38,945 - napalm - DEBUG - get_network_driver - Calling with args: ('aos',), {}
2018-06-05 11:55:39,085 - napalm - ERROR - get_network_driver - Failed: No class inheriting "napalm.base.base.NetworkDriver" found in "napalm.aos".
ERROR:napalm:get_network_driver - Failed: No class inheriting "napalm.base.base.NetworkDriver" found in "napalm.aos".

================= Traceback =================

Traceback (most recent call last):
  File "/home/bla/.virtualenvs/ansible/bin/napalm", line 11, in <module>
    sys.exit(main())
  File "/home/bla/.virtualenvs/ansible/lib/python3.6/site-packages/napalm_base/clitools/cl_napalm.py", line 285, in main
    run_tests(args)
  File "/home/bla/.virtualenvs/ansible/lib/python3.6/site-packages/napalm_base/clitools/cl_napalm.py", line 251, in run_tests
    driver = call_get_network_driver(args.vendor)
  File "/home/bla/.virtualenvs/ansible/lib/python3.6/site-packages/napalm_base/clitools/cl_napalm.py", line 27, in wrapper
    r = func(*args, **kwargs)
  File "/home/bla/.virtualenvs/ansible/lib/python3.6/site-packages/napalm_base/clitools/cl_napalm.py", line 155, in call_get_network_driver
    return get_network_driver(vendor)
  File "/home/bla/.virtualenvs/ansible/lib/python3.6/site-packages/napalm/base/__init__.py", line 116, in get_network_driver
    .format(install_name=module_install_name))
napalm.base.exceptions.ModuleImportError: No class inheriting "napalm.base.base.NetworkDriver" found in "napalm.aos".
```

Does this mean that the napalm-aos driver is broken?

With Ansible I get this error:
```
FAILED! => {"changed": false, "msg": "value of dev_os must be one of: eos, junos, iosxr, fortios, ios, mock, nxos, nxos_ssh, panos, vyos, ros, got: aos"}
```

**Comment by dbarrosop** [comment]
> Does this mean that the napalm-aos driver is broken?

Not necessarily. So, couple of questions:

1. Does it work in the REPL? Would be nice if you run:

```
>>> from napalm import get_network_driver
>>> get_network_driver("aos")
# here we should see some info about the module now
```

2. If it works, are you certain you are using the same virtual environment for the REPL and ansible?

**Comment by dbarrosop** [comment]
Wait, now it's me who missed half of your answer :P Yeah, that output seems to indicate something is broken in the AOS library. How did you install it?

**Comment by shibumi** [comment]
I have created a virtualenvironment and installed it via `pip` with `pip install napalm` and `pip install napalm-aos`. Thanks for your help :)

**Comment by dbarrosop** [comment]
I am not sure how you installed it though, I get this:

```
$ pip install napalm-aos
Collecting napalm-aos
  Could not find a version that satisfies the requirement napalm-aos (from versions: )
No matching distribution found for napalm-aos
```

So I don't think they have any code published. I'd open an issue in their repo.

**Comment by shibumi** [comment]
@dbarrosop I installed it via `pip install git+<URL to the repository>`
I have opened an issue in their repository.. thanks

**Comment by ktbyers** [comment]
I think there are probably multiple issues here:

1. AOS driver looks like it has an issue:

```
napalm.base.exceptions.ModuleImportError: No class inheriting "napalm.base.base.NetworkDriver" found in "napalm.aos".
```

2. The second issue is that os_choices in napalm-ansible needs removed which I have submitted a PR on here:

https://github.com/napalm-automation/napalm-ansible/pull/132

**Comment by shibumi** [comment]
@ktbyers 
Removing the second is a good idea.

About the first.. do you have a quickfix for this? I guess the rest of the code is alright just something in napalm changed and triggers that bug in AOS now..
