### ISSUE TITLE
Add get_cdp_neighbors() and get_cdp_neighbors_details()

### ISSUE THREAD

**Issue by orgito** [napalm-automation/napalm#751]
Add the methods to get CDP neighbors to devices that support CDP. Currently only LLDP neighbors are supported, but scenarios where CDP is required are common.

**Comment by mirceaulinic** [comment]
Hi @orgito - @dainok already has a PR for this: https://github.com/napalm-automation/napalm/pull/601 and he'll appreciate any help you can provide. Thanks!

**Comment by ktbyers** [comment]
This is a duplicate issue. Closing.
