### ISSUE TITLE
Any Napalm function to get channel group information

### ISSUE THREAD

**Issue by AmbicaY** [napalm-automation/napalm#753]
I need to get the channel group information for a port channel, i.e. the interfaces in a channel group, 
example, in cisco, to get this kind of information, we run:
show etherchannel 11 port-channel

it shows:
Ports in the Port-channel:

Index   Load   Port     EC state        No of bits
------+------+------+------------------+-----------
  0     00     **Gi8/27**   On                 0
  1     00     **Gi8/28**   On                 0

Do we have any NAPALM function to get such information ?

**Comment by ktbyers** [comment]
Yes, I don't think there is any napalm getter that accomplishes this.

You could look at TextFSM and NTC-templates and see if they have anything that does this.
