### ISSUE TITLE
Add getter get_bgp_received_routes

### ISSUE THREAD

**Issue by omershtivi** [napalm-automation/napalm#755]
Add a getter to specify a BGP neighbour address and get in response all the BGP NLRI received from that neighbour.

Juniper command:
show route receive-protocol bgp <neighbour>

**Comment by mirceaulinic** [comment]
That's a good idea @omershtivi, and it would make sense as it's not at all specific to a particular platform. Would you be able to implement for a couple of drivers? Thanks!

**Comment by omershtivi** [comment]
Hi Mircea,
I think I can implement it for Junos, but for now I don't have access to other network devices.
I will start with Junos and see how it goes from there.

**Comment by pehruby** [comment]
I can try to implement it for ios, nxos-cli. What input parameters? Neighbor IP and vrf name?

**Comment by omershtivi** [comment]
I think the VRF name need to be optional, and if it's not specify just fall to the default table

**Comment by omershtivi** [comment]
So the name:
get_bgp_receive_routes is ok? any other suggestion?
What do we want to return?
The received routes from that neighbour... anything else?
I still think it should be a dict in a list in case we want to add additional information later (communities? LP?) without breaking  other people code

**Comment by pehruby** [comment]
For me number of routes received is important to be able to check if it is in a certain range.

**Comment by omershtivi** [comment]
Can you please explain what do you mean?

I think we should also add a "vrf all" option

**Comment by pehruby** [comment]
I wanted to include received prefixes count but this information is already included get_bgp_neighbors. So I don't know if makes sense to include it into this getter as well.

**Comment by omershtivi** [comment]
@pehruby First there is the get_bgp_neighbors as you mentioned, but if you want for just one neighbour.
There is no need to include a  count method because there is always the __len__, because it is just a list.
I don't see what the flag add, if there is no soft_reconfiguration the list will be 0, so the flag won't change anything.
The method will not change the config because it is a getter, and this also not the naplam way

**Comment by pehruby** [comment]
@omershtivi I'd like to distinguish if the empty list is a consequence of missing soft reconfiguration or if no prefixes were received from the neighbor.

**Comment by omershtivi** [comment]
I don't think this is the place for the soft reconfiguration it is more on the get bgp config but let me know if you think differently @mirceaulinic

**Comment by omershtivi** [comment]
Hi would like to change concept. instead of get_bgp_received_routes to:
get_routes_neighbour, the getter will receive neighbour, direction (in/out), and protocol.
