### ISSUE TITLE
Napalm CLI has Pip 10.0.1 incompatibilities 

### ISSUE THREAD

**Issue by james-powis** [napalm-automation/napalm#756]
Due to internal API changes in pip, napalm breaks, but when pip is down graded to 9.x it works.
```
$ napalm --user user --password password --vendor ios server call get_facts
Traceback (most recent call last):
  File "/usr/local/bin/napalm", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/napalm/base/clitools/cl_napalm.py", line 284, in main
    check_installed_packages()
  File "/usr/local/lib/python2.7/dist-packages/napalm/base/clitools/cl_napalm.py", line 146, in check_installed_packages
    installed_packages = pip.get_installed_distributions()
AttributeError: 'module' object has no attribute 'get_installed_distributions'
```

**Comment by ktbyers** [comment]
This is fixed in the `develop` branch:

https://github.com/napalm-automation/napalm/commit/a376387297a2c5d2b57c07ddd07a05ce69cfabe3#diff-bf37101a570e51364aa8220585401244

We need to do a new release to get it to pypi, however.

**Comment by james-powis** [comment]
Can we please get a new release cut... Continually having issues with people (or processes) upgrading this package...

**Comment by PalaniKumarP** [comment]
How about the newer version release? I'm getting the same error. Please inform me once it is released. Thanks in advance.

**Comment by ktbyers** [comment]
NAPALM 2.3.2 was released a few minutes ago.

**Comment by james-powis** [comment]
@ktbyers Kirk thanks for the exceptional follow up!
