### ISSUE TITLE
NXOS configuration replace does not work via an SSH proxy

### ISSUE THREAD

**Issue by iamroddo** [napalm-automation/napalm#762]
I created a checkpoint file on a Nexus 9K running 7.0(3)I7(4) and transferred it to my script host with SCP. After doing so I changed the hostname on the Nexus and used the example script at http://napalm.readthedocs.io/en/latest/tutorials/samples.html#load-replace-configuration and the downloaded checkpoint/configuration file against this Nexus 9K. The outcome was that the hostname of the Nexus 9K was not reverted and the script also produced an error `socket.error: [Errno 110] Connection timed out`.

When I change the script to use "load_merge_candidate" the script gets further, it reverts the hostname on the Nexus 9K but times out.

Running the command `rollback running-config file bootflash:test-checkpoint` on the Nexus 9K rolls back the config without error.

`configure replace bootflash:///test-checkpoint` fails.

I setup a virtual NXOS in CML, created a checkpoint file, modified the hostname of the virtual device and rolled the checkpoint file with the CLI tool, using strategy = replace and also with merge.

With `napalm --user cisco --password cisco --vendor nxos_ssh --optional_args 'ssh_config_file="/home/vagrant/.ssh/cml-config"' 10.255.0.47  configure cml-checkpoint --strategy merge`, the error `napalm.base.exceptions.MergeConfigException: Socket is closed` appeared.

With `napalm --user cisco --password cisco --vendor nxos_ssh --optional_args 'ssh_config_file="/home/vagrant/.ssh/cml-config"' 10.255.0.47  configure cml-checkpoint --strategy replace` the error `TimeoutError: [Errno 110] Connection timed out`.

Should a checkpoint file generated by a NXOS device be able to be used by a Napalm load_replace_candidate operation? Does such a checkpoint file need to be modified in order for it to be valid?

The Napalm Ansible host is running Xenial64 on Vagrant with Napalm installed using PIP.
vagrant@ansible:~$ pip list

DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
asn1crypto (0.24.0)
bcrypt (3.1.4)
blinker (1.3)
certifi (2018.4.16)
cffi (1.11.5)
chardet (3.0.4)
cloud-init (18.2)
command-not-found (0.3)
configobj (5.0.6)
cryptography (2.2.2)
diffios (0.0.9)
future (0.16.0)
idna (2.7)
Jinja2 (2.10)
jsonpatch (1.10)
jsonpointer (1.9)
jtextfsm (0.3.1)
junos-eznc (2.1.8)
language-selector (0.1)
lxml (4.2.3)
MarkupSafe (1.0)
napalm (2.3.1)
napalm-ansible (0.9.1)
ncclient (0.6.0)
netaddr (0.7.19)
netmiko (2.1.1)
oauthlib (1.0.3)
paramiko (2.4.1)
pip (9.0.3)
prettytable (0.7.2)
pyasn1 (0.4.3)
pycparser (2.18)
pycurl (7.43.0)
pyeapi (0.8.2)
pygobject (3.20.0)
pyIOSXR (0.53)
PyJWT (1.3.0)
PyNaCl (1.2.1)
pynxos (0.0.3)
pyserial (3.4)
python-apt (1.1.0b1+ubuntu0.16.4.1)
python-debian (0.1.27)
python-systemd (231)
PyYAML (3.12)
requests (2.19.1)
scp (0.11.0)
setuptools (39.2.0)
six (1.11.0)
ssh-import-id (5.5)
textfsm (0.4.1)
ufw (0.35)
urllib3 (1.23)
virtualenv (15.0.1)
wheel (0.31.1)
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
vagrant@ansible:~$

**Comment by ktbyers** [comment]
@iamroddo Your first error is an error actually reaching the device.

You need to post your ansible playbook.

**Comment by ktbyers** [comment]
Note, replace config on nxos_ssh will not work via an SSH proxy.

**Comment by iamroddo** [comment]
I wanted to get replace working. The details on merge was to provide background. Is there any chance that replace will function with nxos_ssh via SSH proxy at any point?

**Comment by ktbyers** [comment]
@iamroddo Feel free to submit a PR on it.

**Comment by ktbyers** [comment]
This is a bit of a hard problem or at least harder than it might initially appear due to use of Secure Copy for the file transfer (and also due to Netmiko SCP needing to support Cisco IOS and consequently needing to open a completely separate SCP channel). This is NX-OS, but Netmiko needs to support both so its pattern is the lowest common denominator (i.e. supports Cisco IOS).

If anyone wants to work on this, let me know.

I am going to close this for now.
