### ISSUE TITLE
Dynamic Pull OS information

### ISSUE THREAD

**Issue by mmihir82** [napalm-automation/napalm#765]
Hello 
Is there any way to find driver (what OS is target device). What I was thinking to run the SNMP query to pull OS information, then pass to driver, then run the next action (stackstorm workflow).

This will be really helpful. 

I using stackstorm.

**Comment by ktbyers** [comment]
Netmiko has two autodetect mechanism one that is SSH based and one that is SNMP based. You could probably use that and then run what Netmiko provides back into a dictionary that maps it to NAPALM platform.

**Comment by ktbyers** [comment]
https://github.com/ktbyers/netmiko/tree/develop/examples/use_cases/case8_autodetect

**Comment by mmihir82** [comment]
Thanks @ktbyers,
