### ISSUE TITLE
NAPALM - autodetect

### ISSUE THREAD

**Issue by marinkosmiljanic** [napalm-automation/napalm#769]
Hi,

It is not really issue but only question.

Is it possible to not define OS version in "get_network_driver('ios')" command, but to use "get_network_driver('autodetect')" instead? 
It is possible in Netmiko, but not sure is it work in Napalm. 
I have to use Napalm since it is possible to compare running config file on Cisco switch/router with the changes we plan to implement. Is this option available with Netmiko as well?

Thank you for feedback.

Regards,
Marinko

**Comment by ktbyers** [comment]
NAPALM does not have this. You would have to use Netmiko or something else to find this and then feed the device_type into Netmiko.

NAPALM uses Netmiko for certain platforms? Why don't you use Netmiko for the autodetect and NAPALM for the functionality you want to achieve with the 'diff'?

**Comment by marinkosmiljanic** [comment]
Thank you Kirk for prompt feedback.
I will do as you suggested.

Have a nice weekend.

Regards,
Marinko

**Comment by ktbyers** [comment]
Yes, you too.
