### ISSUE TITLE
Unable to access ios device in enable mode

### ISSUE THREAD

**Issue by nachosn89** [napalm-automation/napalm#777]
Hi,

I am trying to access to some cisco device with IOS Version 15.1 and version 12.4, and I want to run show commands with privileged mode. If I manually go to the device and type enable, I am able to type the password and run those commands.

Following the documentation, I added the parameter 'secret' in the optional_args but I cannot run those commands, so I guess it didn't entered in enable. 

I tried running:
my_device.device.enable()
my_device.device.check_enable_mode() -> Always return true even if I don't set the secret, is that normal?

I am using **napalm 2.3.1 and a jumphost** to connect to the devices.

Many thanks,

**Comment by ktbyers** [comment]
```
my_device.device.check_enable_mode() -> Always return true even if I don't set the secret, is that normal?
```

What does your prompt look like from the CLI--before and after the enable action (if you do this manually)?

Are you going from privilege 1 to privilege 15 (or doing something else potentially using AAA)?

**Comment by nachosn89** [comment]
Many thanks Kirk.

It looks the same ->  `hostname#`
and for the password is just -> `Password:`

I am going from privilege 3 to 15 after the enable. 

The commands I would like to run for now are just: 
show running-config
show vlan brief

Thank you

**Comment by nachosn89** [comment]
I know how to fix it.

First exiting:
device.device.exit_enable_mode()
and executing the enable again:
device.device.enable(cmd=u'enable', pattern=u'password')

No it is working as expected.

Many thanks

**Comment by ktbyers** [comment]
For reference Netmiko is using the prompt as an indicator that you are in enable mode (so it sees '#' and concludes you are already in enable mode).
