### ISSUE TITLE
add port parameter

### ISSUE THREAD

**Issue by fooelisa** [napalm-automation/napalm#78]

**Comment by ktbyers** [comment]
From discussion with @dbarrosop, 'port' argument will be added in optional_args dictionary.

Here is how I did optional_args and 'port' in the cisco IOS driver.

<pre>
    def __init__(self, hostname, username, password, timeout=60, optional_args=None):
        if optional_args is None:
            optional_args = {}
        self.hostname = hostname
        self.username = username
        self.password = password
        self.timeout = timeout
        ...
        self.port = optional_args.get('port', 22)
</pre>

See https://github.com/ktbyers/napalm/commit/9f346e51b08a72a0fa0c40137acaf79b628f97f2

**Comment by mirceaulinic** [comment]
From what I can understand, this one has been solved?

**Comment by ktbyers** [comment]
Yes, that is my understanding too.
