### ISSUE TITLE
setup.py - pip version 10 ImportError: No module named req.

### ISSUE THREAD

**Issue by sarlacpit** [napalm-automation/napalm#783]
When trying to install Napalm on Ubuntu 16.04 I kept coming across the following message installing the napalm_install_formula on Saltstack: https://mirceaulinic.net/2017-07-06-napalm-install-formula/ and kept getting the following message.

```
local:
----------
          ID: install_napalm_ios_pkgs
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 16:21:59.393955
    Duration: 920.083 ms
     Changes:   
----------
          ID: napalm-ios
    Function: pip.installed
      Result: False
     Comment: Failed to install packages: napalm-ios. Error: Collecting napalm-ios
                Using cached https://files.pythonhosted.org/packages/3b/4a/56fea8dd08b14395da6f3f64edc9f5a48bb077c8cf6f48b76fa5ec54d727/napalm-ios-0.8.1.tar.gz
                  Complete output from command python setup.py egg_info:
                  Traceback (most recent call last):
                    File "<string>", line 1, in <module>
                    File "/tmp/pip-install-WLw8Eo/napalm-ios/setup.py", line 5, in <module>
                      from pip.req import parse_requirements
                  ImportError: No module named req
                  
                  ---------------------------------------- /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
                warnings.warn(warning, RequestsDependencyWarning)
              Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-WLw8Eo/napalm-ios/
     Started: 16:22:00.791283
    Duration: 2593.054 ms
     Changes:   

```
I was informed by a helpful dude to downgrade pip - I am a novice python user but managed to downgrade to 9.0.3 which worked a treat. 

> In pip >= 10, pip.req doesn’t exist anymore, you should probably report that to napalm upstream so they can fix it in their setup.py'

**Comment by ktbyers** [comment]
You are using an old version of napalm. You need to upgrade to a new version of napalm (napalm 2.3.1 is the latest) and this issue should be fixed (well except for in napalm-cli where it will be fixed on the next release; it is fixed in the develop branch there).

**Comment by sjtarik** [comment]
I am still seeing this issue on napalm 2.4.0

**Comment by ktbyers** [comment]
Commented in Slack, but I think that is probably due to you still having napalm-base installed (potentially).

napalm-base is deprecated.
