### ISSUE TITLE
connection failure - Cisco Catalyst C6848  

### ISSUE THREAD

**Issue by jifox** [napalm-automation/napalm#793]
I'm focussing a connection problem on one of my C6848 switches. The same playbook will 

CISCO IOS VERSION
#show version
Cisco IOS Software, c6848x Software (c6848x-IPSERVICESK9-M), Version 15.4(1)SY4, RELEASE SOFTWARE (fc3)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2018 by Cisco Systems, Inc.
Compiled Fri 02-Feb-18 02:07 by prod_rel_team

ROM: System Bootstrap, Version 15.2(02)SY [Rel 1.0], RELEASE SOFTWARE

ANSIBLE VERSION:
$ ansible --version
ansible 2.6.3
  config file = /home/ansible/ansible/develop/ansible.cfg
  configured module search path = ['/usr/lib/python3.6/site-packages/napalm_ansible']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, Apr 10 2018, 17:08:37) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

NAPALM VERSIONS
$ pip3 list | grep  napalm
napalm                     2.3.2
napalm-ansible             0.10.0

ANSIBLE PLAYBOOK that produces the error
```
---

# filter='facts,interfaces,bgp_neighbors'
#   http://napalm.readthedocs.io/en/latest/support/
#

- hosts: ios
  gather_facts: no

  tasks:
    - name: Print dev_os|
      local_action:
        module: debug
        msg: "dev_os: {{ ansible_network_os }}"
      tags: [print_action]


    - name: Gather facts with ios_facts
      ios_facts:
      tags: [print_action]
      
    - name: get facts from device
      napalm_get_facts:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        dev_os: "{{ ansible_network_os }}"
        password: "{{ ansible_ssh_pass }}"
        filter:
          - "facts"
      register: result


    - name: print data
      debug: var=result
      tags: [print_action]

```

PLAYBOOK OUTPUT
The above playbook works for Catalyst 9300-48P Switches wih ios 16.6.4. As shown, the authentication settings are correct because ios_facts module is working as expected.

```
$ ansible-playbook  -i hosts.yml  --limit ATKPACSC001  tasks/get_napalm_facts.yml
# print data **************************************************************************************************************
  * ATKPACSC001                - changed=False -- username: admin, dev_os: ios ----------------
# Gather facts with ios_facts *********************************************************************************************
  * ATKPACSC001                - changed=False --  --------------------------------------------
# get facts from device ***************************************************************************************************
  * ATKPACSC001                - FAILED!!! ------------------------------------------------------
    cannot connect to device: Cannot connect to ATKPACSC001
        to retry, use: --limit @/home/ansible/ansible/develop/tasks/get_napalm_facts.retry

# STATS *******************************************************************************************************************
ATKPACSC001    : ok=2   changed=0       failed=1        unreachable=0

```

**Comment by ktbyers** [comment]
Can you show the output of the playbook execution with the '-vvv' arguments?

```
nsible-playbook  -i hosts.yml  --limit ATKPACSC001  tasks/get_napalm_facts.yml -vvv
```

**Comment by jifox** [comment]
@ktbyers 
Hi,

Here is the output with -vvv arguments. I've trunkated switch configuration output manually.

[ansible@scvnetmgmt01 develop]$ ansible-playbook  -i hosts.yml  --limit ATKPACSC001  tasks/get_napalm_facts.yml -vvv
ansible-playbook 2.6.3
  config file = /home/ansible/ansible/develop/ansible.cfg
  configured module search path = ['/usr/lib/python3.6/site-packages/napalm_ansible']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.5 (default, Apr 10 2018, 17:08:37) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /home/ansible/ansible/develop/ansible.cfg as config file
Parsed /home/ansible/ansible/develop/hosts.yml inventory source with yaml plugin

PLAYBOOK: get_napalm_facts.yml ********************************************************************************************************************************************
1 plays in tasks/get_napalm_facts.yml

PLAY [ios] ****************************************************************************************************************************************************************
META: ran handlers

TASK [Print dev_os|] ******************************************************************************************************************************************************
task path: /home/ansible/ansible/develop/tasks/get_napalm_facts.yml:12
ok: [ATKPACSC001 -> localhost] => {
    "msg": "dev_os: ios"
}

TASK [Gather facts with ios_facts] ****************************************************************************************************************************************
task path: /home/ansible/ansible/develop/tasks/get_napalm_facts.yml:19
<172.24.228.1> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<172.24.228.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739599.726225-157481377882242 `" && echo ansible-tmp-1534739599.726225-157481377882242="` echo /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739599.726225-157481377882242 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/network/ios/ios_facts.py
<172.24.228.1> PUT /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/tmpevpsk50n TO /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739599.726225-157481377882242/ios_facts.py
<172.24.228.1> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739599.726225-157481377882242/ /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739599.726225-157481377882242/ios_facts.py && sleep 0'
<172.24.228.1> EXEC /bin/sh -c '/usr/bin/python3 /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739599.726225-157481377882242/ios_facts.py && sleep 0'
<172.24.228.1> EXEC /bin/sh -c 'rm -f -r /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739599.726225-157481377882242/ > /dev/null 2>&1 && sleep 0'
ok: [ATKPACSC001] => {
    "ansible_facts": {
        "ansible_net_all_ipv4_addresses": [
            "nnn.nn.n.nn",
        ],
		...
        },
        "ansible_net_serialnum": "XXXXXXXXXXX",
        "ansible_net_version": "15.4(1)SY4"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": null,
            "gather_subset": [
                "!config"
            ],
            "host": null,
            "password": null,
            "port": null,
            "provider": null,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    }
}

TASK [get facts from device] **********************************************************************************************************************************************
task path: /home/ansible/ansible/develop/tasks/get_napalm_facts.yml:23
<172.24.228.1> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<172.24.228.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739603.682591-42135588618673 `" && echo ansible-tmp-1534739603.682591-42135588618673="` echo /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739603.682591-42135588618673 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/napalm_ansible/modules/napalm_get_facts.py
<172.24.228.1> PUT /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/tmp5x67m_ft TO /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739603.682591-42135588618673/napalm_get_facts.py
<172.24.228.1> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739603.682591-42135588618673/ /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739603.682591-42135588618673/napalm_get_facts.py && sleep 0'
<172.24.228.1> EXEC /bin/sh -c '/usr/bin/python3 /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739603.682591-42135588618673/napalm_get_facts.py && sleep 0'
<172.24.228.1> EXEC /bin/sh -c 'rm -f -r /home/ansible/.ansible/tmp/ansible-local-27379_uyon_d1/ansible-tmp-1534739603.682591-42135588618673/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_rl1o1fmv/ansible_module_napalm_get_facts.py", line 228, in main
    device.open()
  File "/usr/lib/python3.6/site-packages/napalm/ios/ios.py", line 138, in open
    netmiko_optional_args=self.netmiko_optional_args,
  File "/usr/lib/python3.6/site-packages/napalm/base/base.py", line 84, in _netmiko_open
    raise ConnectionException('Cannot connect to {}'.format(self.hostname))

fatal: [ATKPACSC001]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "args": null,
            "dev_os": "ios",
            "filter": [
                "facts"
            ],
            "hostname": "ATKPACSC001",
            "ignore_notimplemented": false,
            "optional_args": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "provider": null,
            "timeout": 60,
            "username": "admin"
        }
    },
    "msg": "cannot connect to device: Cannot connect to ATKPACSC001"
}
        to retry, use: --limit @/home/ansible/ansible/develop/tasks/get_napalm_facts.retry

PLAY RECAP ****************************************************************************************************************************************************************
ATKPACSC001                : ok=2    changed=0    unreachable=0    failed=1

**Comment by ktbyers** [comment]
@jifox Is `ATKPACSC001` DNS resolvable?

What does your Ansible inventory look like (for the 'ios' group) and ATKPACSC001

**Comment by jifox** [comment]
children:
        ios:
          # All IOS Switches (valid modules: ios_config, ios_facts, ios_vlan, ios_l2_interface)
          children:
            ios_br:
              hosts:
                ATBRACSC001:
                  ansible_host: 172.23.228.1
                  is_default_gateway: true
                  is_location_dcbr: true
                  is_location_fwbr: true

**Comment by ktbyers** [comment]
@jifox You need to use {{ ansible_host }} in your playbook, not {{ inventory_hostname }}:

So I would try this:

```
    - name: get facts from device
      napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        dev_os: "{{ ansible_network_os }}"
        password: "{{ ansible_ssh_pass }}"
        filter:
          - "facts"
      register: result
```

**Comment by jifox** [comment]
@ktbyers  Thanks, using _hostname: "{{ ansible_host }}"_  solved the problem. 
Close ticket, please
