### ISSUE TITLE
Use already established Netmiko connection for SCP instead of importing Paramiko in nxos_ssh

### ISSUE THREAD

**Issue by TomCos** [napalm-automation/napalm#804]
Wanted to discuss.  I see in the ios driver, the SCP transfer is happening via Netmiko, which makes sense because that connection already exists.  In the nxos_ssh driver though, (if my understanding is correct), it's creating a new connection with Paramiko and the SCP is happening over that connection, instead of the already made Netmiko one.  Is it worth moving the nxos_ssh driver to match the ios one for SCP method, in both efficiency and reduced complexity?

**Comment by ktbyers** [comment]
Netmiko opens a separate connection for the SCP also.

Personally, I don't think this is worth fixing as it likely a lot of work and not that much value (reducing the connections from two to one).

**Comment by TomCos** [comment]
My understanding was Netmiko opens a separate channel, under the same connection though.  The Paramiko code is creating a brand new connection for the transfer to take place.  Based on my other commit going right now in the Netmiko repo, I'm a big fan of the SCP implementation in Netmiko, so it made sense to ask why we'd opening a separate session in Paramiko.

**Comment by ktbyers** [comment]
No, Netmiko creates a separate SCP channel. 

It probably would be ultimately better so NX-OS in napalm used Netmiko pattern (so we had consistent behavior), but it still would be separate connections.

This is from the netmiko scp_handler.py:

```python
    def establish_scp_conn(self):
        """Establish the secure copy connection."""
        ssh_connect_params = self.ssh_ctl_chan._connect_params_dict()
        self.scp_conn = self.ssh_ctl_chan._build_ssh_client()
        self.scp_conn.connect(**ssh_connect_params)
        self.scp_client = scp.SCPClient(self.scp_conn.get_transport())
```

It would be great if you want to work on a PR for that (consolidating NX-OS to use Netmiko for its SCP function).

Kirk

**Comment by TomCos** [comment]
Yes, new channel, same session though, using the session already created by Netmiko.  I can take a stab at it.  I'm new to the space, so let's keep this open for a bit.

**Comment by ktbyers** [comment]
No completely new SSH session and then it uses a channel in that completely new SSH session...i.e. self.scp_conn and self.ssh_ctl_chan are separate connections. Netmiko takes the parameters from the other connection, but it is a separate connection.

Probably shouldn't be that way, but that is how it currently is.

**Comment by TomCos** [comment]
Ah ok, been looking through, I see what you mean.  You call connect again, instead of passing the paramiko transport in the current netmiko session, correct?  If that understanding is correct, then I think we're on the same page.

**Comment by ktbyers** [comment]
Yes, that is correct...

I just tried a quick test fix on that to see if it worked, but it was failing (i.e. to re-use the existing SSH connection).

```
paramiko.ssh_exception.ChannelException: (4, 'Resource shortage')
```

I suspect that the fix might not be as easy as one would hope (given that we have to use `invoke_shell()` ). Which also potentially explains why I wrote it the way I did originally (it has been a while since I wrote that code).

**Comment by ktbyers** [comment]
Here was the fix I was trying...didn't look at it too much though:

```python
     def establish_scp_conn(self):
         """Establish the secure copy connection."""
-        ssh_connect_params = self.ssh_ctl_chan._connect_params_dict()
-        self.scp_conn = self.ssh_ctl_chan._build_ssh_client()
-        self.scp_conn.connect(**ssh_connect_params)
+        #ssh_connect_params = self.ssh_ctl_chan._connect_params_dict()
+        #self.scp_conn = self.ssh_ctl_chan._build_ssh_client()
+        #self.scp_conn.connect(**ssh_connect_params)
+        self.scp_conn = self.ssh_ctl_chan.remote_conn
         self.scp_client = scp.SCPClient(self.scp_conn.get_transport())
```

**Comment by TomCos** [comment]
Dug around a little, could be a rabbit hole to start to try to get Netmiko to use its own transport instead of a separate SSH connection.  Those error codes are given back by the server when establishing the new channel, so there are any number of reasons why the switch might have replied with that.

The discussion really becomes now, is it worth re-working Napalm to use the Netmiko code to spin this session up, or just sticking to the pure Paramiko implementation.  I see advantages to both.

**Comment by ktbyers** [comment]
In the long-run, I would probably prefer Netmiko (mainly so there is a consistent mechanism across platforms). It shouldn't be that hard to do, but definitely isn't on my priority-list for right now.

**Comment by TomCos** [comment]
Spent some time looking at this one today too.  The nxos base class is using pynxos file copy, so I'm not sure the right direction to go on this one, as it looks like there are 3 options.  Again, I'm new to this space, so I don't feel confident enough to make the change and properly test.  I am getting better, but not ready to tackle this one.  In the future if I understand the code more, maybe I'll re-open, but otherwise, anyone else is free to tackle.
