### ISSUE TITLE
interfaces_ip getter returns no data for nxos or nxos_ssh

### ISSUE THREAD

**Issue by mattlan** [napalm-automation/napalm#807]
I am leveraging the napalm plugin in nornir for this, I am not using napalm natively.  That being said, I don't have any napalm specific examples to share.  Below is the basic nornir code I am using.

```
from nornir.core import InitNornir
from nornir.plugins.tasks import networking
from nornir.plugins.functions.text import print_result

nr = InitNornir(config_file="config.yaml", dry_run=False)

test = nr.filter(hostname="somehost")

r = test.run(task=networking.napalm_get, getters=["interfaces_ip"])
print_result(r)
```

The getters for `facts` and `interfaces` both work for nxos, just not `interfaces_ip`.  This is what is returned back: `{'interfaces_ip': {}}`.  Same issue for nxos_ssh.

Running the same code against a junos device works as expected and I get all the requisite data.

Just looking for confirmation of a bug or something I am possibly missing/doing wrong?

**Comment by mattlan** [comment]
Think I tracked this down to napalm only looking in default VRF -- which we don't use.

**Comment by mattlan** [comment]
I was able to get this to work by changing https://github.com/napalm-automation/napalm/blob/develop/napalm/nxos/nxos.py#L810 to `ipv4_command = 'show ip interface vrf all'`.  Not sure on what the long term solution should be, but perhaps this works for now?

**Comment by ktbyers** [comment]
The above is the current expected behavior for the getter. Work is in progress on expanding the VRF support.
