### ISSUE TITLE
NX-OS using nx-api fails on get_bgp_neighbors if peer is admin down

### ISSUE THREAD

**Issue by ktbyers** [napalm-automation/napalm#870]

**Comment by ktbyers** [comment]
@carl Can you see if you can reproduce this? If so, then we should add a unit test for it and correct the behavior.

Probably should also sanity check the same thing on NX-OS SSH

**Comment by robobeaver6** [comment]
I am hitting this issue.  It seems to occur on [Line894](https://github.com/napalm-automation/napalm/blob/51ce16c1980c3ea9fd919e8097f3f59fecbae285/napalm/nxos/nxos.py#L894)
on neighbors where the state resolves to `Shut (Admin)`, which is not in the bgp_state_dict lookup dict.

**Comment by nbgr** [comment]
Currently hitting this issue with napalm 4.0.0
```

Traceback (most recent call last):
  File "/home/xxxxxxxx/myvenv/bgp_test.py", line 14, in <module>
    output = device.get_bgp_neighbors()
  File "/home/t449546/myvenv/lib/python3.9/site-packages/napalm/nxos/nxos.py", line 1100, in get_bgp_neighbors
    bgp_state = bgp_state_dict[state]
KeyError: 'Shut (Admin)'
```

**Comment by rich9474** [comment]
I think this has a pretty simple fix.  The nxos.py file just needs an extra state to match the different format of the device response.
```
    def get_bgp_neighbors(self) -> Dict[str, models.BGPStateNeighborsPerVRFDict]:
        results = {}
        bgp_state_dict = {
            "Idle": {"is_up": False, "is_enabled": True},
            "Active": {"is_up": False, "is_enabled": True},
            "Open": {"is_up": False, "is_enabled": True},
            "Established": {"is_up": True, "is_enabled": True},
            "Closing": {"is_up": True, "is_enabled": True},
            "Shutdown": {"is_up": False, "is_enabled": False},
            "Shut (Admin)": {"is_up": False, "is_enabled": False},
```
