### ISSUE TITLE
[Enhancement] Enable `file prompt quiet` only once at the beginning when configuration occurs for cisco_ios

### ISSUE THREAD

**Issue by vladola** [napalm-automation/napalm#893]
Essentially what @ktbyers described in [this comment](https://github.com/napalm-automation/napalm/issues/879#issuecomment-448303651) of issue #879 

> On your point 1, I think we should just add an attribute to the napalm object where we track the file_prompt_quiet state. Once we change this once, then we set that flag to True. Then in the napalm close() method, if that file_prompt_quiet flag has been set to True, we re-set it back to `no file prompt quiet`.
> 
> Basically since we are making a configuration change to the device, we should only do it if we need to (i.e. we shouldn't do it in open() as then you would be making this config change even for getter operations). But if we do it for config() operations and then just track the state so we only do it once, that would be a big improvement.

I'll give it a go.

**Comment by vladola** [comment]
I'll work on this in the new year. 👌

**Comment by vladola** [comment]
Starting on this ^ - been some busy days.

**Comment by ktbyers** [comment]
I think this issue was fixed. Related PR here https://github.com/napalm-automation/napalm/pull/918
