### ISSUE TITLE
File Transfer to Remote Device Failed (IOS)

### ISSUE THREAD

**Issue by nathanjaya** [napalm-automation/napalm#916]
**Description of Issue/Question**
when using napalm to upload a config file, the napalm sends out an error message 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm/ios/ios.py", line 256, in load_replace_candidate
    raise ReplaceConfigException(msg)
napalm.base.exceptions.ReplaceConfigException: File transfer to remote device failed

**Setup**
**napalm version**
napalm version 2.3.3
napalm-base version 1.0.0

**IOS Version**
IOS 3700
Interface Fa

**Step to Reproduce the Issue**
the router configuration:
aaa
user privilege 15
ssh
ip address
vty with privilege 15
ip scp server

I succesfully do get_facts and get_config using python2.7
trying to push config file which contains only hostname and IP address

**Comment by ktbyers** [comment]
Can you post the full stack trace?

Also does your user have direct privilege 15 access or do you have to call `enable`?

Have you tried using an inline transfer? Which is an optional_args that you can specify to napalm (inline_transfer = True).

**Comment by nathanjaya** [comment]
File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/napalm/ios/ios.py", line 256, in load_replace_candidate
    raise ReplaceConfigException(msg)
napalm.base.exceptions.ReplaceConfigException: File transfer to remote device failed

that's already the full trace

my user have direct privilege 15 access
I have tried using inline transfer, and get more errors

**Comment by ktbyers** [comment]
How are you trying to execute this via a Python script, via Ansible, via Salt?

**Comment by nathanjaya** [comment]
I'm executing it from python CLI
But I've already found the solution, beginner's mistake

Thanks btw
