### ISSUE TITLE
get_vlans getter

### ISSUE THREAD

**Issue by bobthebutcher** [napalm-automation/napalm#927]
Opening this issue to track the implementation of a `get_vlans` getter. Based on the discussion in #919 
919 is tracking per interface port type and vlan assignment, where this issue will track the vlan database potentially capturing vlans configured but not assigned to an interface.

Return structure being spit balled is as follows. 
```
{ 
    1: {
        "name": "vlan-1",
        "interfaces": ["ge-0/0/1", "ge-0/0/2"]
    }, 
    2: {
        "name": "vlan-2",
        "interfaces": []
    }
}
```
I am currently working on the `cumulus` community driver implementation and can work the `junos` driver implementation once I am done.

**Comment by VictorPavlushin** [comment]
Implemented for ios, nxos and nxos_ssh.
https://github.com/napalm-automation/napalm/pull/948

**Comment by ggiesen** [comment]
I noticed this implementation doesn't deal with any of the Cisco Metro E platforms (ME3400E, ME3600X, M3800X, ASR920) that use bridge-domains. Would extending this getter or writing a new getter that covers off those platforms be the right approach?

**Comment by ktbyers** [comment]
I am going to close this as I think the original item is done.

@ggiesen I think you should create a separate issue if you think there is an enhancement that needs made to the existing getter (or a different getter that you think needs implemented).
