### ISSUE TITLE
NXOS -MD5 failure on config replace or config merge from file

### ISSUE THREAD

**Issue by b-marcum** [napalm-automation/napalm#931]
I receive the following errors when calling load_replace_candidate(filename=chkpoint_file). I actually came across this in Nornir originally which prompted the following example to reproduce this in Napalm/Netmiko natively.

**Test Code**
```
from __future__ import print_function, unicode_literals
from napalm import get_network_driver

driver = get_network_driver('nxos')

hostname = '192.168.56.14'
username = 'tester'
password = 'omitted'
chkpoint_file = 'configs/Lab-93180-A.ckpt'

device = driver(hostname, username, password)

device.open()

device.load_replace_candidate(filename=chkpoint_file)

print(device.compare_config())

device.discard_config()
```

**Output**
```
Traceback (most recent call last):
  File "/home/user/dev/sandbox/lib/python3.6/site-packages/napalm/nxos/nxos.py", line 110, in load_replace_candidate
    overwrite_file=True,
  File "/home/user/dev/sandbox/lib/python3.6/site-packages/netmiko/scp_functions.py", line 100, in file_transfer
    raise ValueError("MD5 failure between source and destination files")
ValueError: MD5 failure between source and destination files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_napalm_replace.py", line 24, in <module>
    device.load_replace_candidate(filename=chkpoint_file)
  File "/home/user/dev/sandbox/lib/python3.6/site-packages/napalm/nxos/nxos.py", line 63, in wrap_function
    func(self, filename=filename, config=config)
  File "/home/user/dev/sandbox/lib/python3.6/site-packages/napalm/nxos/nxos.py", line 120, in load_replace_candidate
    raise ReplaceConfigException(msg)
napalm.base.exceptions.ReplaceConfigException: Could not transfer file. There was an error during transfer. Please make sure remote permissions are set.
```
This has been reproduced in Python 3.7, 3.6, and 2.7. I've confirmed in both Linux and Windows on the nxos and nxos_ssh Napalm drivers. nxapi and scp-server features are both enabled. NXOS versions are 7.0(3)I7(5a) on the physical model 93180YC-EX and 7.0(3)I7(2) on virtual appliance (9000v) in GNS3. Communication seems file otherwise as I am able to call get_facts and other functions just fine.

Any insight into what's causing this behavior would be greatly appreciated. Feel free to reach out of there is any information that may help to isolate this issue I intend to leverage this for large automation effort.

**Comment by pwnsmack** [comment]
I've tested on other platforms (Nexus 5596 and 5020 switches which do not encounter this problem. This issue appears to be specific to the Nexus 9000 series and I have also replicated this issue in Netmiko. The scp copy is actually completing successfully but the MD5 parse is failing. I can work around it by passing "disable_md5=True" argument into the "file_transfer" function.

Is there any way to pass this argument into Napalm to bypass the MD5 check?

**Comment by ktbyers** [comment]
@pwnsmack I don't think we should bypass the MD5 check. I think we should fix the underlying issue that is causing the MD5 parsing to fail.

**Comment by ktbyers** [comment]
What does `show file bootsystem:/candidate_config.txt md5sum` show on one of the devices that failing.

Note, the filesystem and filename might be different depending on your device and what you are doing. Realistically you can probably show the output of this for some file on the device (just so we can see the output format).

Here is what is executed under the hood for retrieving the MD5

https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco/cisco_nxos_ssh.py#L109


Also it is possible that the global_delay_factor argument to NAPALM just needs increased to 2 or to 4. You can pass this in via optional_args.

**Comment by b-marcum** [comment]
Thanks for responding Kirk, I'm a huge fan of your work having attended several of your courses and greatly appreciate your feedback.

Unfortunately, passing the global_delay_factor arguments of 2 and 4 results in the same outcome with (with extended run time).

I added the session_log argument which shows the file (candidate_config.txt) residing on the system with the proper hash. The file simply contains the four bytes `test`. 

Extensive tracing confirm that the `source_md5` variable matches the session log but I can't seem to catch the `remote_md5` getting set due to the chatty scp_channel debugging. I do see the following output variable being sent back even when the file already exists in bootflash: yet it proceeds with the copy.

```
ouput = `'show file bootflash:candidate_config.txt md5sum

098f6bcd4621d373cade4e832627b4f6
NXOS7# '` 
```

One interesting observation I just noticed when comparing Nexus 9000 output that of the working Nexus 5596 device is that the 5K has a newline following the MD5 hash. 

Any chance a quick regex expression adjustment might resolve this?


**Sample of 5596 output**
```
N5596# show file bootflash:candidate_config.txt md5sum

098f6bcd4621d373cade4e832627b4f6

N5596# 
```

**Sample code**
```
from __future__ import print_function, unicode_literals
from napalm import get_network_driver
from netmiko import ConnectHandler, file_transfer

driver = get_network_driver('nxos')

hostname = '192.168.56.14'
username = 'tester'
password = 'omitted'
optional_args = {'session_log': 'my_file.out', 'global_delay_factor': 2}
chkpoint_file = 'configs/test.ckpt'

device = driver(hostname, username, password, optional_args=optional_args)
device.open()
device.load_replace_candidate(filename=chkpoint_file)
print(device.compare_config())
device.discard_config()
```

**Nexus 9000v Session Log Output**
```

Cisco NX-OS Software
Copyright (c) 2002-2017, Cisco Systems, Inc. All rights reserved.
Nexus 9000v software ("Nexus 9000v Software") and related documentation,
files or other reference materials ("Documentation") are
the proprietary property and confidential information of Cisco
Systems, Inc. ("Cisco") and are protected, without limitation,
pursuant to United States and International copyright and trademark
laws in the applicable jurisdiction which provide civil and criminal
penalties for copying or distribution without Cisco's authorization.

Any use or disclosure, in whole or in part, of the Nexus 9000v Software
or Documentation to any third party for any purposes is expressly
prohibited except as otherwise authorized by Cisco in writing.
The copyrights to certain works contained herein are owned by other
third parties and are used and distributed under license. Some parts
of this software may be covered under the GNU Public License or the
GNU Lesser General Public License. A copy of each such license is
available at
http://www.gnu.org/licenses/gpl.html and
http://www.gnu.org/licenses/lgpl.html
***************************************************************************
*  Nexus 9000v is strictly limited to use for evaluation, demonstration   *
*  and NX-OS education. Any use or disclosure, in whole or in part of     *
*  the Nexus 9000v Software or Documentation to any third party for any   *
*  purposes is expressly prohibited except as otherwise authorized by     *
*  Cisco in writing.                                                      *
***************************************************************************

NXOS7# 


NXOS7# terminal length 0


NXOS7# 


NXOS7# 


NXOS7# dir bootflash:candidate_config.txt

          4    Mar 04 01:34:48 2019  candidate_config.txt

Usage for bootflash://sup-local
 1427357696 bytes used
 2109861888 bytes free
 3537219584 bytes total

NXOS7# 


NXOS7# show file bootflash:candidate_config.txt md5sum

098f6bcd4621d373cade4e832627b4f6
NXOS7# 


NXOS7# dir bootflash:

       4096    Jan 16 00:32:58 2019  .rpmstore/
       4096    Jan 16 00:33:12 2019  .swtam/
       1827    Jan 16 00:34:32 2019  20190116_003416_poap_29809_init.log
          4    Mar 04 01:34:48 2019  candidate_config.txt
      21087    Jan 16 01:46:31 2019  config_2019-01-15_20:46:31.032912
  885554688    Nov 22 22:06:16 2017  nxos.7.0.3.I7.2.bin
          0    Jan 16 00:35:09 2019  platform-sdk.cmd
       4096    Jan 16 00:34:12 2019  scripts/
      21087    Jan 16 01:45:17 2019  sot_file
       4096    Jan 16 00:34:15 2019  virt_strg_pool_bf_vdc_1/
       4096    Jan 16 00:33:28 2019  virtual-instance/
         59    Jan 16 00:33:18 2019  virtual-instance.conf

Usage for bootflash://sup-local
 1427357696 bytes used
 2109861888 bytes free
 3537219584 bytes total

NXOS7# 


NXOS7# show file bootflash:candidate_config.txt md5sum

098f6bcd4621d373cade4e832627b4f6
NXOS7# 
```

**Comment by b-marcum** [comment]
Any ideas? I seem to have hit a wall on this

**Comment by b-marcum** [comment]
@ktbyers, I may have isolated the issue but I don't know how to fix it. 

The MD5 hash is being stripped from the output variable at the following line:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/base_connection.py#L827

Here's what the raw output is prior to the sanitized_output function:
```
output = 'show file bootflash:candidate_config.txt md5sum\r\r\n098f6bcd4621d373cade4e832627b4f6\rNXOS7# '
```

Here are the variables prior to strip_prompt function:
```
base_prompt = 'NXOS7'
output = '098f6bcd4621d373cade4e832627b4f6NXOS7# '
```

Following the strip_prompt function, `output = ''`

**Comment by ktbyers** [comment]
@b-marcum Does it work if you change this line:

https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco/cisco_nxos_ssh.py#L23

I would probably just try the following:

```python
newline = re.compile(r"\r\n)")
return newline.sub(self.RESPONSE_RETURN, a_string)
```

It might also be interesting to print out the following right before this substitution:

```
print(repr(a_string))
```

So we can see exactly what the newline pattern is.

**Comment by ktbyers** [comment]
Adding @carlniger onto this issue.

**Comment by b-marcum** [comment]
@ktbyers @carlniger - Thanks for the quick response

I added the print statement suggested and confirmed that the the output of `a_string` throughout is as follows:
```
'NXOS7#'
'NXOS7#'
'dir bootflash:candidate_config.txt\r\r\n          4    Mar 15 08:57:28 2019  candidate_config.txt\r\n\r\nUsage for bootflash://sup-local\r\n 1427357696 bytes used\r\n 2109861888 bytes free\r\n 3537219584 bytes total\r\n\rNXOS7# '
'dir bootflash:candidate_config.txt\n'
'NXOS7#'
'show file bootflash:candidate_config.txt md5sum\r\r\n098f6bcd4621d373cade4e832627b4f6\rNXOS7# '
'show file bootflash:candidate_config.txt md5sum\n'
```

I tried the newline change suggested which resulted in the following output:
```
'NXOS7#'
Traceback (most recent call last):
  File "C:\data\dev\sandbox\lib\site-packages\napalm\nxos\nxos.py", line 52, in wrap_function
    netmiko_object = self._netmiko_device
AttributeError: 'NXOSDriver' object has no attribute '_netmiko_device'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/data/dev/lowes/nornir_framework/test_napalm_replace.py", line 27, in <module>
    device.load_replace_candidate(config=config)
  File "C:\data\dev\sandbox\lib\site-packages\napalm\nxos\nxos.py", line 61, in wrap_function
    device_type=device_type, netmiko_optional_args=netmiko_optional_args
  File "C:\data\dev\sandbox\lib\site-packages\napalm\base\base.py", line 87, in _netmiko_open
    **netmiko_optional_args
  File "C:\data\dev\sandbox\lib\site-packages\netmiko\ssh_dispatcher.py", line 228, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "C:\data\dev\sandbox\lib\site-packages\netmiko\base_connection.py", line 313, in __init__
    self._try_session_preparation()
  File "C:\data\dev\sandbox\lib\site-packages\netmiko\base_connection.py", line 723, in _try_session_preparation
    self.session_preparation()
  File "C:\data\dev\sandbox\lib\site-packages\netmiko\cisco\cisco_nxos_ssh.py", line 15, in session_preparation
    self.set_base_prompt()
  File "C:\data\dev\sandbox\lib\site-packages\netmiko\base_connection.py", line 1040, in set_base_prompt
    prompt = self.find_prompt(delay_factor=delay_factor)
  File "C:\data\dev\sandbox\lib\site-packages\netmiko\base_connection.py", line 1077, in find_prompt
    prompt = self.normalize_linefeeds(prompt)
  File "C:\data\dev\sandbox\lib\site-packages\netmiko\cisco\cisco_nxos_ssh.py", line 24, in normalize_linefeeds
    newline = re.compile(r"\r\n)")#"(\r\r\n|\r\n)")
  File "C:\data\dev\sandbox\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:\data\dev\sandbox\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\data\dev\sandbox\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\data\dev\sandbox\lib\sre_parse.py", line 944, in parse
    raise source.error("unbalanced parenthesis")
re.error: unbalanced parenthesis at position 4
```

Then I tried the following code change on the line below which fixed it for me ( ͡° ͜ʖ ͡°)
https://github.com/ktbyers/netmiko/blob/develop/netmiko/cisco/cisco_nxos_ssh.py#L25
```
        return newline.sub(self.RESPONSE_RETURN, a_string).replace("\r", "\n")
```
I'm not entirely certain what the broader repercussions for this change is or if there is a cleaner way but this got me though the issue. I'm also not sure why the newline behavior is different for Nexus 9K platform as a whole or just a bug in the output of the `show file {filename} md5sum` command.

**Comment by ktbyers** [comment]
Okay, that makes I messed up the regex change in my original response.

Okay, so this works then--correct?

```python
        newline = re.compile(r"(\r\r\n|\r\n)")
        return newline.sub(self.RESPONSE_RETURN, a_string).replace("\r", "\n")
 ```

**Comment by carlniger** [comment]
@ktbyers just tested against the new n9ks (nxos.9.2.3.bin) in the lab; without @b-marcum's fix, I was able to reproduce the error; with the fix proposed, it worked as expected.

However, with the change in place it broke file transfers against our older nexus boxes (7.3(1)D1(1)).

I'll dig into it more a bit later today to see if I can come up with a draft fix that works against both platforms.

**Comment by ktbyers** [comment]
https://github.com/ktbyers/netmiko/pull/1140

**Comment by ktbyers** [comment]
Fixed in Netmiko develop branch
