### ISSUE TITLE
Adding Support for Onyx Devices Using NAPALM

### ISSUE THREAD

**Issue by anasbadaha** [napalm-automation/napalm#932]
Hi,

I'm working with Mellanox Company and we are planning to adding support for our switches that are using Onyx OS because of some of our customers needs to use it.

Anas Badaha

**Comment by anasbadaha** [comment]
Hi @mirceaulinic,

I have created this issue in order to adding support for Onyx driver. Can you please create a repository for our new driver on https://github.com/napalm-automation-community in order to push my code for onyx-ssh driver on it ?

Best Regards,
Anas Badaha

**Comment by samerd** [comment]
Hi,
Me and Anas are Mellanox Employees.
We have several customers who use napalm automation for salt, and we need to add support for onyx devices in napalm automation.
@anasbadaha already prepared some functions and we need to push it into your repositories.
we tried to contact the repository https://github.com/napalm-automation-community owners but seems the mail is not up-to-date
please advise.

Thanks,
Samer Deeb

**Comment by ktbyers** [comment]
@anasbadaha @samerd I would join the networktocode.slack.com Slack channel and go to the napalm and/or salt sub-channels and then coordinate in there (that is probably the easiest way to do the communication).

You can join that slack channel by going here: http://slack.networktocode.com/


Regards, Kirk

**Comment by dbarrosop** [comment]
@anasbadaha @samerd I can create the repo for you and make you both admins. Is `napalm-onyx` the name you want?

**Comment by samerd** [comment]
@dbarrosop : that would be great, the name is OK.
Thanks so much for your help

**Comment by dbarrosop** [comment]
Done, please confirm you got access and let me know if you need anything else. Closing the ticket as well.

**Comment by samerd** [comment]
Thanks so much @dbarrosop 
I've got access

**Comment by anasbadaha** [comment]
Thanks a lot @dbarrosop
I have got the access as well
