### ISSUE TITLE
Update FreeBSD installation instructions

### ISSUE THREAD

**Issue by neirbowj** [napalm-automation/napalm#934]
In `docs/installation`, `ios.rst`, `iosxr.rst`, and `junos.rst` all refer to the `pkg_add` command which was removed from FreeBSD starting in 10.0 (2014-01-20). The new system package management utility is `pkg` and its sub-commands (e.g. `pkg install`).

I would be glad to prepare a patch for these docs, but first need some guidance. What installation scenario(s) do you wish to cover in the NAPALM docs?

1. Native, pre-built package installation
2. Install from source
3. `pip install`
4. Something else?

NAPALM v2.3.0 was added to the FreeBSD ports tree on 2018-04-05. The port is currently at 2.3.3, with an update to 2.4.0 in the works. It can be installed, _along with any missing dependencies_, with `pkg install net-mgmt/py-napalm`. If a non-default version of Python is desired, use `pkg install py36-napalm`, for instance. Right now, the port unconditionally pulls in dependencies for all supported transports.

FreeBSD [discourages the use of pip at the system level](https://svnweb.freebsd.org/ports/head/devel/py-pip/pkg-message?revision=407947&view=markup&pathrev=493888), because it conflicts with system-managed packages. To install from source, the recommended approach would be to use `pkg` to install immediate dependencies available in the ports tree (e.g. `net-mgmt/py-junos-eznc`), then `python setup.py install --user` to avoid polluting the system.

Alternatively, and to be able to `pip install` modules that aren't available in the ports tree or for which the port has not yet been upgraded to the desired version, working in a virtualenv is recommended.

Considering the foregoing, how would you like me to craft a doc patch?

**Comment by mirceaulinic** [comment]
Hi @neirbowj. It's very nice that there's a package for FreeBSD, I wasn't aware of that. I personally prefer to install from system packages whenever available (and I think that's the recommendation on any platform, when possible). I would suggest to go ahead and document with this perspective in mind, as the other possibility using pip is not platform-specific. Cheers!

**Comment by ktbyers** [comment]
@neirbowj Do you want to submit a PR to update the documentation here?

**Comment by neirbowj** [comment]
Yes, I do. I haven't had the bandwidth recently, but I intend to return to this, hopefully next week.
