### ISSUE TITLE
is there a way to check if a port is err-disabled?

### ISSUE THREAD

**Issue by sincerywaing** [napalm-automation/napalm#941]
Or Is there a getter to get interface down reason?

**Comment by ktbyers** [comment]
I don't think so. We would have to modify a getter to support this.

**Comment by sincerywaing** [comment]
Thanks Kirk. I’m also digging if there is any snmp oid could support this but failed.

Do you happen to aware any?

**Comment by ktbyers** [comment]
@sincerywaing Yes, I don't know about SNMP and where it might exist there. I would probably look at ntc-templates as I think you could possibly retrieve it from that.

**Comment by mirceaulinic** [comment]
Hi @sincerywaing - not sure if you've looked at napalm-logs which you can use to get syslog notifications in a standard format, also for interface down: http://napalm-logs.com/en/latest/messages/INTERFACE_DOWN.html By the looks of it, however, it doesn't look like the syslog messages contain the reasoning why an interface went down.

**Comment by ktbyers** [comment]
I don't think there are any additional actions here.
