### ISSUE TITLE
get_interface Additional Parameters

### ISSUE THREAD

**Issue by robobeaver6** [napalm-automation/napalm#949]
the get_interface getter only ascertains very basic information.  It would be very beneficial if it could also ascertain the following:

- Type of interface / Hardware Type
  - Ethernet
    - Routed / Switchport
    - Switchport Mode
      - Encapsulation Protocol
  - VLAN SVI
  - Port Channel
  - Tunnel {type}
  - Loopback
- MTU
- Media Type
- Bandwidth

There are probably several other Physical Port parameters that others would find useful, but these are the ones I could think of given my current use case.

**Comment by AmbicaY** [comment]
+1 

Hardware type is definitely needed. MTU should be an easy one.

**Comment by mirceaulinic** [comment]
Hi @robobeaver6: @yeled has been working on adding the required support for the MTU - see https://github.com/napalm-automation/napalm/pull/940. Please feel free to submit a similar PR for the rest. Thanks!

**Comment by VictorPavlushin** [comment]
Hi!
I am working on the import and subsequent inventory of network devices (switches, servers: windows and linux) in the netbox.
In that case I use napalm, netbox-netprod-importer and ansible (to collect standard facts and handwritten) for this.
In this request, there is information of interest to me, if you help me with a technical task (commands to get the necessary information) I will try to implement it.
I have the opportunity to check only for drivers ios, nxos and nxos_ssh

**Comment by ktbyers** [comment]
Propose a change to the getter and/or just implement and submit a PR it including tests for all of the core napalm platforms.

If it is a completely new getter then create an issue with the new getter proposal: getter name, returned data structure. Note, you will probably need to implement it on all of the core napalm platforms in order for it to get approved.

The above referenced MTU PR is a very good reference example for doing this.

Also some related discussion here:

https://github.com/napalm-automation/napalm/issues/919
