### ISSUE TITLE
Q: makes sense for devices like linux, openwrt, tiny-routers ?

### ISSUE THREAD

**Issue by ka7** [napalm-automation/napalm#975]
### Description of Issue/Question

i like the concept of __napalm__ ( esp. the get_facts() ) 

Would it make sense, to extend (plugin) that also to all net-devices, like linux servers, openwrt-based whatever, tiny routers ( like small "http config" switches ) ?
_some_ automation ( set_timeserver(), set_logserver(), enable/disabe ports  should also be easy to do here) 
( BTW: I'm not shy to write& share some code )

i think into this direction esp. when seeing that in combination with __netbox__.
( once defining the as-wished, easy to prove things are still like they should be; and yes, for some tiny home-setup this might look crazy, but running same kernel on a raspi _and_ a top-500 computer.. too )

### Did you follow the steps from https://github.com/napalm-automation/napalm#faq
(Place an ``x`` between the square brackets where applicable)

- [x] Yes
- [ ] No

### napalm version
(Paste verbatim output from `pip freeze | grep napalm` between quotes below)

```
n/a
```

### Network operating system version
(Paste verbatim output from `show version` - or equivalent - between quotes below)

```
new stuff, like linux-servers, open-wrt based, ubiquiti-devices, ...
```

### Error Traceback
(Paste the complete traceback of the exception between quotes below)

```
n/a
```

**Comment by ktbyers** [comment]
You should check out the community drivers:

https://github.com/napalm-automation/napalm/issues/468


Regards, Kirk
