### ISSUE TITLE
Napalm get_facts broken for cisco

### ISSUE THREAD

**Issue by AmbicaY** [napalm-automation/napalm#979]
get_facts fails for cisco devices when it tries to parse the output for the command "sh ip int brief"

There is an empty line in the output of this command on few of my cisco devices, which is causing this issue.

napalm version: 
napalm==2.4.0

error:
Traceback (most recent call last):
         File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 178, in call
           out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
         File "/usr/local/lib/python2.7/dist-packages/napalm/ios/ios.py", line 984, in get_facts
           interface = line.split()[0]
       IndexError: list index out of range

In ios.py, I think we need to change the line 982 to:
if "Interface " in line or len(line.split()) < 1:

**Comment by ktbyers** [comment]
@AmbicaY Can you post an example `show ip int brief` that is causing things to break?

**Comment by AmbicaY** [comment]
spare-switch#show ip int brief
Any interface listed with OK? value "NO" does not have a valid configuration

Interface              IP-Address      OK? Method Status                Protocol
FastEthernet1          10.19.90.126    YES DHCP   up                    up
GigabitEthernet3/1     unassigned      YES unset  down                  down
GigabitEthernet3/2     unassigned      YES unset  down                  down
GigabitEthernet3/3     unassigned      YES unset  down                  down
GigabitEthernet3/4     unassigned      YES unset  down                  down
GigabitEthernet3/5     unassigned      YES unset  down                  down
GigabitEthernet3/6     unassigned      YES unset  down                  down
GigabitEthernet3/7     unassigned      YES unset  down                  down
GigabitEthernet3/8     unassigned      YES unset  down                  down
GigabitEthernet3/9     unassigned      YES unset  down                  down
GigabitEthernet3/10    unassigned      YES unset  down                  down
GigabitEthernet3/11    unassigned      YES unset  down                  down
GigabitEthernet3/12    unassigned      YES unset  down                  down
GigabitEthernet3/13    unassigned      YES unset  down                  down
GigabitEthernet3/14    unassigned      YES unset  down                  down
GigabitEthernet3/15    unassigned      YES unset  down                  down
GigabitEthernet3/16    unassigned      YES unset  down                  down
GigabitEthernet3/17    unassigned      YES unset  down                  down
GigabitEthernet3/18    unassigned      YES unset  down                  down
.......
